### ISSUE TITLE
Falsche Anzeige des Datums bei json table

### ISSUE THREAD

**Issue by bergjet** [inventwo/ioBroker.vis-inventwo#100]
Adapter 2.5.11
Es wird immer der 19.Jan. 1970 angezeigt.
Der Timestamp liegt in Millisekunden und nicht in Sekunden vor.
<img width="345" alt="1606686701330-bildschirmfoto-2020-11-29-um-22 49 25" src="https://user-images.githubusercontent.com/4241968/100724512-3ffb3880-33c3-11eb-8de2-b84e871bc142.png">

**Comment by jkvarel** [comment]
@bergjet schaue ich mir an. Wenn der Fehler behoben ist gebe ich hier bescheid

**Comment by truegreyhound** [comment]
Das liegt an den Zeilen 1327 und 1328, die bitte löschen
```
if (cellValue.toString().length == 13)
datetime = datetime / 1000;
```

**Comment by bergjet** [comment]
Hat keine Änderung gebracht.

**Comment by truegreyhound** [comment]
"iobroker upload vis-inventwo" durchgeführt, nach Neustart ioBroker hat es dann bei mir funktioniert.

![image](https://user-images.githubusercontent.com/24899637/101803731-1f448880-3b11-11eb-9c97-5497df17fef6.png)

**Comment by bergjet** [comment]
Habe ich nun auch gemacht, aber nein, klappt nicht.
`if (cellValue.toString().length == 13)
datetime = datetime / 1000;`
Aber wie das verstehe, wird hier die 13 stellige Zahl durch Tausend dividiert. Was auch richtig ist.
Denn wenn ich vom Datum Datenpunkt die letzten 3 Stellen lösche, wird das Datum richtig angezeigt.

**Comment by truegreyhound** [comment]
In meinen Datenpunkten speichere ich grundsätzlich datetime values, also in meinem Leben wird es 13 stellig bleiben.
Der Adapter prüft auf numerisch und versucht bei string das Datum zu parsen.
Das Skript gibt es unterhalb des Homeverzeichnisses von ioBroker an 2 Stellen:
- node_modules\iobroker.vis-inventwo\widgets\vis-inventwo\js\vis-inventwo.js
- iobroker-data\files\vis\widgets\vis-inventwo\js\vis-inventwo.js

Die erste Datei ist quasi das Original und das 2., welches durch die Installation/ upload dahin kopiert wird.

```
if (cellValue.toString().length == 13)
	datetime = datetime / 1000;
```

Den Sinn dieser Anweisung verstehe ich nicht, warum den Zeitwert ungenauer machen, als er ist? Zumal in den Formatierungen auch die Millisekunden ausgegeben werden können, was ich an einigen Stellen auch gern nutze (vereinfacht das auffinden von Logeinträgen).

Im Funktionsaufruf der zuvor definierten Funktion **_getDateString_** wird aus **datetime** ein Datumswert erzeugt.
```
var formattedDate = getDateString(new Date(datetime), data["iTblCellDatetimeFormat" + (i + 1)]);
```

Mit vollständigerm **_datetime_** wird bei mir dann auch das korrekte Datum erzeugt, mit der Kürzung erhalte ich immer 1970....
Zusätzlich habe ich bei mir auch eingebaut, dass bei datetime = 0 in der Tabelle "- - -" geschrieben wird (Spalte vor der IP im Screenshot).

Wenn du dich ein bisschen mit den Browser-Entwickler-Tools auskennst (F12), dann kannst du z. B. in Chrome auf dem Tab Sources die vis-inventwo.js öffnen und nachschauen, ob deine Codeänderungen überhaupt aktiv sind.

**Comment by bergjet** [comment]
Wenn ich die beiden Zeilen in
**node_modules\iobroker.vis-inventwo\widgets\vis-inventwo\js\vis-inventwo.js**
lösche, danach das upload ausführe, müsste auch die Datei
**iobroker-data\files\vis\widgets\vis-inventwo\js\vis-inventwo.js**
geändert sein?

**Comment by truegreyhound** [comment]
soweit ich weis ja, ansonsten iobroker upload vis ausführen, 
ich ändere in solchen Situationen meistens beide Dateien.

**Comment by bergjet** [comment]
So, habe nun beide Skript geändert und nun geht es.
Danke.

**Comment by jkvarel** [comment]
Ich habe die beiden Zeilen entfernt und konnte bis jetzt keine Fehler feststellen.
Version 2.6.0 (latest)

**Comment by bergjet** [comment]
Funktioniert **nicht**.
Die beiden Zeilen stehen nun in Zeile 1590, 1591.
Erst wenn man diese löscht geht es wieder.
