### ISSUE TITLE
Shelly 1L

### ISSUE THREAD

**Issue by McWoolf** [inventwo/ioBroker.vis-inventwo#101]
Es geht um den Shell 1L, welcher noch nicht im ioBroker-Adapter vorhanden ist und somit immer Fehler bringt bzw. noch nicht über ioBroker steuerbar ist.
Wäre es möglich diesen in absehbarer Zeit hinzuzufügen?

Danke an die Entwickler, meine Hochachtung was ihr hier leistet.

**Comment by skvarel** [comment]
Hallo @McWoolf 

Was hat denn der Shelly mit unserem VIS-Adapter zu tun? Wir haben keinen Einfluss auf den Shelly-Adapter und stellen lediglich Widgets zur verfügung.

Gruß, Sven.

**Comment by McWoolf** [comment]
Oh sorry falsche Abteilung.

**Comment by jkvarel** [comment]
@McWoolf das geht meines Wissens nicht. Ich kann das Issue nur in andere Repos von mir verschieben aber nicht in andere. Da müsstest du an der richtigen Stelle ein neues aufmachen.
