### ISSUE TITLE
Änderung Funktionsname im jedem Widget

### ISSUE THREAD

**Issue by Lucifor1976** [inventwo/ioBroker.vis-inventwo#102]
Hallo, ich hätte eine Kleinigkeit die geändert werden sollte. Mich verwirrt es ein wenig.

Istzustand: In jedem Widget Ausführung "Stil" kann zwischen "horizontal" und "senkrecht" gewechselt werden.

Sollzustand: Entweder "Horizontal" und "Vertikal" oder "Waagerecht" und "Senkrecht" verwenden.

Das wäre echt toll.

**Comment by jkvarel** [comment]
@Lucifor1976 das ist mir so nie aufgefallen. Danke. Werde ich noch ändern.

**Comment by jkvarel** [comment]
Hab ich mit Version 2.7.0 geändert. Sollte jetzt überall einheitlich sein. Falls es irgendwo noch falsch ist gerne bescheid gebenn
