### ISSUE TITLE
JSON table: Datumsformatierung an Standard anpassen

### ISSUE THREAD

**Issue by truegreyhound** [inventwo/ioBroker.vis-inventwo#104]
Die hier verwendete Syntax hält sich nicht an die etablierte Nutzung.

Üblicherweise bedeutet
yyyy = 2020, yy = 20
mm = 09, m = 9
analoges gilt für Tag, Stunden, Minuten und Sekunden.

Außerdem würde ich mir die Anzeige der hundertstel wünschen.

**Comment by jkvarel** [comment]
@truegreyhound nach welchen Syntax gehst du da? Es gibt nicht nur einen richtigen Syntax

**Comment by truegreyhound** [comment]
Du hast mit Sicherheit Recht, aber in den über 30 Jahren, in denen ich im "Geschäft" bin, ist mir so eine "Sparvariante" noch nicht untergekommen. ;-)
Ich hatte gewohnheitsmäßig yyyy-mm-dd usw. eingegeben und mich dann über das lustige Datum von 1970 mit den komischen Zeichen dazwischen gewundert. Beim erneuten Lesen habe ich dann natürlich gesehen, dass nur jeweils ein Zeichen gesetzt werden darf.
Kann von mir aus auch geschlossen werden, aber die mögliche Formatierung der millis sollte auch in der Anzeige stehen, finde ich gut!

**Comment by jkvarel** [comment]
yyyy-mm-dd ist mir auch bekannnt.

Ich kann jetzt nur schlecht das Format ändern, weil sonst bei jedem das Datum falsch angezeigt wird. 
Millisekunden ist jetzt auch drin.
