### ISSUE TITLE
JSON table; Wenn timestamp == 0, dann bitte nichts oder einen konfigurierbaren Platzhalter anzeigen, z. B. "---".

### ISSUE THREAD

**Issue by truegreyhound** [inventwo/ioBroker.vis-inventwo#105]
Wenn in JSON-Tabelle Wert mit timestamp == 0, dann bitte nichts oder einen konfigurierbaren Platzhalter anzeigen, z. B. "---".

**Comment by truegreyhound** [comment]
in vis-inventwo.js in~ Zeile 1324 datetime = parseInt(cellValue);

durch 
```
if (cellValue == 0) {
   return "- - -";
} else {
   datetime = parseInt(cellValue);
}
```

**Comment by jkvarel** [comment]
Werde ich ergänzen

**Comment by truegreyhound** [comment]
Danke

**Comment by jkvarel** [comment]
Es kann nun für jede Spalte ein Platzhalter eingetragen werden, wenn Timestamp = 0 ist oder wenn die Zelle leer ist:
Version 2.6.0 (latest)

**Comment by truegreyhound** [comment]
Ja, das ist schön, aber leider bei der Umsetzung etwas über das Ziel hinausgeschossen, es fehlt die Beschränkung auf das Format "datetime"
![image](https://user-images.githubusercontent.com/24899637/102812164-e33ddd00-43c6-11eb-8f51-deaafc1ad15c.png)
![image](https://user-images.githubusercontent.com/24899637/102812113-ca352c00-43c6-11eb-8b13-8615869755f8.png)
Boolean **_FALSE_**  und number **_0_** werden jetzt auch als "nicht vorhanden interpretiert.
