### ISSUE TITLE
JSON table: Kopfzeile fixierbar machen

### ISSUE THREAD

**Issue by truegreyhound** [inventwo/ioBroker.vis-inventwo#106]
JSON table: Kopfzeile fixiebar machen, so dass sie nicht vertical mitgescrollt wird

**Comment by jkvarel** [comment]
Werde ich umsetzen

**Comment by truegreyhound** [comment]
Danke

**Comment by jkvarel** [comment]
Tabellenkopf kann ab Version 2.7.0 fixiert werden
