### ISSUE TITLE
JSON table: mit klick auf Spalte diese sortieren

### ISSUE THREAD

**Issue by truegreyhound** [inventwo/ioBroker.vis-inventwo#107]
JSON table: mit klick auf Spalte diese sortieren, abwechselnd auf- bzw. absteigend

**Comment by jkvarel** [comment]
Werde ich ebenfalls umsetzen

**Comment by truegreyhound** [comment]
Danke

**Comment by jkvarel** [comment]
Per Klick auf die Kopfzeile kann die Tabelle sortiert werden.
Version 2.6.0 (latest)
