### ISSUE TITLE
Versionen größer 2.5.8 zerstören vorhandene Views

### ISSUE THREAD

**Issue by ITCrowdIOB** [inventwo/ioBroker.vis-inventwo#114]
Ein Update des Adapters auf Versionen größer 2.5.8 macht alle Views, die Inventwo Widgets, beinhalten unbrauchbar.

2.5.8
![12](https://user-images.githubusercontent.com/64137907/102092133-01806780-3e20-11eb-9aa2-1875f1bd10d1.PNG)

2.5.9 - 2.5.11
![11](https://user-images.githubusercontent.com/64137907/102092167-0ba26600-3e20-11eb-9955-5a43d4fb9e23.PNG)

Wie man sieht, sind ausschließlich die Inventwo Widgets betroffen. An den Stellen der Widgets ist nichts mehr auswählbar. Sie sind auch nicht transparent.

Folgendes habe ich versucht.

Neuinstallation des Adapters. Keine Verbesserung
Reimport des Views nach Update. Keine Verbesserung.

Nur eine Rückkehr auf Version 2.5.8 stellt den fehlerfreien Zustand wieder her.

**Comment by skvarel** [comment]
Ganz wichtig, es wird nicht zerstört oder gelöscht. Es sind immer noch ALLE Widgets da!

Hier bitte einmal, NACHEINANDER, die Widgets selektieren und wieder deselektieren.

Wichtig hierbei, es wirklich einzeln und eins nach dem anderen zu klicken. 'Alle selektieren' bringt da nicht.

![grafik](https://user-images.githubusercontent.com/1114419/102234798-f0a02680-3ef1-11eb-9782-3f0de01b5840.png)

Der Workflow sollte helfen und muss auch nur einmal gemacht werden.

Gruß, Sven.

**Comment by ITCrowdIOB** [comment]
Hallo Sven.

 

Danke für den Tipp aber bei der Masse an von mir verwendeten inventwo Widgets, ist mir das zu zeitaufwändig. Select und deselect dauert ca. 10 Sek. Pro Widget.

Ich warte auf einen Patch der es richtet oder ich mache die Views neu. Geht wahrscheinlich schneller.

 

Gruß Friedrich

 

P.S.  Schickes Design, die halbtransparenten Widgets über dem Hintergrund.

 

 

 

 

 

 

 

Von: skvarel <notifications@github.com> 
Gesendet: Dienstag, 15. Dezember 2020 16:27
An: inventwo/ioBroker.vis-inventwo <ioBroker.vis-inventwo@noreply.github.com>
Cc: ITCrowdIOB <reg2@team-eul.de>; Author <author@noreply.github.com>
Betreff: Re: [inventwo/ioBroker.vis-inventwo] Versionen größer 2.5.8 zerstören vorhandene Views (#114)

 

Ganz wichtig, es wird nicht zerstört oder gelöscht. Es sind immer noch ALLE Widgets da!

Hier bitte einmal, NACHEINANDER, die Widgets selektieren und wieder deselektieren.

Wichtig hierbei, es wirklich einzeln und eins nach dem anderen zu klicken. 'Alle selektieren' bringt da nicht.

 <https://user-images.githubusercontent.com/1114419/102234798-f0a02680-3ef1-11eb-9782-3f0de01b5840.png> 

Der Workflow sollte helfen und muss auch nur einmal gemacht werden.

Gruß, Sven.

**Comment by jkvarel** [comment]
@ITCrowdIOB ein Patch um das Problem zu beheben wird es leider nicht geben. Es gab eine Änderung im Code, die zur Inkompatibilität führt und erst beim einzeln anklicken der Widgets werden diese neu geladen. 
Es gibt also nur die Möglichkeit, die @skvarel genannt hat um die View wieder herzustellen.

Oder Views neu machen. Ist zwar ein großer Zeitaufwand ich weiß aber wenn du dann gleich die neuen Universal- und Multi-Widgets nutzt kannst du dich auf neue Funktionen freuen. Die Widgets lassen sich individueller anpassen.

**Comment by jkvarel** [comment]
da leider kein Fix möglich ist schließe ich dieses Isssue. Wenn weitere Probleme bestehen, gerne ein neues Issue aufmachen
