### ISSUE TITLE
Slider iChangeOnRelease und IncreaseDecreaseValue funktionieren nicht

### ISSUE THREAD

**Issue by Kespri** [inventwo/ioBroker.vis-inventwo#118]
Ich wünsche allen eine tolle Weihnachtszeit und frohe Festtage, so wie ein guter Rutsch ins neue Jahr!

Ich habe es auf Chrome via Webbrowser und über Android FullyKiosk getestet (inkl. Cache geleert), leider hat der iChangeOnRelease keinen Einfluss. Das Licht dimmt sich schon während der Betätigung des Reglers und nicht erst nach dem loslassen. Daher spielt es zur Zeit keine Rolle, ob der Hacken gesetzt ist oder nicht.

IncreaseDecrease:
Wenn man den Widget Typ auswählen möchte bleiben die Einstellmöglichkeiten des vorher gewählten Types bestehen, daher weiss ich nicht was man wo Eintragen sollte oder könnte. Je nachdem was vorher war, wie zB Typ State, hat man zwei Werte Typen wie Wahr und Falsch oder bei vorher Eingestellten Typ Background hat man nur noch eine Werte Typ Wahr.
Ich habe diverse Werte probiert mit und ohne Plus und Minus Zeichen, die gehen aber nicht. Der Widget Typ scheint noch buggy zu sein.

**Comment by jkvarel** [comment]
@Kespri dann ist beim Update wohl was schiefgegangen. Mach mal bitte ein downgrade und lad das Update nochmal neu.

**Comment by Kespri** [comment]
Danke für den Tipp, ein downgrade und ein erneutes install hat geholfen, beide Widgets funktionieren somit bei mir. Das Ticket kann somit geschlossen werden.

**Comment by jkvarel** [comment]
Super das es funktioniert hat
