### ISSUE TITLE
Slider: Wertanzeige, wenn "nach loslassen..." aktiviert (v2.6.0)

### ISSUE THREAD

**Issue by izmiruebel0** [inventwo/ioBroker.vis-inventwo#126]
Hallo,
ich habe gerade die in der 2.6.0 neue Funktion "Wert erst beim loslassen setzen" ausprobiert. Wirklich eine tolle Sache für die Rolladensteuerung, da ohne diese Funktion der Rolladen oft unkontrolliert rumfährt, bis man den richtigen Wert eingestellt hat.
Was mir jetzt aber noch zu meinem Glück fehlt: der nach Aktivieren von "Zeige Wert" angezeigte Wert, wird ebenfalls erst nach loslassen aktualisiert, für die genaue Einstellung des Sliders auf den gewünschten Sollwert, müsste der Wert aber sofort aktualisiert werden, wenn man den Slider bewegt. Wäre so etwas möglich?

**Comment by jkvarel** [comment]
@izmiruebel0 ja das ist möglich und ergibt auch vollkommen Sinn. Ich werde das noch umsetzen

**Comment by izmiruebel0** [comment]
Super, vielen Dank. 
Dann bin ich gleich mal so unverschämt und aüßere gleich noch mal einen Wunsch. Ist es auch möglich den Wert wahlweise an einer anderen Stelle anzuzeigen (idealerweise mit einstellbarem Suffix)? Für meine Rolladensteuerung habe ich den Wert rechts neben dem Silder plaziert:
![Aufnahme1](https://user-images.githubusercontent.com/76837142/103454706-f31ec080-4ce6-11eb-8fb1-869d6e8ec9c8.jpg)
Standardmäßig ist er ja darunter, das würde aber irgendwie gar nicht zum Layout passen. Momentan kann ich ja noch den mit dem Slider verknüpften Wert (statt des "Zeige Wert"-Werts) dort manuell hinsetzen. Wenn aber dann der Sliderwert (vor loslassen) dort stehen soll, funktioniert diese Vorgehensweise ja nicht mehr, weil der Wert vermutlich nur Widget-intern verfügbar sein wird.

Bei dieser Gelegenheit noch mal herzlichden Dank für die sehr gut gemachten Widgets. Man merkt hier, dass sich jemand echt Gedanken gemacht hat. Bei anderen Widgets passt immer irgendeine Kleinigkeit nicht, oder sie sehen in der Runtime anders aus als im Editor, oder sie sind zu wenig konfigurierbar. Hier habe ich wohl nach langen rumprobieren endlich ein Widget-Set gefunden, mit dem ich gut arbeiten kann.

Eine (Off-Topic) Frage noch zu dem Stop-Button aus oben gezeigter Rolladensteuerung. Hiermit setze ich ein Bit auf true (momentan mit einem 1-fachen Radiobutton), mit dem der fahrende Rolladen gestoppt wird. Dieses Bit bleibt leider noch einige Zeit auf true stehen, sodass ich die Rückmeldung über die Buttonfarbe durch Setzen von 2 gleichen Button-Farben deaktiveren musste, damit die Stop-Taste nicht im aktivierten Zustand hängen bleibt (obwohl sich ein neuer Stop trotzdem auslösen lässt). Dadurch fehlt jetzt aber leider jegliche Rückmeldung, dass die Taste überhaupt gedrückt wurde. Hast du da irgendeinen Vorschlag, was ich das noch anders machen könnte, bzw. ob sich das mit einem anderen Button-Typ evtl. besser umsetzen lässt?

**Comment by jkvarel** [comment]
@izmiruebel0
Zu dem Stop Button: Wenn ich dich richtig verstehe würde sich hier ein State Button anbieten. Den kannst du beim Universal- oder Multi-Widget unter Widget Typ auswählen. Dort gibt es die Möglichkeit eine Rückmeldedauer und eine Verweildauer anzugeben. 
Erstmal zum State: Das Widget setzt beim klicken immer wieder den gleichen Wert.
Rückmeldedauer: Zeigt das Widget solange als "Zustand true" an, wie eingestellt.
Verweildauer: Setzt den Wert für die angegebene Zeit und trägt danach dann den alten Wert wieder in den Datenpunkt. (Z.b. wenn der Dp vorher  false war wird der beim Klick auf true gesetzt und nach z.B. 2 Sekunden wieder auf false)

Zu deinem Wunsch: Ja ist machbar. Ist nur nicht so schnell gemacht, dass ich es heute noch mit in das Update bekomme. Aber werde ich noch umsetzen ;)

**Comment by izmiruebel0** [comment]
Danke für die schnelle Info und vielen Dank für die Übernahme der Wert-Positionierung in deine todo Liste.

Den State Button hatte ich offenbar missverstanden. "State" hatte ich nämlich als Statusrückmeldung interpretiert und nicht als Taster. Ja, der State Button macht genau das, was ich haben wollte. Einfach perfekt. Wie ich schon oben sagte, da hat sich jemand wirlklich Gedanken gemacht. 
Was ich allerdings hier nicht verstanden habe, ist der Vergleichsoperator. Wenn der State Button doch keine wirklichen Rückmeldungen verarbeitet, was wird denn hier verglichen?

**Comment by izmiruebel0** [comment]
Ach so, eine Sache habe ich noch vergessen in Verbindung mit dem State Button:
Wie würde man das machen, wenn man z.B. einen Stromstoßschalter damit ansteuern würde und eine Rückmeldung, ob das Licht brennt oder nicht direkt auf dem Button haben möchte. Das würde ja doch nur gehen, wenn es eine Rückmeldung gäbe (die zu allem Überfluss sogar noch von einem anderen Signal herrührt).

**Comment by izmiruebel0** [comment]
Und noch mal ine Sache mit dem Slider. Ich steuere teilweise auch mehrere Rolläden über eine virtuelle Gruppe, indem ich die Zielposition über den Slider für die gesamte Gruppe setze. Dieser Zielpositionswert wird automatisch mit der Ist-Position überschrieben, nachdem die Rollädenostions verändert wurde. Dabei kann es auch vorkommen, dass nicht alle auf der gleichen Position stehen (z.B. wenn ein Rolladen einzeln gefahren wurde). Dann steht aber in der mit der Gruppe verknüpften Variable für den Zielwert ein unbestimmter Wert ("uncertain"). Prinzipiell wäre das nicht weiter schlimm, aber in diesem Zustand lässt sich der Slider nicht mehr bewegen bzw. bedienen, da er ja auch mit dem "uncertain"-Wert gefüttert wird. Warum ist das so? Ich könnte idealerweise doch jetzt einfach mit dem Slider wieder einen gültigen Wert zwischen 0 und 100 einstellen und die Gruppe würde diesen Zielwert dann anfahren, unabhängig davon was vorher als Zielwert drin stand.

**Comment by jkvarel** [comment]
zu dem State Button: Ich weiß nicht ob ich dich richtig verstehe aber mit dem Multi-Widget kannst du unabhängig vom senden des Werts einen Status anzeigen.

zu dem Slider: Ja muss ich gucke ob das geht, da ich mir jetzt für den Slider den aktuellen Wert aus dem Dp ziehe

**Comment by jkvarel** [comment]
Jetzt wird beim Slider immer der aktuelle Wert vom Slider beim schieben angezeigt (v2.7.2 latest)

Das mit dem wenn der Wert z.B. uncertain oder etwas anders ist muss ich mir noch angucken

**Comment by izmiruebel0** [comment]
> zu dem State Button: Ich weiß nicht ob ich dich richtig verstehe aber mit dem Multi-Widget kannst du unabhängig vom senden des Werts einen Status anzeigen.
Ah, ok. danke. Jetzt hab ich auch die Funktion des Multi-Widgets verstanden. ich wusste vorher nicht, für was das gut ist (hatte mich aber auch noch nicht großartig damit befasst).

Den Vergleichsoperator habe ich allerdings immer noch nicht verstanden.

Slider-Wertanzeige funktioniert prima. Vielen Dank.
Ich muss allerdings erst noch mal auf die Verwendung der Wertanzeige verzichten, da sie ja wie bereits erwähnt momentan noch nicht in mein Layout passt.

**Comment by jkvarel** [comment]
Der Vergleichsoperator ist nur wichtig für die Statusanzeige des Widgets. Zum Beispiel wenn du "kleiner" Auswählst dann trifft der Zustand zu wennn  der Wert im Dp zum Beispiel kleiner als 10 ist. 10 ist dabei der Wert, den du im Feld "Wert" einträgst

**Comment by jkvarel** [comment]
Das Problem mit "uncertain" ist behoben. Sollten mal nicht zulässige Werte im Datenpunkt landen, lässt sich der Slider jetzt trotzdem nutzen. 

Hab noch paar andere Dinge zu tun. Das Update kommt spätestens Sonntag :)

**Comment by izmiruebel0** [comment]
Prima, danke. Das werd ich dann am Sonntag Nachmittag gleich mal austesten.

Noch mal zum Vergleichsoperator. Beim (Single) State Button macht das dann aber nicht wirklich einen Sinn, oder?
Oder hast du ein Beispiel parat, wo es doch einen Sinn macht?

**Comment by izmiruebel0** [comment]
Habs gerade ausprobiert. Funktioniert prima. Wenn der Wert undefiniert ist, springt der (horizontale) Slider ganz nach links und es wird "uncertain" angezeigt, wenn man die Wertanzeige nutzt. Momentan kann ich die Wertanzeige noch nicht nutzen kann, weil sie ja noch am falschen Platz ist. Wenn sich die Position aber irgendwann mal einstellen lassen wird, kommt ein neues Problem: der "uncertain" String ist zu lang für den von mir vorgesehenen Platz für die Wertanzeige. Momentan habe ich das Poblem ja auch mit der selbstgebastelten Wertanzeige, dort blende ich die Wertanzeige aber aus, wenn "uncertain" drin steht. Alternativ könnte ich aber auch z.B. "? %" dort einblenden. Idealerweise gäbe es also beim Slider eine Möglichkeit, statt uncertain etwas anderes anzuzeigen.

**Comment by jkvarel** [comment]
Super das es soweit klappt. Ich werde das Issue hier erstmal schließen, da das eigentliche Problem behoben ist. 

Kannst du bitte für die Sache mit der Positionierung des Wertes ein neues Issue mit dem Label "Enhancement" aufmachen? Das geht hier sonst nur unter.
