### ISSUE TITLE
Signalbilder nur noch schwarz/weiss

### ISSUE THREAD

**Issue by beef76** [inventwo/ioBroker.vis-inventwo#135]
Hi inventwo guys :-)
Seit irgendeiner, der letzten Versionen, werden Signalbilder in den widgets nur noch schwarz weiss bzw. in Graustufen angezeigt.
Ist euch das Problem bereits bekannt?

Hier ein Beispiel Bild

![image](https://user-images.githubusercontent.com/59502459/104331155-0dc71580-54ef-11eb-8582-10de5f20e0f8.png)

Die Bilddateien dahinter sind jedoch farbig

![image](https://user-images.githubusercontent.com/59502459/104331452-5ed70980-54ef-11eb-8f35-9fd4ac084954.png)

**Comment by beef76** [comment]
Hey ihr zwei habt ihr schon mal gucken können? 😉

**Comment by jkvarel** [comment]
Fehler hab ich gefunden und konnte ich beheben. Ist mit dem nächsten Update behoben. Kommt spätestens diesen Sonntag

**Comment by jkvarel** [comment]
Mit der Version 2.7.5 sollte es behoben sein. Bitte einmal testen und mir bescheid geben, ob es der Fall ist

**Comment by beef76** [comment]
werde ich sobald sie zur Verfügung steht, oder ist sie aktuell nur per GIT zu installieren? im IOB wird sie noch nicht gelistet (latest)

**Comment by beef76** [comment]
Hi Jannis, hi Sven, leider besteht der Fehler auch nach dem Update von 2.7.5
Alles neu gestartet, hab auch noch mal ein Signalbild gelöscht und neu eingestellt, sind immer noch schwarz/weiss bzw. in Graustufen :-( Sonst sind auch alle Adapter up to date (latest)

**Comment by beef76** [comment]
ich werde meine Signal-Bilder jetzt anders abbilden, kann daher geschlossen werden.

**Comment by beef76** [comment]
Hab herausgefunden, dass Signalbilder dann in der Farbe verändert werden, wenn Werte unter Farbe falsch und Farbe wahr eingestellt werden. Lässt man die Felder frei, werden die Signalbilder korrekt angezeigt.
![image](https://user-images.githubusercontent.com/59502459/106577982-50ed3500-653f-11eb-8d1f-02c42be190f9.png)
Leider würde ich beides gern nutzen :-)

**Comment by jkvarel** [comment]
@beef76 ,

@skvarel hat es bei  sich ausprobiert  und da geht es.  Hast du den Cache geleert? Vielleicht ist beim Updaten  etwas  schiefgegangen. Hast du schon ein down- und upgrade  des  Adapters  versucht?

**Comment by beef76** [comment]
Hi Jannis @jkvarel 
Ich denke ich hab alles gemacht was man machen kann, mehrfach iobroker neu gestartet (nicht nur deshalb) und diverse Browser probiert, Cache geleert, neue widgets angelegt und getestet, leider bleibt der Fehler bestehen, so lang man eine Farbe bei falsch oder wahr definiert. wenn man ihn zb. auf #ffffff setzt, werden die Signalbilder in graustufen dargestellt, setzt man irgendeine Farbe, werden auch die Farben der Signalbilder verfälscht.
VG Björn

**Comment by jkvarel** [comment]
Hast du auch schon ein Adapter down- und upgrade versucht? Vielleicht wurde beim Updaten etwas verschluckt

**Comment by beef76** [comment]
krasse endschei..... :-)
Ich hatte von 2.7.4 auf 2.7.5 aktualisiert und wie gesagt immer noch das Problem gehabt.
Jetzt noch mal runter auf 2.7.4 und erneut auf 2.7.5 und die scheixxxx geht??!!! :-) Danke dir!!
