### ISSUE TITLE
Universal / Multi Button

### ISSUE THREAD

**Issue by Obelix411** [inventwo/ioBroker.vis-inventwo#136]
Guten Tag 
Gibt es eine Anleitung wie ich die Werte anzeigen lassen kann beim backround ich möchte z.b CPU Werte Temperatur usw vom raspberry Anzeigen leider komme ich nicht weiter und bräuchte einen kleinen Gedanken anstoß

**Comment by skvarel** [comment]
Hallo.

Das funktioniert über das Binding.

Due trägst Deinen gewünschten Datenpunkt mit geschweiften Klammern in das Beschriftungsfeld ein.

Beispiel für eine Temperatur:

{0_userdata.0.Heizung.inventwo_Raumtemperatur_Tür}

Im Widget wird dann der Inhalt des Datenpunktes angezeigt. Es lassen sich auch mehrer Datenpunkte eintragen. HTML Tags sind auch möglich So wie auf dem Screenshots.

![grafik](https://user-images.githubusercontent.com/1114419/104843494-3f632680-58cb-11eb-942b-486ae12cd89d.png)

![grafik](https://user-images.githubusercontent.com/1114419/104843529-691c4d80-58cb-11eb-85a4-fab3d37ea9e3.png)

**Comment by Obelix411** [comment]
Bei mehreren werten dann auch immer <br> davor und <hr> dahinter ?

**Comment by Obelix411** [comment]
Ok danke hast du zufällig einen link zur Bedeutung der Sachen in den <> stehen finde es interessant mit den Linien und so

**Comment by skvarel** [comment]
Ich nutze hauptsächlich folgendes

<br> neue Zeile
<hr> Linie
<b> Fettdruck
<i> Schrägschrift
<iframe> eingebettete Seite

Hier mal eine Übersicht, was so geht:

https://www.mediaevent.de/html/html5-tags.html

**Comment by Obelix411** [comment]
Vielen Dank damit hast du meine Fragen beantworten die ich derzeit hatte kann geschlossen werden
