### ISSUE TITLE
Bilder in Widgets

### ISSUE THREAD

**Issue by Obelix411** [inventwo/ioBroker.vis-inventwo#139]
Guten Abend 
Mir ist aufgefallen das wenn ich kein Bild wähle in einem Widget das dann in der Visualisierungen ein kleines weißes Quadrat angezeigt wird im Moment bekomme ich das nur weg wenn ich ein Bild wähle und dann die Größe auf 0 stelle ich nutze ein firetab mit fully Kiosk

**Comment by jkvarel** [comment]
Bei welchem Widget ist das der Fall? Bei einem Universal/Multi-Widget?

**Comment by Obelix411** [comment]
Beim Universal auf jeden Fall das nutze ich auch ohne Bilder

**Comment by jkvarel** [comment]
Auf welchen Geräten mit welchem Browser?

**Comment by Obelix411** [comment]
Wie oben geschrieben fully Kiosk auf Amazon Fire tab 7

**Comment by jkvarel** [comment]
Kannst du ein Widget, bei dem der Fehler auftritt, exportieren und mir bitte schicken?

**Comment by Obelix411** [comment]
Ja werde ich morgen machen das seltsame ist wenn ich die Visualisierungen am pc öffne tritt der Fehler nicht auf werde es auch noch mal an anderen Geräten versuchen

**Comment by jkvarel** [comment]
Kannst du auch ein Bild machen, wo das Quadrat zu sehen ist? Ich hab so keine Ahnung wo das herkommen kann. Vor allem, wenn das nicht überall auftritt. Ein Bild könnte vielleicht auch noch helfen

**Comment by Obelix411** [comment]
[{"tpl":"i-vis-universal","data":{"g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","iUniversalWidgetType":"Switch","iValueType":"boolean","iValueComparison":"equal","iStateResponseTime":"0","iStateResetValueTime":"0","iNavWait":"100","iButtonCol":"#333333","iButtonActive":"#455618","iButtonColHover":"","iOpacityBack":"1","iCornerRadiusUL":"12","iCornerRadiusUR":"0","iCornerRadiusLR":"12","iCornerRadiusLL":"0","iContentFlexDirection":"vertical","iContentVertAlign":"iSpace-between","iContentOrder":"orderTextImg","iOpacityCtn":"1","iTextColor":"#ffffff","iTextSize":"12","iTextAlign":"iStart","iTextSpaceTop":"0","iTextSpaceBottom":"0","iTextSpaceLeft":"0","iTextSpaceRight":"0","iIconSize":"0","iImgAlign":"iEnd","iImgSpaceTop":"0","iImgSpaceBottom":"0","iImgSpaceLeft":"0","iImgSpaceRight":"0","iImgRotation":"0","iImgBlinkFalse":"0","iImgBlinkTrue":"0","iImgColorFalse":"","iImgColorTrue":"","iShadowXOffset":"2","iShadowYOffset":"2","iShadowBlur":"2","iShadowSpread":"1","iShadowColor":"#111111","iShadowColorActive":"#111111","iShadowColorHover":"","iShadowInnerXOffset":"0","iShadowInnerYOffset":"0","iShadowInnerBlur":"0","iShadowInnerSpread":"0","iShadowInnerColor":"#111111","iShadowInnerColorActive":"#111111","iShadowInnerColorHover":"","iBorderSize":"0","iBorderStyle":"none","iBorderColor":"#ffffff","iBorderColorActive":"#ffffff","iBorderColorHover":"","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"iTextFalse":"Wohnzimmer<hr>Aktuell {hm-rpc.0.LTK0131636.2.ACTUAL_TEMPERATURE} °C<hr>Soll {hm-rpc.0.LTK0131636.2.SET_TEMPERATURE} °C<hr>Ventil {hm-rpc.0.MEQ0527432.4.VALVE_STATE} %<hr>","iImageFalse":"","iImageTrue":""},"style":{"left":"6px","top":"11px","width":"176px","height":"136px","z-index":"0"},"widgetSet":"vis-inventwo"}]

**Comment by Obelix411** [comment]
Hier noch mal ein vergleichsbild oben Laptop Monitor unten firetab

**Comment by Obelix411** [comment]
![IMG_2735](https://user-images.githubusercontent.com/69235992/105520315-d882aa80-5cda-11eb-81cd-17dac7163b9a.jpg)
Oben Laptop Monitor unten Fire Tab

**Comment by Obelix411** [comment]
Lässt sich beheben wenn ich ein Bild wähle und die Größe auf 0 stelle dann ist nix zu sehen

**Comment by Obelix411** [comment]
Das weiße Quadrat wandert auch immer auf die Position die fürs Bild gewählt wurde

**Comment by jkvarel** [comment]
@Obelix411 ich habe etwas am Widget geändert, sodass das Quadrat weg sein sollte. Ich kanns leider nicht bei mir testen, da es vorher in keinem  Browser zu sehen war. Daher bitte ich dich mit dem nächstem Update mit Bescheid zu geben, ob das Quadrat noch da ist oder weg ist.

**Comment by jkvarel** [comment]
@Obelix411 ist der Fehler behoben?

**Comment by jkvarel** [comment]
Da keine Rückmeldung kam gehe ich erstmal davon aus, dass der Fehler behoben ist. Sollte das doch nicht der Fall sein melde dich gerne

**Comment by Obelix411** [comment]
Sorry hatte vergessen mich zu melden ja der Fehler ist behoben vielen Dank
