### ISSUE TITLE
Touch Steuerung

### ISSUE THREAD

**Issue by xlklwr** [inventwo/ioBroker.vis-inventwo#141]
Ich habe mir ein erstes Vis mit euren Buttons gebaut. Während die Steuerung über den PC und Maus funktioniert, zeigen die Buttons keine Reaktion an Android-Geräten. Weder am Handy noch auf 2 verschiedenen Tablets und verschiedenen Browsern sind die Buttons bedienbar. Füge ich einen Button aus einem anderen Plugin hinzu kann ich schalten und dann ändert sich auch die Farbe des inventwo Buttons.

**Comment by jkvarel** [comment]
Schaltet sich denn der Datenpunkt wenn du auf unser Widget klickst und nur die Farbe ändert sich nicht oder funktioniert nicht mal das?

**Comment by Kespri** [comment]
Dieses Problem habe ich auch festgestellt im Browser auf dem PC, sowie auf dem Tablet in WallPanel und Fully Kiosk. Der Datenpunkt wird geschaltet, somit kann man die Geräte steuern, aber irgendwie kommt kein Feedback mehr zurück zur Visualisierung. Man muss die Visualisierung erst wieder manuell aktualisieren, dann wird die Änderung angezeigt. Nach der Aktualisierung funktioniert es wieder für kurze Zeit, dann werden die Änderungen wieder nicht angezeigt.
Es scheint aber nicht nur eure Widget zu betreffen, den auch einfache Ausgaben von  Zahlenfelder, welche z.B. die Temperatur ausgeben, werden nicht mehr aktualisiert. Scheint als würde die Kommunikation zwischen ioBroker und Visualisierung gestört werden, aber nicht komplett - seltsam.

Wenn ich meine erste Visualisierung aufrufe, welche keine Inventwo Widgets benutzt, passiert dies nicht, alles schaltet und gibt das Feedback korrekt wieder. Werde mal die alte Visualisierung aktiv lassen, um zu sehen, ob der Fehler vielleicht doch noch auftaucht.
Aber vielleicht hilft das Feedback schon mal und ihr findet einen Fehler, der die Kommunikation stört oder so.

**Comment by jkvarel** [comment]
@xlklwr @Kespri welche Adapterversion nutzt ihr? Könnt ihr mir mal ein Widget schicken, damit ich mir die Einstellungen angucken kann

**Comment by Kespri** [comment]
@jkvarel seit dem Fehler habe ich inventwo nochmal aktuallisiert, da aber das Tablet in der Ferienwohnung steht, kann ich es erst wieder ende März testen, ob das Problem noch besteht oder nicht.

**Comment by Kespri** [comment]
@jkvarel das Problem ist bei mir bis jetzt nicht mehr aufgetreten. Aus meiner Sicht, kannst diesen Issue gerne schliessen, wenn von @xlklwr nichts mehr zu hören ist.

Danke für Eure unermüdliche Arbeit ;-)
