### ISSUE TITLE
Slider - Wert erst beim loslassen

### ISSUE THREAD

**Issue by Kespri** [inventwo/ioBroker.vis-inventwo#145]
Nachdem ich das Update machte, haben meine Slider den Wert nicht mehr übergeben, aber nur solange der Hacken bei "Wert erst beim loslassen setzen" aktiv war. Wenn man den Hacken entfernt, schaltet der Datenpunkt auch sofort wieder.

(Wenn die Kommunikation nicht gerade gestört ist - Beschreibung des Problem  im Issues: Touch Steuerung näher beschrieben)
Der Slider zeigt den Wert des Datenpunkt korrekt an, wenn man den Wert wo anders ändert. Man kann einfach nur den Wert nicht über den Slider ändern, wenn der Hacken gesetzt ist.

**Comment by jkvarel** [comment]
Fehler gefunden. Ist mit dem nächstem Update behoben

**Comment by Kespri** [comment]
Nach dem Update heute, funktioniert es wieder - Danke.
