### ISSUE TITLE
unterschiedliche Schrift / Ausrichtung der MultiSwitch unter Chrome&Edge vs. Safari&FireFox

### ISSUE THREAD

**Issue by UlliMUC** [inventwo/ioBroker.vis-inventwo#150]
Hi,

ich habe mir Buttons gebaut, wo jedoch unter Chrome&Edge vs. Safari&FireFox die Schrift variiert:
Chrome&Edge
![image](https://user-images.githubusercontent.com/78802971/107375731-5ae7d880-6ae9-11eb-8ddf-01e1082129e9.png)
Safari&FireFox
![image](https://user-images.githubusercontent.com/78802971/107375810-6dfaa880-6ae9-11eb-8941-9616cf212ec8.png)

Zoom ist jeweils auf 100% - das ändert jedoch prinzipiell nichts an dem Verhalten.

**Comment by Lucifor1976** [comment]
Ich hänge mich hier an, seit dem letzten Update ist alles gezogen.

Ansicht Firefox: 
![Bildschirmfoto 2021-02-13 um 09 45 15](https://user-images.githubusercontent.com/67290625/107845989-69cbd500-6de0-11eb-8efd-a6595fef0522.png)

Ansicht Safari:
![Bildschirmfoto 2021-02-13 um 09 45 02](https://user-images.githubusercontent.com/67290625/107845999-7e0fd200-6de0-11eb-88a0-98cd12850002.png)


Ansicht Firefox:
![Bildschirmfoto 2021-02-13 um 09 44 35](https://user-images.githubusercontent.com/67290625/107846008-8d8f1b00-6de0-11eb-97cd-29e9c66fc74e.png)

Ansicht Safari:
![Bildschirmfoto 2021-02-13 um 09 44 18](https://user-images.githubusercontent.com/67290625/107846012-954ebf80-6de0-11eb-85c0-30e1cd4323c6.png)

Das zieht sich durch die komplette VIS!

**Comment by jkvarel** [comment]
@Lucifor1976 den Fehler konnte ich finden und ist mit dem nächstem Update behoben.

@UlliMUC ich schau mal woran es liegt. Konnte so noch nicht feststellen woran es liegt. Bei uns sieht es in Firefox, Chrome und Safaria gleich aus. Kannst du mir mal ein Widget schicken, damit ich mir die Einstellungen davon mal angucken kann?

**Comment by Lucifor1976** [comment]
Danke :) Ich ändere mal noch nichts. Ich nutze den Safari permanent für die Vis auf dem Mac auf einem eigenen Bildschirm, es ist mir daher sehr wichtig das das korrekt aussieht. :)

**Comment by Lucifor1976** [comment]
Najaaaaaaaaaa... Das ist jetzt nicht wirklich besser :/

**Comment by Lucifor1976** [comment]
![Bildschirmfoto 2021-02-15 um 19 47 17](https://user-images.githubusercontent.com/67290625/108017739-f14e5980-7015-11eb-8a0e-a3ca1b3d0a05.png)

**Comment by Lucifor1976** [comment]
Da habt Ihr ordnetlich was fehl entwickelt. Die Lampen und Schalter aktualisieren auch nicht mehr richtig.. Die States werden nicht geändert. Funktion ist gegeben, aber am Widget tut sich nix.

**Comment by jkvarel** [comment]
@Lucifor1976 das Hintergrundbild ist ein Image-Widget? Das hat ein paar neue Funktionen bekommen.  Die Bilder gehen jetzt nicht mehr über den Rand des Widgets hinaus. Könnte es sein, dass das Widget so klein ist? Ansonsten kannst du die Art der Skalierung auf "Füllen" stellen
![image](https://user-images.githubusercontent.com/35769746/108214891-fe13a000-7130-11eb-8619-6f4c2852abdf.png)

Kannst du mir eines der Widgets schicken? Ich kann den Fehler bei mir so nicht reproduzieren

**Comment by jkvarel** [comment]
Bestehen die Fehler noch oder sind die bei euch behoben?

**Comment by jkvarel** [comment]
Da keine Rückmeldung kam gehe ich erstmal davon aus, dass der Fehler behoben ist. Sollte das nicht der Fall sein meldet euch gerne
