### ISSUE TITLE
Switch bei Typ Wert übernimmt erst beim 2. Druck

### ISSUE THREAD

**Issue by UlliMUC** [inventwo/ioBroker.vis-inventwo#151]
Hi,

mir ist aufgefallen, dass bei einem Switch und dem Typ Wert, erst beim 2. Betätigen der Wert geschrieben wird. Bei einem normalen jqui Button funktioniert es problemlos.

![image](https://user-images.githubusercontent.com/78802971/107482182-9d5bf480-6b7f-11eb-8348-ff25c67f759e.png)
![image](https://user-images.githubusercontent.com/78802971/107482235-b06ec480-6b7f-11eb-8d08-b123d101bd8b.png)

**Comment by tomg1970** [comment]
Yes i have this problem too

**Comment by jkvarel** [comment]
@UlliMUC @tomg1970 
Ist das bei allen Browsern und Geräten der Fall? Ich konnte es bei mir nicht reproduzieren.

**Comment by tomg1970** [comment]
Ja .... sogar mit der iOS App IoBroker

**Comment by jkvarel** [comment]
@tomg1970 , tut mir leid. Ich wollte den Kommentar nicht löschen. Hab mich verklickt. Ich schaue mal ob ich das Problem finden kann

**Comment by tomg1970** [comment]
Kein Problem, sagte ja nur das es bei allen Browsern so ist und da ich die iOS App IOBROKER nutze und es da zeitweise auch vorkommt.

**Comment by jkvarel** [comment]
@UlliMUC  @tomg1970 besteht das Problem noch oder ist es behoben. Ich konnte das so nicht reproduzieren. Vielleicht wurde es durch andere Fehlerbehebungen mit behoben

**Comment by jkvarel** [comment]
Da keine Rückmeldung kam gehe ich erstmal davon aus, dass das Problem behoben ist. Sollte es dennoch wieder auftreten, gebt bitte bescheid
