### ISSUE TITLE
Optionales Unterscheiden zwischen angezeigtem und verändertem Datenpunkt

### ISSUE THREAD

**Issue by n3ucr0n** [inventwo/ioBroker.vis-inventwo#152]
Ich nutze Schalter von Fibaro (Walli) welche über Z-Wave eingebunden werden.

Diese kann ich zum einen manuell am Schalter und natürlich über die Datenpunkte im ioBroker steuern.

Die Datenstrucktur im ioBroker ist bei diesen Geräten so, dass ein Datenpunkt zu Steuern des Lichts ist und ein anderer Datenpunkt den aktuellen Status anzeigt.
Schalte ich also über den Steuerdatenpunkt das Licht auf True ändert sich der Statusdatenpunkt ebenfalls auf True.
Schalte ich allerdings über den Lichtschalter das Licht an, bleibt der Steuerdatenpunkt unverändert und des änder sich lediglich der Statusdatenpunkt.

So kommt es zu dem Status, dass der Steuerdatenpunkt auf "True" aber der Statusdatenpunkt auf "False" steht.
Das führt dann zu einer fehlerhaften Darstellung in der VIS.

Meine Wunsch wäre es, dass man optional (durch eine Checkbox aktivierbar) einen anderen Datenpunkt anzeigen lassen kann als der, der gesteuert wird.
So könnte ich den Statusdatenpunkt für die Anzeige und den Steuerdatenpunkt für das Setzen von Werten nutzen.

Aktuell löse ich das Problem, indem ich über Euer Widget den Statusdatenpunkt auslese und ein durchsichtiges Widget drüber lege, welches dann den Steuerdatenpunkt bedient. Dies funktioniert, aber eine schöne Lösung direkt über das Widget wäre noch schöner :-)

Ich hoffe, ich habe alles verständlich erklärt.

Liebe Grüße
Micha

**Comment by UlliMUC** [comment]
@n3ucr0n Nimm doch den MultiSwitch.

Da kannst du eine ObjektID beschreiben, und eine andere dafür nutzen, wie der Switch aussehen soll.

**Comment by n3ucr0n** [comment]
@UlliMUC  Das hört sich nach einer Möglichkeit an.
Leider bin ich mit der Nutzung der MultiSwitch Widgets noch nicht so warm geworden.

Hast Du zufällig einen Screenshot für mich, wo ich was im Widget eintragen muss um diese Trennung zu haben? Ich bin dafür scheinbar zu blöd....

Danke :-)

**Comment by UlliMUC** [comment]
![image](https://user-images.githubusercontent.com/78802971/107631836-ec7c5500-6c65-11eb-9bda-1441b8cae540.png)

**Comment by jkvarel** [comment]
@n3ucr0n falls dies deine Frage beantwortet hat geb bitte Bescheid und/oder schließe dann das Issue damit die Frage abgeschlossen ist

**Comment by n3ucr0n** [comment]
@UlliMUC Danke für die Hilfe

@jkvarel Ich bin leider erst heute dazu gekommen es zu testen.

@all Es kann gut möglich sein, dass dies die Lösung ist. Das Problem liegt leider an anderer Stelle. Da der Datepunkt zum Steuern nicht aktualisiert wird, wenn der Hardwareschalter geschaltet wird, kommt es immer wieder zu fehlerhaften Darstellungen - Das muss ich erstmal in den Griff bekommen.

Vorerst können wir diesen Case schließen. Danke für die Hilfe =)
