### ISSUE TITLE
Widget "image"

### ISSUE THREAD

**Issue by Matt77CHE** [inventwo/ioBroker.vis-inventwo#153]
Wenn ich in das Widget "image" ein png oder svg Bild einer Türe (eine Linie; grün für geschlossen, rot für offen) einfüge, gibt es ein Problem:
Habe ich die Linie im Bild horizontal gezeichnet, passt alles. - Wenn ich jetzt aber die selbe linie um 90° gedreht (senkrecht) als Bild exportiere und dann in das Widget importiere, ist die Linie dann im Widget überproportional gross (grösser als wenn horizontal) und kann nicht auf die gewünschte Grösse reduziert werden....

![Bug_2](https://user-images.githubusercontent.com/73795309/107847659-b4a01980-6ded-11eb-98a0-26a090bc0ebc.jpg)

![Bug](https://user-images.githubusercontent.com/73795309/107847670-c1bd0880-6ded-11eb-8958-759dd78e73d9.jpg)

hat jemand eine Ahnung woran das liegen könnte?

Installierte Version inventtwo : 2.7.6
Iobroker alles heute auf den neuesten Stand gebracht (Bug war vor der Aktualisierung auch schon)

**Comment by jkvarel** [comment]
Hab den Fehler denke ich gefunden. Bitte versuchs mal mit dem nächstem Update und sag mit bescheid ob es klappt

**Comment by Matt77CHE** [comment]
werde ich machen...

**Comment by jkvarel** [comment]
@Matt77CHE behoben?

**Comment by Matt77CHE** [comment]
habs soeben kontrolliert - Ja; behoben!
Ganke!
