### ISSUE TITLE
Color Slider, aktualisiert sich nicht

### ISSUE THREAD

**Issue by AndiSch87** [inventwo/ioBroker.vis-inventwo#154]
Hallo, erstmal ein Lob an den Programmierer. Super Widgets.
Leider habe ich folgendes Problem:
Ich besitze eine Yeelight RGB Bulb Lampe.
Ich möchte mit dem Color Slider die Farbe steuern, dies funktioniert auch einwandfrei.
Schalte ich jedoch die RGB Lampe über ein anderes Gerät (Alexa oder über die Yeelight App), 
aktualisiert sich der Regler auf dem Slider nicht.

Im Gegensatz dazu funktioniert der Simple Slider einwandfrei.
Mit dem Simple Slider steuer ich die Helligkeit der Lampe zwischen 1 und 100%.
Dieser Wert wird auch aktualisiert wenn ich, über Alexa die Helligkeit anpasse.

Ich hoffe ihr könnt mir weiterhelfen.

**Comment by jkvarel** [comment]
@AndiSch87 tut mir leid, dass es so lange gedauert hat.
Ich konnte den Fehler beheben. Allerdings müssen die Datenpunkt bei dem Widget neu ausgewählt werden.
Der Fehler ist mit dem Update heute behoben (v2.8.1 latest)
