### ISSUE TITLE
Universal Widget als Hintergrund Aktualisieren sich nicht

### ISSUE THREAD

**Issue by Manuel35i** [inventwo/ioBroker.vis-inventwo#160]
Hallo ich verwende das Universal Widget als Hintergrund um mir den Status meiner Fenster anzeigen zu lassen.
Sprich auf oder zu.
Nun ist es so das sich das Widget erst Aktualisiert wenn ich den Browser neu Lade was denke ich so nicht sein sollte.
Oder habe ich etwas Falsch gemacht.
![neu](https://user-images.githubusercontent.com/79336301/108558941-ed168a80-72fa-11eb-8529-4d9333424862.jpg)

**Comment by jkvarel** [comment]
@Manuel35i ne sieht auf dem ersten Blick richtig aus. Welche Version hast du installiert? Kannst du das Widget exportieren und hier schicken?

**Comment by Manuel35i** [comment]
Das wäre der Widget Code:

[{"tpl":"i-vis-universal","data":{"g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","iUniversalWidgetType":"Background","iValueType":"value","iValueComparison":"equal","iStateResponseTime":"0","iStateResetValueTime":"0","iNavWait":"100","iButtonCol":"#0ac804","iButtonActive":"#f50522","iButtonColHover":"","iOpacityBack":"0.4","iCornerRadiusUL":"0","iCornerRadiusUR":"0","iCornerRadiusLR":"0","iCornerRadiusLL":"0","iContentFlexDirection":"vertical","iContentVertAlign":"iSpace-between","iContentOrder":"orderImgText","iOpacityCtn":"1","iTextColor":"#ffffff","iTextSize":"19","iTextAlign":"iCenter","iTextSpaceTop":"0","iTextSpaceBottom":"0","iTextSpaceLeft":"0","iTextSpaceRight":"0","iIconSize":"130","iImgAlign":"iCenter","iImgSpaceTop":"0","iImgSpaceBottom":"0","iImgSpaceLeft":"0","iImgSpaceRight":"0","iImgRotation":"0","iImgBlinkFalse":"0","iImgBlinkTrue":"1400","iImgColorFalse":"","iImgColorTrue":"","iShadowXOffset":"2","iShadowYOffset":"2","iShadowBlur":"2","iShadowSpread":"1","iShadowColor":"#111111","iShadowColorActive":"#111111","iShadowColorHover":"","iShadowInnerXOffset":"0","iShadowInnerYOffset":"0","iShadowInnerBlur":"0","iShadowInnerSpread":"0","iShadowInnerColor":"#111111","iShadowInnerColorActive":"#111111","iShadowInnerColorHover":"","iBorderSize":"0","iBorderStyle":"none","iBorderColor":"#ffffff","iBorderColorActive":"#ffffff","iBorderColorHover":"","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"oid":"hm-rpc.1.00109709A3BF82.1.STATE","iImageFalse":"/vis.0/main/img/Fenster geschlossen.png","iImageTrue":"/vis.0/main/img/5841034851552641733-512.png","iTextFalse":"Fenster-Büro Geschlossen","iTextTrue":"Fester-Büro Geöffnet","value":"CLOSE/OPEN","iValueTrue":"1","lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0},"style":{"left":"854px","top":"564px","width":"200px","height":"200px","z-index":"3"},"widgetSet":"vis-inventwo"}]


Version ist 2.7.10



![neu2](https://user-images.githubusercontent.com/79336301/108602728-da0bc500-73a3-11eb-8054-1390e5e042c4.jpg)

**Comment by daes10** [comment]
Ich habe genau das selbe Problem mit dem Universal Widget.
Ich lasse die Farbe meines Icons ändern beim Einschalten einer Lampe, was super klappt. Jedoch geht die Farbe nicht wieder zurück, wenn ich sie wieder ausschalte. Dazu muss auch ich den Browser neuladen, dass es klappt.

Meine Version ist: 2.7.4

**Comment by daes10** [comment]
Habe es nun anderst gelöst:

Habe ein Universal-Widget genommen...
Dort ein Bild abgefragt und halt den Text ausgeblendet, so gut wie es geht.
Beim Image Widget habe ich immernoch den selben Fehler wie @Manuel35i da es nicht aktualisiert wird oder weil ich einfach nicht nach true UND false gleichzeitig abfragen kann.

**Comment by jkvarel** [comment]
@daes10 , @Manuel35i 
Besteht das Problem noch? Ich mir das Widget importiert und konnte den Fehler nicht reproduzieren. Auch beim Image-Widget konnte ich keinen Fehler feststellen.

Beim Image-Widget ist es nicht notwendig auch auf false zu prüfen. Denn wenn der Wahr-Wert nicht zutrifft wird einfach der Falsch-Zustand angezeigt. Auch wenn da aus irgendeinem Grund etwas anders in Dp steht.

Falls das Problem noch besteht schickt mir gerne noch ein Image-Widget. Dann kann ich das mit euren Einstellungen bei mir nochmal testen.

**Comment by jkvarel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [lzhu](https://trello.com/c/Aas4H22K/1-lzhu)

**Comment by Manuel35i** [comment]
Also bei mir besteht das Problem immer noch!
Ich habe meine Visualisierung noch weiter ausgebaut und denn Fehler bei mehreren Sachen festgestellt.
Ich habe mir z.b. eine Liste mit den geöffneten Fenstern gemacht diese wird auch nur mit den ersten Fenster gefüllt, alle anderen Fenster die ich danach öffne werden erst sichtbar nach den erneuten laden des Browsers

[{"tpl":"i-vis-valuelist","data":{"g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":true,"g_css_shadow_padding":true,"g_css_border":true,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","iValueListStyle":"disc","iValueListEntryDistance":"0","iTextColor":"#000000","iTextSize":"30","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"oid":"javascript.0.zählen_Fenster.textFensteraufAnsage"},"style":{"left":"584px","top":"475px","width":"483px","height":"212px","z-index":"10"},"widgetSet":"vis-inventwo"},{"tpl":"i-vis-universal","data":{"g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":true,"g_css_shadow_padding":true,"g_css_border":true,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","iUniversalWidgetType":"Background","iValueType":"boolean","iValueComparison":"equal","iStateResponseTime":"100","iStateResetValueTime":"100","iNavWait":"100","iButtonCol":"#ffffff","iButtonActive":"#f90b06","iButtonColHover":"","iOpacityBack":"0.2","iCornerRadiusUL":"50","iCornerRadiusUR":"50","iCornerRadiusLR":"50","iCornerRadiusLL":"50","iContentFlexDirection":"vertical","iContentVertAlign":"iSpace-between","iContentOrder":"orderTextImg","iOpacityCtn":"0.8","iTextColor":"#ffffff","iTextSize":"12","iTextAlign":"iStart","iTextSpaceTop":"0","iTextSpaceBottom":"0","iTextSpaceLeft":"0","iTextSpaceRight":"0","iIconSize":"77","iImgAlign":"iCenter","iImgSpaceTop":"5","iImgSpaceBottom":"12","iImgSpaceLeft":"0","iImgSpaceRight":"0","iImgRotation":"0","iImgBlinkFalse":"0","iImgBlinkTrue":"1400","iImgColorFalse":"","iImgColorTrue":"","iShadowXOffset":"2","iShadowYOffset":"2","iShadowBlur":"2","iShadowSpread":"1","iShadowColor":"#111111","iShadowColorActive":"#111111","iShadowColorHover":"","iShadowInnerXOffset":"0","iShadowInnerYOffset":"0","iShadowInnerBlur":"20","iShadowInnerSpread":"5","iShadowInnerColor":"#111111","iShadowInnerColorActive":"#111111","iShadowInnerColorHover":"","iBorderSize":"0","iBorderStyle":"none","iBorderColor":"#ffffff","iBorderColorActive":"#ffffff","iBorderColorHover":"","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"oid":"javascript.0.scriptEnabled.Manuel_Datenpunkte.Fenster_offen","iImageTrue":"/vis.0/main/img/X icon.png","iImageFalse":"/vis.0/main/img/HackenNeu2.png","iValueTrue":"","value":""},"style":{"left":"555px","top":"455px","width":"537px","height":"250px","z-index":"3"},"widgetSet":"vis-inventwo"}]


das wäre das Widget.


![mmmmmm](https://user-images.githubusercontent.com/79336301/110244188-d3fa1480-7f5d-11eb-9a73-3a3e61fbe922.jpg)
![mmmmmmfgf](https://user-images.githubusercontent.com/79336301/110244193-d8263200-7f5d-11eb-9955-d3486e65387c.jpg)

Version hab ich die 2.8.0

**Comment by jkvarel** [comment]
Ich kann das Problem hier leider nicht reproduzieren. Funktioniert das aktualisieren der Widgets denn mit anderen Widgets? Z.B. mit den Standard-Widgets von der VIS? @skvarel sagte mir gerade, dass man die Datenpunkte von Homematic erst noch mit einem Skript auf "acknowledged" setzen muss

**Comment by Manuel35i** [comment]
Hallo,
also bei den Metro Widget funktioniert es problemlos.

Das wäre das selbe Widget nur von Metro zum vergleich:

[{"tpl":"tplMetroTileBool","data":{"oid":"hm-rpc.1.00109709ADC5A4.1.STATE","g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","hover":"true","label_false":"WC Fenster Geschlossen","label_true":"WC Fenster Offen","bg_class_false":"ribbed-emerald","bg_class_true":"ribbed-red","icon_class_false":"","icon_class_true":"","icon_badge_false":"","icon_badge_true":"","badge_bg_class_false":"","badge_bg_class_true":"","badge_top":"0","badge_left":"0","brand_bg_class_false":"","brand_bg_class_true":"","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"icon_false":"/vis.0/main/Fenster geschlossen.png","icon_true":"/vis.0/main/fenster.png","icon_width":"50","icon_height":"60","icon_top":"20","icon_left":"40","transform":"true"},"style":{"left":"40px","top":"130px","width":"200px","height":"200px","z-index":"5"},"widgetSet":"metro"}]

**Comment by jkvarel** [comment]
Ich hab mir nochmal dein Widget genommen und versucht den Fehler zu reproduzieren aber ohne Erfolg. Es klappt ohne Probleme. Klappt es vielleicht mit der aktuellen Version 2.9.5 bei dir auch? Vielleicht hat ja das beheben anderer Fehler deins auch behoben?

**Comment by Manuel35i** [comment]
Bei mir funktioniert es leider auch mit der neuesten Version immer noch nicht.
Welche Sensoren verwendest du beim Testen? 
Bei mir sind es Homematic IP Fensterkontakte vielleicht liegt es an denen?

**Comment by jkvarel** [comment]
@Manuel35i kannst du mir sagen, ob mittlerweile das Problem behoben ist? Es hat sich zur v3.x.x im Hintergrund etwas geändert, sodass die Generierung und Aktualisierung besser funktioniert

**Comment by Manuel35i** [comment]
Hallo nein Leider immer noch keine Änderung!
Nur ist mir aufgefallen wenn ich das VIS am Laptop öffne mit einen Browser Funktioniert es mittlerweile tadellos somit denke ich ist es ein Problem auf den Handy Browser

**Comment by jkvarel** [comment]
@Manuel35i 
Welchen Browser nutzt du auf dem Handy? Und welches Handy hast du?
Du nutzt die aktuellste Version des Adapters? v3.0.11?

**Comment by Manuel35i** [comment]
Ich benutze die IO Broker App hab es aber auch schon mit Chrome Probiert.
Handy ist ein Xiaomi MI 9.

**Comment by Manuel35i** [comment]
Version ist die Aktuelle.

**Comment by Manuel35i** [comment]
So ich glaube das ich das Problem jetzt gefunden habe.
Wenn man das ganze ohne Cache ladet funktioniert es einwandfrei.
Somit ist der Browser Cache schuld.

**Comment by jkvarel** [comment]
@Manuel35i 

Das ist gut möglich. Also ist das Problem an sich behoben?

**Comment by jkvarel** [comment]
Da keine Antwort mehr kam gehe ich erstmal davon aus, dass das Problem behoben ist. Falls nicht bitte melden
