### ISSUE TITLE
Analogwerte getrennt vom Text anzeigbar machen.

### ISSUE THREAD

**Issue by Elektroniker0486** [inventwo/ioBroker.vis-inventwo#163]
Es wäre cool wenn es die Möglichkeit gäbe, analoge Werte im Widget separat anzeigen und anordnen zu können.

**Comment by jkvarel** [comment]
v3.0.0: Beim Universal- und Multiwidget kann der Inhaltstyp auf HTML/Text geändert werden um anstelle des Bildes eigenen Text oder Datenpunktwerte anzuzeigen. Per Binding kann dort ein Datenpunktwert angezeigt werden.
![image](https://user-images.githubusercontent.com/35769746/122923172-b1510780-d364-11eb-817c-fe9afdfc8124.png)
