### ISSUE TITLE
Kombi Button - Navigation + State

### ISSUE THREAD

**Issue by tomg1970** [inventwo/ioBroker.vis-inventwo#165]
Hallo,
vielleicht könnte ihr einen Button Typ erstellen, wo ich den Status (on/off) eines Devices anzeigen kann und
beim Button Klick auf eine andere Seite Navigieren kann. (ohne das sich der Status on/off ändert.

**Comment by jkvarel** [comment]
Die Funktionalität kommt noch mit bei den Zuständen rein. Ich ändere das so ab, dass man beim Zustand auswählen kann, ob an auf einen Datenpunkt oder eine View prüfen möchte

**Comment by jkvarel** [comment]
@tomg1970 mit der Version 2.9.0
Um das umzusetzen kannst du dir dann ein Multi-Widget nehmen, diesen auf "Navigation" stellen und als Zustand kannst du dann auf ein Datenpunkt prüfen

**Comment by tomg1970** [comment]
Hi, sorry für die späte Antwort. Vielen lieben Dank für deine Umsetzung. Nach ein bisschen Einarbeitungszeit klappt das alles wunderbar!
