### ISSUE TITLE
View in Popup automatisch nach Inaktivität schließen

### ISSUE THREAD

**Issue by n3ucr0n** [inventwo/ioBroker.vis-inventwo#171]
Hallo,

ich stelle grade einige meiner Darstellungen auf "View in Popup" um.

Nun hätte ich es gerne, dass das Popup automatisch nach X Sekunden Inaktivität wieder schließt.

Ich habe die Einstellungsmöglichkeit "Verweildauer in Millisec." gefunden.
Leider führt dies nicht dazu, dass sich das Popup wieder schließt.

Könnt Ihr die Möglichkeit hinzufügen, das Popup automatisch nach x Sekudnen inaktivität zu schließen?
Sollte die Funktion, die ich gefunden habe, genau dafür gedacht sein: Wie konfiguriere ich sie richtig?

(nebenbei: Die Darstellung dieser Einstellung im Vis-Editor ist noch buggy - Man muss das Einstellungsfenster "Allgemein" schließen und wieder neu öffnen damit man die Einstellung sieht. Sobald man etwas verändert, verschwindet die Einstellung wieder und wird erst sichtbar, wenn man das Einstellungsfenster erneut schließt und wieder öffnet.)

**Comment by skvarel** [comment]
Hallo.

Die Einstellung 'Verweildauer' bezieht sich auf die Rückmeldung eines Nav-Widget. Ein automatisches Schließen ist noch nihct eingebaut, kommt aber auf jeden fall noch.

Gruß, skvarel.

**Comment by skvarel** [comment]
Hallo.

Die Einstellung 'verweildauer' dürfte beim PopUp und beim Nav eigentlich gar nicht da sein. Sie ist für den Tuy 'State' um eine Rückmeldung für das Drücken zu erhalten. Deswegen ist sie auch auf den ersten Blick nicht zu sehen!

Mehr Einstellungen hat das PopUp (noch) nicht:
![grafik](https://user-images.githubusercontent.com/1114419/110479857-236b4c80-80e6-11eb-9e5b-710541231528.png)

**Comment by n3ucr0n** [comment]
Alles klar. Danke für die Infos.
Die Einstellungen erscheint jedes Mal bei mir, wenn ich den Tab "Allgemein" aus und wieder einblende:

![Dashboard 1](https://user-images.githubusercontent.com/63336916/110483145-b9ed3d00-80e9-11eb-8715-d76dedfd4262.JPG)

**Comment by jkvarel** [comment]
@n3ucr0n mit der Version 2.9.0 kann das PopUp automatisch geschlossen werden
![image](https://user-images.githubusercontent.com/35769746/114162771-b4258a00-9929-11eb-98a9-3dcf5e4db3c1.png)

**Comment by n3ucr0n** [comment]
Funktioniert fürs erste super. 
Ich würde diesen Case noch einmal öffnen:

Der Wert Schließe nach X Sekunden schließt das Fenster FIX nach der eingestellten Zeit. Egal ob ich noch in dem Popup arbeite oder nicht. Klasse wäre, wenn das schließen (ggf. optional) erst nach X Sekunden Inaktivität im Widget geschlossen werden würde.

Danke für Eure Entwicklung!

**Comment by n3ucr0n** [comment]
@skvarel gibt es noch Überlegungen das automatische schließen an die letzte Interaktion zu koppeln?
