### ISSUE TITLE
Color slider mir Grauwerten

### ISSUE THREAD

**Issue by tobe2bcon** [inventwo/ioBroker.vis-inventwo#179]
Hallo,
bin begeistert von den neuen Widgets - super Arbeit! 
Ich erstelle gerade unter ioBroker ein Programm zur Steuerung eines ca. 320 x 170 cm großen LED-Panels (weltweites Unikat). Zur Einstellung der Farbmuster setze ich 60 x Color slider ein. Wie auf dem einen Bild zu sehen, sollen neben den Farben (zB #ff00ea) auch weiß (#ffffff), grau (#808080) und sogar schwarz (#000000) dargestellt werden können. (Hinweis: die "japanischen Inseln"
![IMG_1702](https://user-images.githubusercontent.com/59087087/111479720-85a0fe80-8731-11eb-9024-ccbb9960eca1.JPG)
![IMG_1703](https://user-images.githubusercontent.com/59087087/111479724-86d22b80-8731-11eb-8ebe-9fc348aafebc.JPG)

 haben mit der Funktion nichts zu tun und sind nur ein temporäres Problem (Feuchtigkeit))

Hierzu bräuchte ich entweder einen weiteren Slider, der nur Grauwerte im Bereich von weiß bis schwarz ausgibt, oder aber einen Slider, den ich per Software umschalten kann, also entweder für color oder für grau.

Diese Idee würde ggf auch allen entgegenkommen, die mit RGB-LEDs weißes Licht dimmen möchten. 

Meint ihr, das wäre machbar? 

Grüße ans Team

**Comment by jkvarel** [comment]
Welches Format brauchst du? HEX?

**Comment by tobe2bcon** [comment]
Sorry :-((, ja, HEX

**Comment by jkvarel** [comment]
Hallo, mit v3.3.0 gibt es nun einen Colorpicker. Dort lassen sich auch Grauwerte einstellen

**Comment by tobe2bcon** [comment]
Hallo Jannis,
super! Vielen Dank für eure tollen Widgets. Die Änderung schaue ich mir
bei Gelegenheit an.
Alles Gute weiterhin
Am Montag, dem 07.03.2022 um 19:47 +0000 schrieb Jannis:
