### ISSUE TITLE
View in PopUp triggern mit einem Objekt

### ISSUE THREAD

**Issue by Kespri** [inventwo/ioBroker.vis-inventwo#180]
Ist es möglich, beim PopUp eine weitere Funktion einzubauen?

Es wäre cool, wenn sich das PopUp öffnet, wenn ein Objekt z.B. auf TRUE geschaltet wird und evtl auch schliesst, wenn der Wert wieder auf FALSE geht.

**Comment by jkvarel** [comment]
@Kespri 
Automatisch schließen ist mit der Version 2.9.0 möglich. Automatisch öffnen kommt noch
![image](https://user-images.githubusercontent.com/35769746/114162877-d15a5880-9929-11eb-90d2-b63be0001e03.png)

**Comment by jkvarel** [comment]
v3.0.0: Popup kann per Datenpunkt geschlossen werden

**Comment by MichaelSchaaf999** [comment]
Geht automatisch öffnen auch jetzt? Über einen Datenpunkt?

**Comment by jkvarel** [comment]
@MichaelSchaaf999 , ja geht 
![image](https://user-images.githubusercontent.com/35769746/158424434-d39c860e-3f2b-45bd-b9ae-1e6305881679.png)

**Comment by MichaelSchaaf999** [comment]
Danke sehr!

**Comment by MichaelSchaaf999** [comment]
p.s.: Ein solcher Button (= ein solches Widget) muss ja nicht mal auf einer View stehen, die damit in direktem Zusammenhang steht. Ich kann diese Start-/Close-Widgets auch auf irgendeiner View im Projekt "verstecken".

**Comment by MichaelSchaaf999** [comment]
p.p.s.: Nein, ich muss mich korrigieren - diese Start-/Widgets dürfen NICHT auf irgendeiner View im Projekt stehen, dann werden sie nicht ausgeführt. Sie werden NUR DANN ausgeführt, wenn die View, auf der sie stehen, MINDESTENS EINMAL angezeigt und somit geladen war.
Ist das eine richtige Annahme?

Liebe Grüße
Michael

**Comment by MichaelSchaaf999** [comment]
Hi, das mit dem automatisch Öffnen hab ich gerade nicht mehr im Fokus: In welchen Widgets geht das bitte? Bin da etwas verwirrt...  bitte um Hilfe.
lg
Michael

**Comment by MichaelSchaaf999** [comment]
Hi jkvarel,
ich glaube, ich hab es nun bald. Sorry, musste ein wenig üben.
Ich habe nun ein (nahezu unsichtbares und nicht benutztes) vis-inventwo Universal Widget auf allen meinen Seiten.
Denn wenn in einer bestimmten Situation auf ALLEN Views auf ALLEN Clients ein Popup erscheinen soll, dann setze ich aus einem Script bspw den Datenpunkt "0Popup1" auf true. 
Beispiel: Die Haustür wird geöffnet oder es klingelt, dann soll auf allen Clients ein Hinweis aufgepoppt werden.
Dazu muss aber in ALLEN Views des Vis-Projektes auch der Universal-Button vorhanden sein, dann klappt das und auf allen Clients hier im Haus, egal welche View gerade gezeigt wird, wird dann das Popup aufgeblendet. Schließen nach Zeit oder falls dieser Datenpunkt vorher schon wieder auf false gesetzt wird, funktioniert wohl auch. 
Wenn nach Ablauf der eingestellten Zeit geschlossen wird: Dann wird der Datenpunkt allerdings nicht von alleine auf "false" gesetzt, der bleibt true. Das muss ich dann also irgendwo alleine regeln, oder?
Und: Ich habe in meinen Views eine Navigation in einem basic-view in widget, das also quasi in der angezeigten View A in diesem widget auf ein View B zeigt. Das sieht so aus:
<img width="507" alt="grafik" src="https://user-images.githubusercontent.com/53481090/187023499-de349af6-a594-4acf-9d99-72c5b7960a97.png">
Links außen also quasi die Navigation in einem basic-view in widget und die dort hinterlegten Buttons kann man dann benutzen.
NUN ist es aber so, dass bei Ende des Popups aus dem vis-inventwo-Universal-Switch als Typ ´View in Popup´ zwar das Popup geclosed wird - sehr gut - aber dann mein basic-view in widget Menü "leer" ist:
<img width="459" alt="grafik" src="https://user-images.githubusercontent.com/53481090/187023617-f51e896f-b3e0-4805-bb65-375148edb2d5.png">
Links bei den Fragezeichen müsste eigentlich wieder mein in dem basic-view in widget eingeblendetes Menü kommen, bleibt aber weg.
Was mache ich falsch bei der Anwendung des Popup-Schließens? Oder gibt es für das Menü dort eine bessere Lösung, die dann funktioniert?
Liebe Grüße
Michael

**Comment by MichaelSchaaf999** [comment]
p.s.: Ah, ich glaube, ich hab's durch Experimentieren herausgefunden:
In der als Popup benutzten View darf NICHT auch dies Menü in dem basic-view in widget vorhanden sein, so wie hier im Beispiel:
<img width="681" alt="grafik" src="https://user-images.githubusercontent.com/53481090/187024011-93342e59-724a-40f7-b198-d94c54e45caa.png">
Rechts in dem Popup mit der aussagekräftigen Übersichszeile "asdfasdf..." ist EBENFALLS dies Menü in dem basic-view in widget: Die blauen Buttons.
DANN ist es aber auch beim Close des Popups aus dem alten ersten View verschwunden, d.h. wird nicht angezeigt, wenn das Popup geclosed ist.
Lösung erstmal: Dieses Widget, das als Menü benutzt wird, darf NICHT in der Popup-View sein, dann klappt das, will sagen: Dann wird dies Menü-Widget auch nach Close des Popups wieder angezeigt.
Gibt es etwas Besseres?
LG
Michael
