### ISSUE TITLE
Dezimalzahl bei Slider Min. und Max.-Werten

### ISSUE THREAD

**Issue by maddingamer** [inventwo/ioBroker.vis-inventwo#184]
**Describe wanted Enhancement !**  
Aktuell lassen sich beim Min. und Max-Wert des Silders nur Ganzzahlen setzen. 
Komma oder Punkt funktionieren nicht.

**Why should we put effort in it ?**  
Wäre sehr cool und ist hoffentlich recht einfach umgesetzt 👍

**Comment by jkvarel** [comment]
@maddingamer , die Slider können bereits Dezimalzahlen. Beachte, dass du im Editor einen Punkt anstelle eines Kommas nutzen musst.
![image](https://user-images.githubusercontent.com/35769746/114039659-39099880-9883-11eb-9221-7d7408bbc346.png)

**Comment by maddingamer** [comment]
Dass das bei den Schritten geht, hatte ich gemerkt, aber ich möchte gern den Min/Max-Wert mit Dezimalstelle setzen. Das geht (zumindest bei mir) nicht.

**Comment by jkvarel** [comment]
@maddingamer sollte mit der 2.9.2 funktionieren
