### ISSUE TITLE
Widgets aktualisieren nicht bei Version 2.9.1

### ISSUE THREAD

**Issue by BernhardLinz** [inventwo/ioBroker.vis-inventwo#189]
Typ Switch schaltet zwar wechselt seine Farbe aber nicht. Nach neu laden der Webseite mit F5 wird die richtige Farbe angezeigt
Typ View arbeitet normal.

Mit 2.8.3 funktioniert alles normal.

**Comment by jkvarel** [comment]
Hast du wirklich die 2.9.1 oder die 2.9.0? Mit der 2.9.0 funktioniert es nicht. Den Fehler habe ich mit der 2.9.1 wieder behoben

**Comment by BernhardLinz** [comment]
2.9.0, gerade gesehen (ich schaue parallel immer auf GitHub)
