### ISSUE TITLE
Bug? Universal Wigdet: Switch ändert Status aber Anzeige in VIS wird nicht aktualisiert

### ISSUE THREAD

**Issue by n3ucr0n** [inventwo/ioBroker.vis-inventwo#191]
Hallo,
ich habe heute das Update auf 2.9.0 gemacht.

OT: Danke für die Option, ein PopupWidget automatisch nach gewisser Zeit zu schließen

Nun beobachte ich folgendes Problem:
Wenn ich über das Universal Widget im Switch Mode ein Licht umschalte, wird zwar der Datenpunkt geändert und das Licht geht an / aus, jedoch passt sich die Visualisierung des Widgets nicht an den neuen Status an.
Nur wenn ich manuell die VIS aktualisiere, wird das Wirdget korrekt angezeigt.

Liebe Grüße

**Comment by Flyor** [comment]
Hab das gleiche Problem. Schalte mit meinen Widgets verschiedene Datenpunkte aus und ein, welche dann durch iFrame ein View in View ergeben. Der "Switch" selbst funktioniert einwandfrei, jedoch wird der Farbwechsel durch die Aktivierung nicht mehr durchgeführt. Es kommt keine Rückmeldung an das Widget. Betrifft soweit ich das feststellen kann jeden bool switch.

**Comment by skvarel** [comment]
Bitte auf 2.9.1 updaten. Dort ist der Fehler behoben worden.

**Comment by jkvarel** [comment]
Das Problem besteht nur in der 2.9.0. Den Fehler habe ich mit der 2.9.1 behoben
