### ISSUE TITLE
Universal und Mulitiwidget funktionieren nicht

### ISSUE THREAD

**Issue by tomtom123123** [inventwo/ioBroker.vis-inventwo#195]
Aus irgendeinem Grund funktionieren diese beiden Widget auf meinem Tablet/ Smartpohone nicht mehr. Auf einem Laptop mit Windows 10 funktionieren sie jedoch., ebenso funktionieren alle anderen Widgets auch auf meinem Tablet/ Smartphone. Hat da vielleicht irgendjemand eine Idee zu? Ich habe leider nichts gefunden. 

LG

**Comment by skvarel** [comment]
Hallo @tomtom123123 

Ist das Problem weg? Was war der Grund?

Gruß, Sven
