### ISSUE TITLE
Button im Modus „State.

### ISSUE THREAD

**Issue by ing-michel** [inventwo/ioBroker.vis-inventwo#196]
Hallo der Button reagiert nicht im Modus „State“ in Farbe und Beschriftung je nachdem, ob das Objekt True oder false ist.

**Comment by skvarel** [comment]
Hallo.

Der Button kann nicht reagieren, da es beim Typ 'State' keine Satatusänderung gibt. Es ist ein Pufh-Button, kein Switch.

Lediglich über die 'Rückmeldungsdauer' kann man ein optisches Signal bekommen, ob man den Button gedrückt hat.

**Comment by ing-michel** [comment]
Hallo. Danke für deine Rückmeldung. 

Gewollt von mir war ein Button, der anzeigt, ob ein bestimmter State false oder true ist und sich anpasst, wenn der State sich änder. 

Das geht nicht, die Funktion „State“ eines Button kann nur durch drücken einen State setzen. Habe ich das korrekt verstanden?

Beste Grüße 
Michel

**Comment by skvarel** [comment]
Wenn Du nur 'prüfen' willst, dann ist Background der passende Typ .. dann kann das Widget nur lesen.

**Comment by skvarel** [comment]
![grafik](https://user-images.githubusercontent.com/1114419/114848434-f98d0000-9dde-11eb-9a63-bf7407b3c5a4.png)

**Comment by ing-michel** [comment]
Oh man, sorry. Ich hasse die Leute, die die Anleitung nicht richtig lesen...
-> Danke, habe Dir einen Kaffee ausgegeben.

**Comment by skvarel** [comment]
Dankeschön :)
