### ISSUE TITLE
JSON Table - incorrect view of content

### ISSUE THREAD

**Issue by MKI-Munich** [inventwo/ioBroker.vis-inventwo#197]
Using the JSON table widget I see the objects instead of the content. In the editor the content is shown.
VIS Editor view:
![vis_editor](https://user-images.githubusercontent.com/30495003/115145657-ef733780-a052-11eb-8a06-05f4a4323003.PNG)

Runtime:
![vis_runtime](https://user-images.githubusercontent.com/30495003/115145663-f5691880-a052-11eb-85ea-0409b1c70c28.PNG)

**Comment by skvarel** [comment]
You need the 'Attreibute for JSON'

![grafik](https://user-images.githubusercontent.com/1114419/115147922-8513c480-a05d-11eb-98ce-e8e547f86312.png)

**Comment by MKI-Munich** [comment]
Thank you very much for the fast help! Works perfect now.
