### ISSUE TITLE
Bilder "flackern" im Button

### ISSUE THREAD

**Issue by ing-michel** [inventwo/ioBroker.vis-inventwo#202]
Hallo,
habe folgendes Problem: 

in meinem Button "flackern" die Bilder der Buttons. habe einen Screencast aufgenommen, um es zu zeigen:

https://www.dropbox.com/s/gqfrtmvq62lkznn/Bildschirmaufnahme%202021-04-25%20um%2017.27.36.mov?dl=0

Ist das ein Bug? Oder mache ich was falsch?

Liebe Grüße
Michel

Das obere Widget:
`[{"tpl":"i-vis-universal","data":{"g_fixed":false,"g_visibility":false,"g_css_font_text":true,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","iUniversalWidgetType":"State","iValueType":"value","iValueComparison":"lower","iStateResponseTime":"0","iStateResetValueTime":"0","iNavWait":"100","iPopUpBackground":"#666666","iPopUpPreventClickOutside":"","iPopUpShowTitle":"true","iPopUpTitle":"","iPopUpTitleColor":"#ffffff","iPopUpCloseBtnColor":"#dc2e2e","iPopUpWidth":"800px","iPopUpHeight":"500px","iPopUpPosition":"center","iPopUpCornerRadiusUL":"12","iPopUpCornerRadiusUR":"0","iPopUpCornerRadiusLR":"12","iPopUpCornerRadiusLL":"0","iPopUpShadowXOffset":"2","iPopUpShadowYOffset":"2","iPopUpShadowBlur":"2","iPopUpShadowSpread":"1","iPopUpShadowColor":"#111111","iButtonCol":"#333333","iButtonActive":"#455618","iButtonColHover":"","iOpacityBack":"1","iCornerRadiusUL":"12","iCornerRadiusUR":"0","iCornerRadiusLR":"12","iCornerRadiusLL":"0","iContentFlexDirection":"vertical","iContentVertAlign":"iSpace-between","iContentOrder":"orderImgText","iOpacityCtn":"1","iTextColor":"#f2f2f2","iTextSize":"17","iTextAlign":"iCenter","iTextSpaceTop":"0","iTextSpaceBottom":"0","iTextSpaceLeft":"0","iTextSpaceRight":"0","iIconSize":"68","iImgAlign":"iCenter","iImgSpaceTop":"5","iImgSpaceBottom":"0","iImgSpaceLeft":"0","iImgSpaceRight":"0","iImgRotation":"0","iImgBlinkFalse":"0","iImgBlinkTrue":"0","iImgColorFalse":"","iImgColorTrue":"","iShadowXOffset":"2","iShadowYOffset":"2","iShadowBlur":"2","iShadowSpread":"1","iShadowColor":"#111111","iShadowColorActive":"#111111","iShadowColorHover":"","iShadowInnerXOffset":"0","iShadowInnerYOffset":"0","iShadowInnerBlur":"0","iShadowInnerSpread":"0","iShadowInnerColor":"#111111","iShadowInnerColorActive":"#111111","iShadowInnerColorHover":"","iBorderSize":"0","iBorderStyle":"none","iBorderColor":"#ffffff","iBorderColorActive":"#ffffff","iBorderColorHover":"","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"oid":"javascript.0.lmair.temp-sensoren.aussen.temperature","iValueTrue":"","iTextTrue":"sensoren.aussen.temperature}","iTextFalse":"{javascript.0.lmair.temp-sensoren.aussen.temperature} &deg;C","iImageFalse":"/vis.0/eigeneBilder/garden1.png","iImageTrue":"","value":""},"style":{"left":"734px","top":"287px","width":"125px","height":"90px","font-family":"Jura-Regular"},"widgetSet":"vis-inventwo"}]`

**Comment by jkvarel** [comment]
Meine erste Vermutung ist, dass der Datenpunkt so oft aktualisiert wird. Kannst du was dazu sagen? Also wann oder wie oft der sich aktualisiert?

**Comment by ing-michel** [comment]
Oh man - ja, korrekt.

Der Datenpunkt wurde jede Sekunde, statt jede Minute aktualisiert. Habe ich das Bild weggelassen, hat man es nicht gesehen. Aber nun ist es perfekt.
Danke Dir!
