### ISSUE TITLE
Verweildauer und Rückmeldungsdauer keine Funktion?

### ISSUE THREAD

**Issue by Lucifor1976** [inventwo/ioBroker.vis-inventwo#205]
Guten Tag

Bei einem State oder Switch, einzeln oder Multi tut sich bei der Rückmeldungdauer nichts. Bzw. egal welchen Wert ich einstelle, es sind und bleiben ca 1000ms also knapp eine Sekunde. Anscheinend funktionieren nur Werte unter 1000ms?

Verstehe ich die "Rückmeldungsdauer" richtig?
Wenn ich einen State nutzen muss und möchte das der "Taster" ein paar Sekunden "anzeigt" das er gedrückt wurde und die Funktion ausgeführt wurde nutze ich die Rückmeldungdauer um dies anzuzeigen, korrekt? Funktioniert aber nicht. Der "Taster" springt sofort wieder in den Status bereit bzw ungedrückt. Egal welche Zeit in ms ich dort einstelle. 
Das ganze unter Safari, Firefox, Fully auf Fire HD 7 oder Fire HD 10.

Szenario: Ein State aktiviert eine ioBroker Szene, diese Szene setzt die Lautstärke aller Alexas auf 50, gibt einen Sprachtext aus und stellt danach die Lautstärke wieder auf 30 herunter. Da ich gerade an einer VIS in Verbindung mit einem Fire HD 7 als Smarte Türklingel arbeite (was wunderbar funktioniert) wäre es schön, wenn dem Klingelden per Rückmeldungsdauer mitgeteilt werden kann das die Klingel ausgelöst wurde, es geht auch ohne, keine Frage, aber unser Postpote hat die scheiss Angewohnheit Sturm zu Klingeln, selbst für verkackte Werbung, daher möchte die Funktion nutzen um a) anzuzeigen das es geklappt hat und b) Sturmklingeln zu verhindern :)

Any Hints?

Edit: Jetzt mal etwas intensiver getestet, wenn ich einen neuen Button anlege, klappt das ganze ein paar Mal, dann einfach ohne Änderungen nicht mehr und die eingestellte Zeit wird ignoriert, reload bringt keine Änderung.

**Comment by jkvarel** [comment]
Hallo, 

die Rückmeldedauer gibt es nur beim State. Ja, Rückmeldedauer heißt, bleibe solange im "Wahr-Zustand". 
Mit dem Universalwidget konnte ich gerade ohne Probleme auch den Wert auf 2000ms stellen und er blieb dann auch 2 Sekunden. Mit dem Multi ebenfalls, außer der Datenpunkt erhält in der Zeit einen anderen Wert. Dann aktualisiert sich nämlich das Widget und die  Zustände werden geprüft, was an sich auch richtig ist.

Hat der Datenpunkt, den du für das Widgets nutzt, verschiedene Werte oder wird immer nur der gleiche reingeschrieben?

**Comment by Lucifor1976** [comment]
Hi,

der Datenpunkt ist eine Szene in ioBroker, kennt also nur true und false. Es wird beim tasten also nur auf true gesetzt, mehr passiert nicht. Wie gesagt; mit einem neuen Button geht es ein paar mal, dann ist irgendwann ende, das habe ich heute mehrfach reproduziert.

**Comment by jkvarel** [comment]
v3.0.0:  Problem mit Rückmeldedauer ist behoben. Bitte um Rückmeldung ob das auch bei dir der Fall ist

**Comment by jkvarel** [comment]
Da keine Antwort mehr kam gehe ich erstmal davon aus, dass das Problem behoben ist. Falls nicht bitte melden
