### ISSUE TITLE
View in PopUp schließt nicht

### ISSUE THREAD

**Issue by senger1985** [inventwo/ioBroker.vis-inventwo#208]
**Describe the bug**  
Popup lässt sich nicht schließen, bei "Klick" auf Freifläche.

**Versions:**  
 - Adapter version: 2.9.7
 - JS-Controller version: 3.3.8
 - Node version: 12.22.0
 - Operating system: Linux

![PopUp](https://user-images.githubusercontent.com/35745035/116942803-97534c80-ac72-11eb-9f26-f917788e01f7.PNG)

**Comment by jkvarel** [comment]
Auf welchen Geräten und mit allen Browsern?

**Comment by senger1985** [comment]
Windows-Rechner und Microsoft Edge.
Frag mich bitte nicht, aber es geht wieder, wenn ich neben das PopUp klicke, dass es geschlossen wird.
Kannst gerne das Issue schließen, wenn du der Meinung bist.

**Comment by jkvarel** [comment]
Ich schließe das Issue erstmal. Sollte der Fehler wieder auftauchen gerne mitteilen

**Comment by RelaxedHome** [comment]
Hallo bei mir taucht der wieder Fehler auf, allerdings nur auf einer Seite mit dem Widget : 
<img width="142" alt="Bildschirmfoto 2021-10-30 um 21 15 44" src="https://user-images.githubusercontent.com/91123351/139555838-3418659a-d170-4ecc-85ec-9bb9b64d10ba.png">
