### ISSUE TITLE
Links funktionieren nicht im PopUp

### ISSUE THREAD

**Issue by bloop16** [inventwo/ioBroker.vis-inventwo#218]
Hallo,

Sowohl beim Universal als auch beim Multi Widget ist es nicht möglich ein Link Widget im hinterlegten View auszuführen, wenn als Funktion View in Popup ausgewählt wird.

Würde gerne aus dem Popup heraus einen _blank Link in einen neuen Fenster öffnen.

Herzlichen Dank
Martin

**Versions:**  
 - Adapter version: 2.9.7
 - JS-Controller version: v12.22.1
 - Node version: 3.2.16
 - Operating system: Linux

**Comment by jkvarel** [comment]
Ich hab den Fehler gefunden. Bitte mit der nächsten Version testen

**Comment by jkvarel** [comment]
v3.0.0: Links in Popups funktionieren. Bitte um Rückmeldung ob dies auch bei dir der Fall ist

**Comment by bloop16** [comment]
Funktioniert!
Herzlichen Dank!
