### ISSUE TITLE
Uhren-Widget

### ISSUE THREAD

**Issue by galegro** [inventwo/ioBroker.vis-inventwo#230]
Mein Wunsch wäre ein Widget mit einer Uhr - passend zu dem Stil von Inventwo . Die Farbe der Anzeigeelement (Zeiger, Marken, Zahlen, ..) sollten frei wählbar sein, die Gestaltung des Hintergrundes eurer Widgets ist ja bereits ideal, weitere Anpassungen vorzunehmen.

**Comment by jkvarel** [comment]
Geht es dir primär um eine analoge oder digitale Uhr?

Ich denke, dass ich irgendwann beide Uhren erstelle aber welche würdest du dir eher wünschen?

**Comment by galegro** [comment]
Mein Wunsch ist primär eine analoge Uhr zur Verfügung zu haben.

**Comment by jkvarel** [comment]
v3.0.0: Analoge und digitale Uhr kann als Inhaltstyp ausgewählt werden
![image](https://user-images.githubusercontent.com/35769746/122922562-0b050200-d364-11eb-92b3-513e248f4ab4.png)
