### ISSUE TITLE
Wunsch: Checkboxen & (Gruppen von) Radiobuttons

### ISSUE THREAD

**Issue by galegro** [inventwo/ioBroker.vis-inventwo#239]
Um in (unseren) Hausautomationen komfortabler Steuerungen und Konfigurationen zu realisieren (Mein Vorhaben: Steuerung einer DAIKIN Klimaanlage) wären Gruppen von Checkboxen und Radiobuttons eine feine Sache.

Checkbuttons: kleine weiße Quadrate mit/ohne Häkchen; unabhängig von einander (de)aktivierbar
Radiobuttons: kleine weiße Kreise, komplett leer oder mit schwarzem Punkt gefüllt; immer nur ein Button kann aktiv sein

Der Code für die aufwendige Radiobutton-Implementierung sollte ja schon vorliegen, denn das Button-Widget arbeitet ja bereits wie die von mir gewünschten Radiobuttons. Es wäre somit "bloß" eine alternative optische Darstellung zu erstellen.

**Comment by jkvarel** [comment]
Ab v3.1.0 gibt es ein neues Widget: Checkbox/Radiobutton

Mit diesem lassen sich einmal Listen von Checkboxen und Radiobuttons erstellen. Damit es sich wie Radiobuttons verhält muss einfach bei allen Boxen der gleiche Datenpunkt eingetragen werden
