### ISSUE TITLE
View in PopUp Angabe Breite und Höhe

### ISSUE THREAD

**Issue by an-klam** [inventwo/ioBroker.vis-inventwo#244]
Bei der Funktion view in Popup muss die Größe des PopUp Fensters angegeben werden.

Wenn man nur die Zahl eingibt (in meinem Fall 370x370) und das "px" dahinter weglässt, dann wird das PopUp auf einigen Geräten nicht angezeigt.

Bei der Größe des Widgets kann das px weggelassen werden und es funktioniert trotzdem. 

Ist an sich nicht falsch aber es hat mich doch einiges an Zeit gekostet, bis ich herausgefunden habe warum das PopUp auf dem Laptop angezeigt wird auf dem Tablet aber nicht.

**Comment by jkvarel** [comment]
Habs jetzt so gemacht, dass wenn man nur z.B. 500 eingibt dann packt der da intern ein px hinter wie bei den Widget größen.
Ist mit dem nächstem Update dann drin
