### ISSUE TITLE
CSS Font & Text ==> text-shadow

### ISSUE THREAD

**Issue by BernhardLinz** [inventwo/ioBroker.vis-inventwo#246]
In Version 3.0.1 gibt es für die Widgets "Universal" und "Multi" die neue Option "Schatten Text:".
Nun wird nicht mehr - wie bisher - das Feld

**CSS Font & Text** => **text-shadow**

ausgewertet / beachtet.
Ich würde mir wünschen das zusätzlich der Inhalt dieses Feldes mit beachtet wird - sofern dort etwas gesetzt ist.

**Comment by jkvarel** [comment]
Habs so geändert, dass unsere Einstellungen erst greifen, wenn man X Versatz, Y Versatz oder Blur erhöht. Heitß also standardmäßig wird das Feld unten benutzt
