### ISSUE TITLE
JSON Table: Fehler bei Format datetime

### ISSUE THREAD

**Issue by bluefish007** [inventwo/ioBroker.vis-inventwo#250]
Hallo,

seit der Version 3.0.0 funktioniert bei mir die Anzeige der JSON Table mit einem Datumsobjekt und dem Format "datetime" nicht mehr. Ohne eingegebenes Format zeigt er mir das Datum in ms an, aber sobald ich ein Format angebe, z.B. H:i zeigt er nichts an und das Widget löscht sich (w00555_removed). Man kann es dann nicht mehr anklicken, sondern nur noch in der Widget-Liste (Aktives Widget) auswählen...

(Nach dem Downgrade auf 2.9.7 funktioniert die Datumsanzeige wieder mit dem richtigen Format)

<img width="595" alt="Bildschirmfoto 2021-07-04 um 14 14 14" src="https://user-images.githubusercontent.com/72299469/124384571-3b3c9100-dcd2-11eb-95b8-f566219e0574.png">
<img width="599" alt="Bildschirmfoto 2021-07-04 um 14 14 32" src="https://user-images.githubusercontent.com/72299469/124384578-3e378180-dcd2-11eb-8d33-7614ed2f8132.png">
<img width="781" alt="Bildschirmfoto 2021-07-04 um 14 14 54" src="https://user-images.githubusercontent.com/72299469/124384581-40014500-dcd2-11eb-8519-610f5d885a2d.png">

Komischerweise zeigt er mir auch manchmal Optionen an, die gar nicht zum datetime dazu passen:
<img width="443" alt="Bildschirmfoto 2021-07-04 um 14 10 22" src="https://user-images.githubusercontent.com/72299469/124384447-9457f500-dcd1-11eb-92ec-cc1a4191364c.png">

**Comment by jkvarel** [comment]
@bluefish007 
Fehler mit dem Format ist mit dem nächstem Update behoben.

Dass der manchmal Optionen anzeigt, die nicht dazugehören liegt an gewissen Events. Z.B. wenn man den Editor neu lädt und das Widget bleibt ausgewählt. Damit dir nur die richtigen angezeigt werden einfach einmal auf das Widget klicken. Dann aktualisieren sich die Felder

**Comment by jkvarel** [comment]
@bluefish007 
v3.1.o ist online. Mit dem Update sollte der Fehler bei dir behoben sein. Bitte um Rückmeldung

**Comment by bluefish007** [comment]
@jkvarel 
Gerade das Update auf v3.1.2 installiert! Fehler behoben! Funktioniert - besten Dank!
