### ISSUE TITLE
Button in einem Popup Fenster haben keine Reaktion

### ISSUE THREAD

**Issue by seers84** [inventwo/ioBroker.vis-inventwo#260]
Die Buttons die in der **Visualisierung in einem Popup** eingebaut sind funktionieren nach dem letzten Update nicht mehr.
Es sind Radiobuttons aus der jqui Widgetsammlung.
Radiobutton funktioniert wenn dieser nicht in einem Popup eingebaut sind.
Dies funktionierte bisher alles ohne Probleme.

Wenn ich einen Inventtwo Button als Switch in ein Popup einbaue funktioniert es!

Edit: 
Wenn die Popup Seite als reguläre Seite geöffnet wird also im Vollbild funktionieren auch die Buttons.

Bild Visualisierung
![2](https://user-images.githubusercontent.com/87387550/125499033-f3ad7eb9-84e4-4f9d-bcb1-648def035485.JPG)

Bild Version
![1](https://user-images.githubusercontent.com/87387550/125499091-410e12a4-a7ff-40db-806b-cf0f6cb54b81.JPG)

**Comment by jkvarel** [comment]
@seers84 
Ahh ich sehe du läufts auf Stable. 
Ich habs bei mir gerade mit der aktuellsten latest Version v3.0.11 getestet und bei funktionieren die Widgets im Popup.

Da für die Version aber keine Fehler mehr kamen werde ich die ins Stable schieben lassen. Bitte gebe mir Feedback wenn die Version im Stable ist ob der Fehler weiterhin besteht

**Comment by seers84** [comment]
@jkvarel
sieht gut aus erster Test mit v3.0.11 war gut funktioniert! 
Top Danke!
