### ISSUE TITLE
inventwo Design Widgets installation bricht mit Fehler ab

### ISSUE THREAD

**Issue by betonix70** [inventwo/ioBroker.vis-inventwo#265]
Hallo,

hätte da eine Frage. Ich habe gerade versucht auf einer IoBroker Docker Instanz auf einer Synology NAS den Adapter inventwo Design Widgets zu installieren. (aktuelle Version und in der älteren Version lief der Adapter!?)
Leider bricht die Installation in der neuen Umgebung immer wieder mit einem Fehler ab.
Blöder Weise komme ich gerade nicht an die NAS heran, so dass ich den genauen Fehler nicht nennen kann.

Eventuell kann mir ja jemand schon jetzt einen Tipp geben...

**Comment by betonix70** [comment]
So hier noch ein paar Infos zum genannten Problem IoBroker ist Version 4.2.2
Fehler beider inventwo Design Widgets Installation:
$ ./iobroker add vis-inventwo  --host ioBroker
NPM version: 6.14.13
npm install iobroker.vis-inventwo@3.0.11 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/supports-color: Integrity verification failed for sha512-DING2QV62aoI3KUKuv5qoC613YsGtO073216ozCf8r1Pb4oeJocY842Mn5tDJ7q7zZgi4JhygAZKcg0ivinOXA== (/opt/iobroker/.npm/_cacache/content-v2/sha512/0c/83/46d9057ad9aa08dca50abafe6aa02eb5dd8b06b4ed3bdf6d7aa3309ff2bd4f6f8a1e268718f38d8c9f9b4327babbcd9822e0987280064a720d22be29ce5c)
npm ERR! A complete log of this run can be found in:npm ERR!     /opt/iobroker/.npm/_logs/2021-07-25T18_19_44_689Z-debug.log
ERROR: host.ioBroker Cannot install iobroker.vis-inventwo@3.0.11: 1
ERROR: process exited with code 25

**Comment by sigi2345** [comment]
> So hier noch ein paar Infos zum genannten Problem IoBroker ist Version 4.2.2

> ERROR: process exited with code 25

Stoppe den Adapter vor der Installation.

**Comment by betonix70** [comment]
Danke!

**Comment by jkvarel** [comment]
@betonix70 ist der Fehler behoben? Falls ja bitte das Issue schließen.
Und danke @sigi2345

**Comment by betonix70** [comment]
Den Adapter schließen war mir nicht möglich!? - er war ja noch gar nicht installiert.
Ich habe den IoBroker komplett neu aufgesetzt, danach war die Installation problemlos möglich.

Vielen Dank für die schnelle Hilfestellung!
