### ISSUE TITLE
Vis shows nothing on Smartphone in IOB App.

### ISSUE THREAD

**Issue by Beliar-666** [inventwo/ioBroker.vis-inventwo#27]
Hello, 
Nice Work. But i have a Problem with the IoBroker app. I just build up a view on PC with this Adapter. On my PC in Browser everything works fine. But on my Smartphone in the IoB App nothing shows up. just a blank Screen.

Just tested on my phone in Browser, there it works. Only in the App there is a blank screen.

**Comment by jkvarel** [comment]
Hi,
are widgets from other adapters working and only ours not?

**Comment by Beliar-666** [comment]
Only Your Widgets are not working. All others work.

**Comment by jkvarel** [comment]
We can't say why it'ss not working for you. Because we  don't use the app we cant try to replicate the problem. The adapter also works for someone else.
![Issue](https://user-images.githubusercontent.com/35769746/76143868-27036800-607b-11ea-95c5-f92da9f2f344.png)

**Comment by Beliar-666** [comment]
Dann muss ich wohl noch mal schauen warum ausgerechnet eure nicht angezeigt werden. Trotzdem Danke. Sollte ich einen Fehler finden, werde ich ihn hier vermelden, falls mal jemand anderes das gleiche Problem hat.

**Comment by Apollon77** [comment]
In android app?? Dann ist das normal. Die android app hat ein set von Widgets eingebaut. Nachdem diese Widgets im stable sind müsste man ein Vis issue anlegen um diese Widgets in einer neuen Version der android app zu sehen. 

Oder ist die iOS App gemeint? Dann: cloud oder lokal?

**Comment by Beliar-666** [comment]
@Apollon77  Also lag es doch nicht an mir?

**Comment by spider12785** [comment]
Ich habe aktuell ein ähnliches Problem. Wenn ich mir switches nehme werden die bei meinem Ipad(los 9.3.5 safari) nicht angezeigt. Die State Widget allerdings werden normal angezeigt. 

Ich habe eine Reihe mit 5 Widgets. States und switches gemischt. Bei Android und am Pc werden alle einwandfrei angezeigt. Beim ipad sind auf jedenfall Lücken, wo eigentlich sie switches waren.
Ipad wurde auch schon rebootet und cache wurde geleert

**Comment by michihorni** [comment]
Hallo ich habe das selbe Problem auf einem Android Tablet mit FullyBrowser.
Alles andere wird angezeigt nur die inventwo widgets nicht. Wenn ich auf dem Tablet diese View im Chrome öffne sehe ich die Widgets. Michael

**Comment by jkvarel** [comment]
Hallo,

kurz zusammengefasst:

Unsere Wídgets funktionieren in der App nicht, weil diese dort noch irgendwie eingebunden werden müssen. Das müssen wir uns mal angucken.

In jedem anderem Browser, egal ob auf dem PC, Tablet oder Handy sollten die Widgets funktionieren. Außer: Bei einem Android Gerät z.B. kann es an irgendeiner zu alten Browser Version oder so liegen. Aber das soll an Android liegen und das kann man nicht updaten. In diesem Fall funktionieren die leider nicht.

**Comment by adele0449** [comment]
Hallo, ich habe das gleiche Problem! Auf allen Browsern am PC laufen Ihre Widgets. Am Tablet (Android 5.0.1und auch am Samsung Galaxy A 70 (Android 10) mit iobroker-vis  ist nichts zu sehen. 
Sehr schade, da ich mich darauf eingestellt hatte alles damit zu gestalten.

**Comment by Apollon77** [comment]
Für Android App bitte hier ein issueanlegen das der adapterreinkommt oder nen PR machen https://github.com/ioBroker/ioBroker.vis.cordova/issues
