### ISSUE TITLE
Ausrichtung (Drehung) der Widgets

### ISSUE THREAD

**Issue by dany198300** [inventwo/ioBroker.vis-inventwo#276]
Leider kann man die Widgets selbst nicht drehen. Wäre super wenn man die Widgets selbst wie die Bilder Ausrichten und drehen könnten.

Siehe Bsp. (RGB) im Bild

![Bildschirmfoto 2021-08-12 um 14 52 45](https://user-images.githubusercontent.com/88837379/129202404-c4076bc1-e056-4feb-8aae-73c6ec90c721.png)

**Comment by jkvarel** [comment]
Das bietet der Vis-Editor bereits: Statt der -15 dann dort deine Gradzahl eintragen
![image](https://user-images.githubusercontent.com/35769746/129597006-305f0476-d3d6-4947-9912-907a680d9d87.png)
