### ISSUE TITLE
Value ausgeben

### ISSUE THREAD

**Issue by tommyMX** [inventwo/ioBroker.vis-inventwo#279]
Hi,

wie kann man in dem Widget einen einfach Value abrufen dass er entsprechend im Widget dargestellt wird?

Gerne auch zusätzlich mit einem icon.

Danke

**Comment by tommyMX** [comment]
Also einen Wert :-)

**Comment by sigi2345** [comment]
> Also einen Wert :-)

Mit binding :   {DEIN DP}

![Screenshot (4203)_LI](https://user-images.githubusercontent.com/41079106/130291231-5fcb277c-0d1b-40a4-a49a-5422c46e0d65.jpg)

**Comment by jkvarel** [comment]
@tommyMX konnte die Antwort von @sigi2345  dir helfen?

**Comment by jkvarel** [comment]
Ich gehe erstmal davon aus, dass sich die Frage geklärt hat. Falls nicht gerne melden
