### ISSUE TITLE
Color Slider CIE -> Datenformat =[0.4437,0.3062]

### ISSUE THREAD

**Issue by RacinR** [inventwo/ioBroker.vis-inventwo#284]
Hallo,
ich verwende LED-Stripes mit Controllern von Gledopto (GL-C-008) und Lidl (TUYA).
Bei beiden wird die Farbe als CIE geschrieben, jedoch passt der String nicht, der in den Datenpunkt geschrieben wird.
Geschrieben wird der Wert aktuell z. B. im Format "0.4437,0.3062", 
die Controller erwarten den String jedoch im Format "[0.4437,0.3062]", also mit eckigen Klammern zu Beginn und Ende.
Wäre es vielleicht möglich, für den Color Slider eine Version "CIE mit []" zu erstellen?

**Comment by jkvarel** [comment]
@RacinR 
Hab ich umgesetzt. Ich hoffe, dass es richtig funktioniert. Im Datenpunkt steht es zumindest jetzt mit Klammern drin. Das Widget liest den Datenpunkt beim ersten mal und schreibt den Wert dann im gleichem Format wieder rein. Ich bitte um Rückmeldung, ob es mit dem nächstem Update funktioniert

**Comment by RacinR** [comment]
Hallo Jannis,

vielen Dank!
Ich verwende aktuell nur den Release-Stand. Ich nehme an, dass ich die Beta-Version installieren muss, um es zu testen?

Gruß,
Rolf.

**Comment by jkvarel** [comment]
@RacinR, ja die Version ist aktuell nur in der Beta. Wenn bis zum Wochenende keine Fehler auftauchen geht die Version in Stable

**Comment by RacinR** [comment]
ok, dann warte ich. 
Besten Dank!

**Comment by RacinR** [comment]
V3.2.0 installiert und getestet -> funktioniert!
Vielen Dank!
