### ISSUE TITLE
Farbe/Farbe aktiv für Text im Universal-Widget

### ISSUE THREAD

**Issue by mlapp** [inventwo/ioBroker.vis-inventwo#285]
Das Universal-Widget unterstützt Farbe und Farbe aktiv für den Hintergrund aber leider nur Farbe für den Text.
Schön währe, wenn es für den Text auch zwischen Farbe und Farbe aktiv unterscheiden könnte.
Hintergrund: Ich nutze das Widget als Schalter und ändere die Hintergrundfarbe von einem dunklen braun nach hell Orange, wenn der Button auf True geht. Die Schrift ist weiß und lässt sich dann nur noch schwer lesen.

**Comment by W0RSCHD** [comment]
Ich habe das Problem, habe auch verschiedene Farben für Status An und Aus.... Wenn an, dann wird das Widget auch gelb, das Funktioniert, die Farbe des Icons und des Textes soll dann Schwarz werden. Am PC in der VIS Runtime klappt das auch, aber auf dem Tablet mit der VIS App, bleibt die schrift dann trotzdem weiss und ist bei gelbem Widget logischerweise nur schwer lesbar...
Warum gehts am PC und in der VIS App nicht, bzw. was kann/muss ich noch einstellen damit auch auf dem Tablet die Farbe des Icons und des Textes in Schwarz ändert?
