### ISSUE TITLE
Konfiguration der Sortierung einer Spalte in Json-Tabelle

### ISSUE THREAD

**Issue by mlapp** [inventwo/ioBroker.vis-inventwo#286]
Es wäre super, wenn in der JSON-Tabelle eine Spalte als Standard für eine Sortierung inkl der Richtung konfiguriert werden könnte.

Hintergrund:
Ich nutze die Tabelle um mir die Verbrauchswerte von aktuell ca. 30 Geräten in einer Tabelle anzeigen zu lassen.
Viele dieser Geräte, werden über die Hausautomation geschaltet, oft auch automatisch oder sie werden in ihrer Leistung gesteuert,  z.B. machen unsere Wallboxen PV-Überschussladung und passen die Ladeleistung an den PV-Überschuss an.
Nun wäre es super, wenn man z.B. nach der Spalte "Watt" automatisch von groß nach klein sortieren könnte. So hätte man die größten Verbraucher stets im Blick.

**Comment by jkvarel** [comment]
Mit v3.2.6 kannst du über die Schwellwerte die ganze Zeile einfärben. Ich habe das in der Wiki mit aufgenommen. https://github.com/inventwo/ioBroker.vis-inventwo/wiki/Widget-Erkl%C3%A4rungen-ab-Version-2.x.x
![image](https://user-images.githubusercontent.com/35769746/151596552-dee4ee00-63f4-4b9b-b293-6eba90bb3072.png)
