### ISSUE TITLE
Switch

### ISSUE THREAD

**Issue by ossisp1** [inventwo/ioBroker.vis-inventwo#29]
Der Switch button funktioniert am PC Browser per Mausklick und zum antippen in Safari.
In Chrome oder Firefox keine Funktion beim antippen...

Alles auf aktuellem Stand.

**Comment by skvarel** [comment]
@ossisp1 .. vielen Dank für die Rückmeldung.

Wir können das Problem leider so nicht nachvollziehen, schauen aber nochmal alles durch.

Wir testen vor jedem Release alle Widgets auf drei verschiedenen ioBrokern mit verschiedenen Betriebssystemen und mit vier verschiedenen Browsern (Chrome, Firefox, Edge und Vivaldi). Auf den Handys nutzen wir Chrome und auf den Tablets den Wallpanel Browser. Überall funktionieren unsere Widgets einwandfrei.

**Comment by maddingamer** [comment]
Ich habe ein ähnliches Problem.. Unter Chrome funktioniert alles top (sowohl PC als auch Andorid-Tablet), aber mit dem fully kiosk browser wird leider absolut gar nichts aus dem adapter von euch angezeigt (nur iframes, welche nicht aus dem adapter sind..) irgendwelche Ideen?

Version 1.2.1

PS: Habe dem Entwickler vom Fully Kiosk Browser eine E-Mail geschrieben. Vlt kann er Hinweise geben (oder sagen auf welchem Browser Fully basiert).

So soll es aussehen:
![fully_soll](https://user-images.githubusercontent.com/7353549/77375455-cc9e2300-6d6d-11ea-9746-62d323ecff5c.png)
so sieht es leider aus:
![fully-screenshot](https://user-images.githubusercontent.com/7353549/77375457-cd36b980-6d6d-11ea-9b7e-4489b65b7657.png)

**Comment by maddingamer** [comment]
> PS: Habe dem Entwickler vom Fully Kiosk Browser eine E-Mail geschrieben. Vlt kann er Hinweise geben (oder sagen auf welchem Browser Fully basiert).

Scheinbar hat es was mit der (zugegeben uralten) Version von Android WebView zutun..

**Comment by Beliar-666** [comment]
> Scheinbar hat es was mit der (zugegeben uralten) Version von Android WebView zutun..

Also ich habe den Fullybrowser auf einem Archos Tablet, dort wird alles dargestellt.

**Comment by maddingamer** [comment]
> Also ich habe den Fullybrowser auf einem Archos Tablet, dort wird alles dargestellt.
Welche Android Version bzw WebView Version ist bei dir installiert? 
(steht in den Fully Settings bzw im Dashboard falls du das an hast unter Android version und Webview version)

**Comment by jkvarel** [comment]
Hallo

@ossisp1 , der Fehler ist hoffentlich behoben. Ansonsten kannst du dich gerne bei uns melden.

Bzgl. der falschen Ansicht (fehlende Widgets): Ist behoben? Liegt an der alten WebView Version?
Falls es  noch Probleme gibt könnt ihr euch gerne melden :)
