### ISSUE TITLE
Multi Switch "Beschriftung wahr" fehlt

### ISSUE THREAD

**Issue by mkshb** [inventwo/ioBroker.vis-inventwo#295]
**Describe the bug**  
Wenn ich einen Multi mit dem Widget Typ Switch erstelle, fehlt in den einzelnen Zuständen das Textfeld für die Bedingung wahr. Stattdessen wird mir eine View Auswahl angeboten.

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/24550678/133620702-1de53606-4333-477d-9f45-d45d35711e4f.png)

**Versions:**  
 - Adapter version: v0.80.0
 - JS-Controller version: 3.3.15
 - Node version: v12.22.5
 - Operating system: Docker unter debian

**Additional context**  
Ansonsten vielen Dank für die Widgets. Super Arbeit!

**Comment by jkvarel** [comment]
@mkshb es gibt einen kleinen Bug mit dem ein- und ausklappen der Optionen. Bitte klicke einmal hier drauf. Dann sollten die anderen Felder auftauchen
![image](https://user-images.githubusercontent.com/35769746/133796922-85b641b3-fa42-4d78-ad56-912956e2ed81.png)

**Comment by mkshb** [comment]
Moin, 
ich bin so oft durch die Optionen gegangen um sicher zu gehen, dass ich nichts übersehen habe, aber das ist mir nicht aufgefallen. 
Danke @jkvarel
