### ISSUE TITLE
nochmal Farben im Universal Widget

### ISSUE THREAD

**Issue by shrek24** [inventwo/ioBroker.vis-inventwo#302]
Ich möchte mehrere Universal Widgets als Navigations-Buttons parallel darstellen. Alle Buttons werden in allen Views angezeigt. 
Beim jeweils aktiven View sollen die Farben für Hintergrund, Text und Bild des zugehörigen Widgets anders dargestellt werden. Beim Hintergrund funktioniert das problemlos, beim Text und/oder Bild nur beim Start-View. Wenn man auf einen anderen View schaltet, ändert sich die Farbe manchmal für den Text, manchmal für das Bild nicht mehr, manchmal ist es auch vertauscht, kann da leider keine "innere Logik" finden, ob und wann mal das Bild und wann der Text betroffen ist, eins geht immer, das andere dann nicht.  

Beispiel: Start mit View A, Farben ok:
![image](https://user-images.githubusercontent.com/91475700/134924049-27a5853d-3c58-4ab7-b2ad-90fc57110f20.png)

nach Umschalten auf B, Farben vertauscht:
![image](https://user-images.githubusercontent.com/91475700/134924316-17be1e48-bd1e-4e33-99ce-688825592c01.png)

Farben sind auf beiden Widgets aber so eingestellt:
![image](https://user-images.githubusercontent.com/91475700/134924922-e9fa8262-a62d-48f1-929a-0c2d89cc7a7a.png)
![image](https://user-images.githubusercontent.com/91475700/134925459-75165f2b-d206-4e49-a62a-b40fc74cfc77.png)

**Comment by jkvarel** [comment]
Ich gehe erstmal davon aus, dass das Problem behoben ist. Sollte es nicht der Fall sein gerne melden
