### ISSUE TITLE
Schalter gibt keine Werte weiter

### ISSUE THREAD

**Issue by snoppy1970de** [inventwo/ioBroker.vis-inventwo#31]
Hallo,

ich habe das Problem, dass der Aktor den Wert 0 oder 1 benötigt. Dazu habe ich im Widget von "bolean" auf "Wert" gestellt und die Werte 1 und 0 eingegeben. Wenn ich dann den Schalter betätige wird nichts geschaltet und im Log erscheint eine Fehlermeldung "connection error: "value must be a number". Ist hier ein Fehler im Widget oder in meinen Einstellungen?

Wenn zum Schalten true/false benötigt wird, funktioniert es ohne Probleme.

Installierte Version:1.2.3

![widget](https://user-images.githubusercontent.com/63065268/78275346-c8ae9580-7511-11ea-9602-0344616c66de.png)

![log](https://user-images.githubusercontent.com/63065268/78275356-ccdab300-7511-11ea-9f3d-ef0c9ba30d98.png)

**Comment by jkvarel** [comment]
Wurde auf Facebook geklärt. Lag am Homee Adapter. Falls es doch noch nicht funktioniert bitte melden.
