### ISSUE TITLE
View in PopUp schließt nicht auf einem View

### ISSUE THREAD

**Issue by RelaxedHome** [inventwo/ioBroker.vis-inventwo#320]
Hallo,
das view in PopUp lässt sich auf einem View nicht schließen (auch nicht nach der eingestellten Zeit). Nur auf dieser Seite ist das Select ValueList widget drauf. Deshalb gehe davon aus das es damit zusammenhängt. Auf allen anderen Views funktioniert das View in PopUp tadellos.

<img width="142" alt="Bildschirmfoto 2021-10-30 um 21 15 44" src="https://user-images.githubusercontent.com/91123351/139555905-0218c313-293a-40dd-8fa1-3be10822e4aa.png">

**Comment by jkvarel** [comment]
Hallo @RelaxedHome ,

besteht das Problem mit der neusten Version noch?
Ich hab gerade eine View mit einem Select ValueList Widget erstellt und diese View im PopUp geöffnet und konnte diese ohne Probleme schließen.

**Comment by RelaxedHome** [comment]
Hi Jannes, 

Der Fehler ist behoben. Super Arbeit. Das Video ist vorbereitet ich denke Sonntag geht es online. 

Mit freundlichen Grüßen 

Sebastian Nierwitzki
