### ISSUE TITLE
Buttons etc. werden nicht komplett angezeigt. 

### ISSUE THREAD

**Issue by TomSC1984** [inventwo/ioBroker.vis-inventwo#33]
Im lokalen Netzwerk funktioniert alles ohne Probleme. Es werden alle buttons / switches / Etc. angezeigt. 

Über den Originalen Iobroker.pro Fernzugriff sehe ich leider gar nichts mehr. Woran kann das liegen? 

Alle adapter latest und aktuell

**Comment by jkvarel** [comment]
Nutzt du die ioBroker App? Wenn ja dann funktioniert es nicht weil die Widgets erst integriert werden müssen. Wir wissen aber nicht wie das geht, da wir die App nicht nutzen

**Comment by TomSC1984** [comment]
Nein ich nutze keine App. Ich nutze den Fernzugang über iobroker.pro 
![vis](https://user-images.githubusercontent.com/39329061/80011309-fc0a9180-84cb-11ea-8a39-4e0d43cf22c4.png)

So sieht es über den Browser aus.... mit Google Chrome. ( anderer Browser kein unterschied)
Auf dem Smartphone ( Android ) ist überhaut kein Text zu sehen. Nur die Widgedts, die nicht von euch sind werden komplett und richtig angezeigt.

**Comment by jkvarel** [comment]
Ok. Um nach dem Fehler suchen zu können brauche ich ein paar Informationen:
- Ist das die runtime View oder im Editor?
- Kannst du einmal ein Bild von der richtigen/funktionierenden Ansicht schicken?
- Ein Bild von den Einstellungen eines Widgets im Editor
- Adapter Version

**Comment by jkvarel** [comment]
Hallo @TomSC1984 ,

da wir seit mehreren Tagen nichts mehr von dir gehört haben, hoffen wir, dass das Problem behoben wurde. Wenn nicht dann kannst du dich gerne bei uns melden :)
