### ISSUE TITLE
Seit update auf 1.3.3, Anzeigefehler und verschobene Beschriftung

### ISSUE THREAD

**Issue by Flyor** [inventwo/ioBroker.vis-inventwo#34]
Ich habe heute ein Update auf die 1.3.3 gemacht, seither werden die Widgets im View nur noch eckig und nicht mehr abgerundet angezeigt. Im Editor genauso, klickt man einmal drauf, haben sie wieder abgerundete Ecken. Nach Aktualisierung allerdings wieder eckig. 

Des Weiteren ist die Beschriftung nun verschoben und viel weiter unten. Ich finde leider keine Option um diese manuell nach oben zu setzen. Ich bitte um Hilfe. 
![2](https://user-images.githubusercontent.com/64526892/80580361-b558f200-8a0b-11ea-889e-c81df63e6914.JPG)

**Comment by jkvarel** [comment]
Hallo Flyor,
damit wir herausfinden können woran es liegt brauchen wir  noch ein paar Informationen:
- Ist das Problem auch bei neuen Widgets? Also wenn du z.B. einen neuen Switch rein ziehst?
- Hast du noch andere Vis Adapter? Diese könnten eventuell Teile des CSS überschreiben, wenn die Klassen übereinstimmen

**Comment by Flyor** [comment]
Hab's gerade versucht, wenn ich neue Widget's rein ziehe schein alles zu passen. Zumindest der Text ist korrekt und angezeigt werden sie auch richtig. 

Was ist gemeint, mit Vis Adapter? der Vis Adapter selbst (da hab ich nur einen) oder Adapter FÜR die Vis (Widgets etc.) - letzteres hab ich mehrere.

**Comment by jkvarel** [comment]
Hmm ok. Dann müssen wir mal prüfen ob der CSS bei dir irgendwie überschrieben wird.
Hast du irgendwas im CSS im Editor eingetragen? Wenn ja, kannst du mir schicken, was du gemacht hast?

**Comment by Flyor** [comment]
Ich wüßte nicht mal wo ich den in der VIS finde :D Also dementsprechend wohl nein. Ich gebe gern Zugriff via Anydesk auf den Rechner.

**Comment by jkvarel** [comment]
Tut mir leid für die späte Antwort. Wir haben privat ziemlich viel zu tun.
Falls das Problem noch besteht: Ist das bei allen unseren Widgets so oder nur bei bestimmten. Welche sind das auf dem Bild?
Falls das Problem behoben ist, woran lag es?

**Comment by jkvarel** [comment]
Hallo @Flyor ,

da wir seit mehreren Tagen nichts von dir gehört haben, hoffen wir, dass das Problem behoben ist. Wenn nicht kannst du dich gerne bei uns melden :)
