### ISSUE TITLE
JSON Tab: Texte per Skript eintragen

### ISSUE THREAD

**Issue by tobe2bcon** [inventwo/ioBroker.vis-inventwo#340]
Hallo, 
ist es möglich, die Spaltenüberschrift, den vorangestellten oder nachfolgenden Text per Skript einzufügen?
So ließe sich der Inhalt der Tabelle oder einer Zeile näher spezifizieren.
Falls ja,: Hat jemand Anwendungsbeispiele?

![Screenshot_20211202_112651](https://user-images.githubusercontent.com/59087087/144404945-9f2e5e7c-c543-45fd-ba03-a8c7d1d611a6.png)

Noch ne Frage: Wo geht's zur Kaffekasse?

Grüße, Thomas

**Comment by jkvarel** [comment]
Du kannst Bindings nutzen, um Werte aus Datenpunkten einzutragen, die durch ein Skript befüllt werden. Dazu einfach den Pfad des Datenpunktes in geschweiften Klammen schreiben. Also so: {datenpunkt}

**Comment by jkvarel** [comment]
Nicht wundern. Im Editor werden Bindings nicht immer aufgelöst

**Comment by tobe2bcon** [comment]
Vielen Dank. Das werde ich testen

**Comment by tobe2bcon** [comment]
Danke nochmals. Läuft perfekt. Mit <script> war ich auf dem Holzweg. Wieder was dazugelernt.
