### ISSUE TITLE
Scrollen im Popup

### ISSUE THREAD

**Issue by Herazzer** [inventwo/ioBroker.vis-inventwo#344]
Hallo,

gibt es eine Möglichkeit im Popup-Fenster zu scrollen bzw. scrollen zu aktivieren?
Finde hier aktuell weder etwas für die X noch für die Y Achse.

Wenn hier zu viel im neuen View zu sehen ist schneidet er diesen einfach unten ab, wenn man trotzdem scrollt sieht man nur wie man im Hintergrund scrollt. Die unteren Daten im Popup lassen sich auf keine Weise einsehen.

Danke!

**Comment by jkvarel** [comment]
Mit v3.2.6 kann horizontal und/oder vertikal im PopUp gescrollt werden
![image](https://user-images.githubusercontent.com/35769746/151597991-9f129a91-3688-4ed4-a732-3808797d3b29.png)
