### ISSUE TITLE
PopUp Widget sollte gleichzeitig einen Datenpunkt setzen können

### ISSUE THREAD

**Issue by Schmakus** [inventwo/ioBroker.vis-inventwo#354]
Hi,
Wenn ein Widget als PopUp definiert ist, sollte ein gleichzeitiges Setzen eines Datenpunkts möglich sein. Aktuell ist nur eine Wahr/Falsch Anzeige möglich.
Hintergrund:
Man könnte einen Datenpunkt mit variablen Werten setzen, welche wiederum für die Widgets innerhalb des PopUp als Objekt ID, bzw. Binding innerhalb der Objekt-ID verwendet werden können.

Beispiel:
Ich setze einen Datenpunkt mit dem Wert "9". Das PopUp (View in PopUp) geht auf.
Die Widgets darin greifen dann auf folgende Objekt-ID zu (Beispiel):
javascript.0.LightControl2.**{0_userdata.0.Visualisierung.Variablen.Variable_PopUp_Zwischenspeicher}**.power
javascript.0.LightControl2.**{0_userdata.0.Visualisierung.Variablen.Variable_PopUp_Zwischenspeicher}**.ct
javascript.0.LightControl2.**{0_userdata.0.Visualisierung.Variablen.Variable_PopUp_Zwischenspeicher}**.color
...

Der Vorteil darin ist, man kann eine einzelne View für z.b. Lichtsteuerung oder Rollladensteuerung als PopUp verwenden und damit mehrere Geräte ansteuern. Alles in Abhängigkeit der Variablen.

Aktuell verwende ich dafür 2 Widgets. Eins zum Setzen der Variablen als State definiert.
Ein zweites als PopUp definiert reagiert auf den gesetzten DP und Öffnet das PopUp.

**Comment by jkvarel** [comment]
Wie bei einer normalen Navigation kann hier ein Datenpunkt und Wert eingetragen werden. So wird einmal das PopUp mit der View geöffnet und der Wert in den Datenpunkt geschrieben. Ich weiß nicht mehr genau mit welcher Version das drin ist aber da ist schon eine Weile möglich
![image](https://user-images.githubusercontent.com/35769746/151590888-d2db1cdb-12f6-4ff8-9f37-f480c04883e3.png)
