### ISSUE TITLE
State-Widget sollte Objekt-ID aktualisieren

### ISSUE THREAD

**Issue by Schmakus** [inventwo/ioBroker.vis-inventwo#355]
Ein State-Widget sollte eine Objekt-ID auch aktualisieren, sofern der alte Wert = dem neuen Wert ist.
Aktuell wird der Wert nur gesetzt, wenn dieser ungleich dem alten Wert ist.

Aktuell setze ich den Wert per Script wieder zurück, damit dieser erneut per Widget gesetzt werden kann.

**Comment by skvarel** [comment]
Das ist beim State so gewollt. Es ist ein einfacher Taster, der nur einen Wert pushen kann.

**Comment by Schmakus** [comment]
🤦🏻‍♂️ mein Fehler. Ich hatte das "Problem" nicht anhand des Datenpunkts ausgemacht, sondern weil das PopUp-Widget nicht auf die Aktualisierung regierte!

Demnach wäre dies nun gelöst. 🙈😂

Aber ist es gewollt, dass das PopUp Widget nur auf Änderung eine DP reagiert, um das PopUp zu öffnen? Meiner Meinung nach sollte es auch auf die Aktualisierung eines DP reagieren.
