### ISSUE TITLE
Navigation Button wird nicht aktiv

### ISSUE THREAD

**Issue by scooty99** [inventwo/ioBroker.vis-inventwo#36]
Wenn man einzelne Views programmtechnisch aktiviert (über vis.0.control.command), dann wird der betreffende inventwo Navigation Button nicht aktiv und ändert auch nicht seine Farbe.

**Comment by jkvarel** [comment]
Hallo scooty99,

hab ich behoben. Ist im Update heute im laufe des Tages mit drin.
