### ISSUE TITLE
Image Widget zeigt immer das Image für true

### ISSUE THREAD

**Issue by peterfido** [inventwo/ioBroker.vis-inventwo#361]
Image Widget zeigt immer das Image für true

Selbst, wenn ich einen Datenpunkt mit false angebe, zeigt er das Icon für true. Gebe ich eine unvollständige Objekt ID an, zeigt er es im Editor rot und (auch nach STRG F5) im View grün an.
![image](https://user-images.githubusercontent.com/63405109/148910636-79977369-f5eb-4941-b99a-6e4ff51490e9.png)

**Comment by jkvarel** [comment]
Ich hab gerade mal versucht das nachzustellen. Bei mir klappte es soweit.
Welche Version des Adapters hast du installiert?
Kannst du mir das Widget bitte einmal schicken? 
Ist der Datenpunkt ein boolean oder ein string?

**Comment by mtb-z** [comment]
Hi @jkvarel,

ich greife das hier mal auf, da ich auch irgendwie auf dem Schlauch stehe... 

Bei mir ist der Datenpunkt als boolean definiert. Obwohl der Datenpunkt auf "true" steht, sehe ich immer das Icon für "false".  
Trage ich manuell im Feld "value" z.B. "true" oder "1" ein, wird das richtige icon angezeigt.

Habe ich etwas vergessen oder falsch eingestellt? 
Der Adapter ist in Version 3.3.1 installiert.

Hier das Widget:

`[{"tpl":"i-vis-image-new","data":{"g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","iCornerRadiusUL":"0","iCornerRadiusUR":"0","iCornerRadiusLR":"0","iCornerRadiusLL":"0","iImgRotation":"0","iOpacityCtn":"1","iImgBlinkFalse":"0","iImgBlinkTrue":"0","iImgColorFalse":"#fefefe","iImgColorTrue":"#fefefe","iImgScaleType":"Normal","iImgTileSize":"","iShadowSpread":"0","iShadowSpreadInner":"0","iShadowBlur":"0","iShadowColor":"#111111","iShadowColorActive":"#111111","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"iImageTrue":"/vis-icontwo/Doors_Windows/door-closed_locked.png","iImageFalse":"/vis-icontwo/Doors_Windows/door-open.png","iImgColorInvertFalse":false,"oid":"homee.0.Homee-0.Homeegrams.396.active","iValue":"","lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0},"style":{"left":"140px","top":"140px"},"widgetSet":"vis-inventwo"}]`

**Comment by jkvarel** [comment]
Im Feld Wert muss der Wert eingetragen werden, der den true Zustand bestimmt. Heißt wenn der Datenpunkt ein boolean ist muss im Feld true oder 1 eingetragen werden. Dann wird das Bild für wahr angezeigt, wenn der Datenpunkt auf true steht.

**Comment by jkvarel** [comment]
Sollte mit Update 3.3.4 behoben sein. Ansonsten bitte nochmal melden
