### ISSUE TITLE
Open http Link

### ISSUE THREAD

**Issue by srkonus** [inventwo/ioBroker.vis-inventwo#363]
Wie im iobroker Forum angefragt, wäre es super wenn man mittels Widget einen http Link aufrufen kann. Hier der Forumseintrag:

https://forum.iobroker.net/topic/45942/vis-inventwo-v3-x-x/21?_=1642017261961

Mit der Funktion wäre es möglich zwischen verschiedenen vis (mit allen wichtigen und unwichtigen Informationen) zu wechseln. Bei Rückfragen helfe ich gerne.

**Comment by jkvarel** [comment]
Mit v3.2.6 kann, wenn als Widget Typ "HTTP" ausgewählt ist, zwischen Senden, Öffnen und Öffnen im neuem Tab ausgewählt werden 
![image](https://user-images.githubusercontent.com/35769746/151598321-9cdeec9d-7f19-4c25-b1db-e3a2b5db01ef.png)

**Comment by srkonus** [comment]
Super, vielen Dank - klappt wunderbar!
