### ISSUE TITLE
Min/Max-Werte beim Slider "Vertical"

### ISSUE THREAD

**Issue by Verblizz** [inventwo/ioBroker.vis-inventwo#366]
Hallo zusammen,

mir ist aufgefallen, dass beim "Simple Slider Vertical" beim Anzeigen der Min/Max-Werte auf beiden Seiten der Slider jeweils der Max-Wert angezeigt wird.
Version ist die 3.2.5.
Dieses passiert sowohl bei neu angelegten Slidern und ist auch bei allen in meiner VIS plötzlich der Fall...

![Slider](https://user-images.githubusercontent.com/97833593/149659430-d793ef1a-9ba0-4524-b663-925ceef1fcf8.PNG)

**Comment by jkvarel** [comment]
Hab den Fehler gefunden und behoben. Am Wochenende kommt ein offizielles Update. Du kannst, wenn du willst, die Änderungen aber schon von GitHub ziehen.
