### ISSUE TITLE
Simple Slider Farbe der Schritte

### ISSUE THREAD

**Issue by Linustrispoke** [inventwo/ioBroker.vis-inventwo#369]
Die Textfarbe der Schritte kann nicht verändert bzw. konfiguriert werden .

![grafik](https://user-images.githubusercontent.com/46529635/149771715-b97044ec-ab0c-4303-9c25-c1b1e36be7b6.png)

**Comment by jkvarel** [comment]
Die Farbe kannst du bei CSS Font & Text ändern 
![image](https://user-images.githubusercontent.com/35769746/150146690-43c29b50-34a7-4eee-ae7d-c3bb4365d441.png)

**Comment by Linustrispoke** [comment]
Hallo Jannis,
dem muss ich wiedersprechen, zumindest bei mir funktioniert es nicht.

![grafik](https://user-images.githubusercontent.com/46529635/150165508-bc2fd1e3-5471-4297-b6eb-baa148042b25.png)

Die Farbe von CSS Text & Color ersetzt die Farbe von Text / Farbe im Widget.
font-style und font-weight aus CSS Text & Color werden übernommen.

**Comment by jkvarel** [comment]
Welches Thema hast du ausgewählt? Habe gerade festgestellt, dass einige die Farben überschreiben. Redmond funktioniert bei mir 
![image](https://user-images.githubusercontent.com/35769746/150410606-cc61c188-781d-4b01-89f8-a3ac862bb3a6.png)

**Comment by jkvarel** [comment]
Sollte mit Update 3.3.4 behoben sein. Ansonsten bitte nochmal melden
