### ISSUE TITLE
ioBroker.vis-icontwo

### ISSUE THREAD

**Issue by Emphantom4d** [inventwo/ioBroker.vis-inventwo#37]
Hallo. Ich verstehe nicht, wo ich den Ordner mit den Dateien für den Broker ablegen soll. hat die zip-datei heruntergeladen und was soll ich damit machen?

https://github.com/inventwo/ioBroker.vis-icontwo

**Comment by sigi2345** [comment]
Adapter über Git installieren und dann mit + eine Instanz hinzufügen.
![Screenshot (2501)](https://user-images.githubusercontent.com/41079106/82198311-690f1c80-98fc-11ea-9517-985786db7b3e.png)

**Comment by Emphantom4d** [comment]
Icon set fehlt.

**Comment by skvarel** [comment]
@Emphantom4d  .. ja, das stimmt! Das ist auch so in der Wiki erklärt. Wir haben seit gestern einen extra Icon Adapter erstellt -> vis-icontwo

Dort werden in Zukunft alle Icons zur Verfügung stehen.

**Comment by Emphantom4d** [comment]
Hallo.  ja danke.  Ich hoffe zu sehen.  Danke.  sehr schöne.

пн, 18 мая 2020 г., 19:51 skvarel <notifications@github.com>:
