### ISSUE TITLE
Externe Webseite öffnen 

### ISSUE THREAD

**Issue by kaschperle83** [inventwo/ioBroker.vis-inventwo#375]
Hallo,
mir fehlt die Möglichkeit eine externe Webseite über eines der Widgets direkt zu öffnen. Könnte man das noch implementieren?

Grüße

**Comment by jkvarel** [comment]
Ein Issue dazu existiert bereits. Siehe https://github.com/inventwo/ioBroker.vis-inventwo/issues/363
