### ISSUE TITLE
Berechung in datetime

### ISSUE THREAD

**Issue by DerDoubleD** [inventwo/ioBroker.vis-inventwo#376]
Hallo
Ich lese eine JSON aus einer Webseite aus dort kommt der Zeitstring zu ungenau, genauer gesagt 3 Stellen zu kurz.
Beispiel: Ist: 1643180400 => Soll: 1643180400000
Kann ich die Zahl im datetime-feld vorher *1000 rechnen? Dann würde die Anzeige stimmen.

**Comment by jkvarel** [comment]
Besteht das Problem mit der neusten Version noch? Ab der 3.2.6 wird bei 10-stelligen Zeitstempeln automatisch noch 3 Nullen hinzugefügt

**Comment by jkvarel** [comment]
Falls das Problem noch besteht bitte neu öffnen
