### ISSUE TITLE
Fix icon on repo too ;-)

### ISSUE THREAD

**Issue by ldittmar81** [inventwo/ioBroker.vis-inventwo#38]
https://github.com/ioBroker/ioBroker.repositories/blob/57049cc4a09ff5f5cba2a4444772742b7659a205/sources-dist.json#L1541

**Comment by jkvarel** [comment]
Oh yes. Thank you. I forgot that it has to be changed too. :D

**Comment by jkvarel** [comment]
Added the change to the  pull request for our new adapter
