### ISSUE TITLE
JSON Tables causing issues with latest update 3.2.6

### ISSUE THREAD

**Issue by beef76** [inventwo/ioBroker.vis-inventwo#387]
**Describe the bug**  
JSON content will not be shown anymore after update from 3.2.5 to 3.2.6

**Screenshots & Logfiles**  
screenshot of the working and not working tables and also the JSON content attached

**Versions:**  
 - Adapter version: 3.2.6
 - JS-Controller version: 3.3.22
 - Node version: v12.22.8
 - Operating system: Debian

![Zwischenablage015](https://user-images.githubusercontent.com/59502459/151834504-b7fedc23-308c-4403-8d93-5b7eddbb7672.jpg)
![Zwischenablage016](https://user-images.githubusercontent.com/59502459/151834607-ef153852-6c65-465c-9254-c66f8cdbe5be.jpg)
[JsonExample2.txt](https://github.com/inventwo/ioBroker.vis-inventwo/files/7972492/JsonExample2.txt)
[JsonExample1.txt](https://github.com/inventwo/ioBroker.vis-inventwo/files/7972493/JsonExample1.txt)

**Comment by jkvarel** [comment]
Hallo @beef76,

der Text in den Dateien ist kein JSON. Das sind kommagetrennte Werte. Bist du sicher, dass du das richtige geschickt hast?

**Comment by beef76** [comment]
Hi Jannis
du hast natürlich vollkommen recht, es ist gar keine JSON bzw. der DP hat keinen JSON formatierten Inhalt, sondern Kommagetrennte Werte.
Das komische ist halt, dass in der vorherigen Version die Anzeige in der VIS mit dem inventwo JSON widget nocht problemlos funktioniert hat und mit der letzten Version halt nicht mehr.
Das Script was dahinter steckt ist dieses hier (screenshot). Es generiert halt eine Liste, Komma-getrennt immer mit dem link zum grün oder rot icon und der jeweiligen Info zum DP der über die Funktion "reachable" ausgelesen wird (das gleiche hab ich noch für Fensterkontakte ob offen oder zu usw.)
Man müsste hier sicher das Script so umbauen dass er die Werte im JSON Format in den DP schreibt, den man dann in der VIS wiederum aufruft über euer Widget. 
Aber trotzdem komisch, dass es bislang funktioniert hat und nur seit dem letzten Update nicht mehr, oder?
VIele Grüße
Björn
![Zwischenablage014](https://user-images.githubusercontent.com/59502459/152245768-81ff6452-ea9e-44cb-a27f-80aad1bcf5af.jpg)

**Comment by beef76** [comment]
hab mein script umgebaut dass eine JSON erstellt wird anstatt einer komma getrennten Liste und alles funktioniert mit der neusten Adapter Version. Ich schließ dann mal das issue ;-)

**Comment by wackelfinger** [comment]
hallo @beef76 ich habe selbes problem. kannst du mir sagen wie du dein blockly umgebaut hast dass es wieder funktioniert? danke und gruß
