### ISSUE TITLE
Request: Lichtgruppen

### ISSUE THREAD

**Issue by n3ucr0n** [inventwo/ioBroker.vis-inventwo#39]
Hallo Entwicklerteam,

leider kenne ich mich mit den "Verhaltensweisen" von GritHub nicht aus, daher hoffe ich, dass dies der richtige Ort ist. Falls nicht, bitte einfach löschen / verschieben.

Die Iconsammlung hat sich in der letzten Zeit massiv weiterentwicklet und ich würde gerne in meiner VIS ein Icon verwenden, welches eine Lichtergruppe darstellt.

Also quasi die "Standard" Glühbirne (an sowie aus) nur dann mehrere kleine auf einem Icon.

Ist es möglich, ein solches Icon zu erstellen und der Bibliothek hinzuzufügen?

Danke und liebe Grüße

**Comment by skvarel** [comment]
@n3ucr0n 

Es gibt einen weiteren Adapter von uns. Dort findest Du alle Icons.

vis-icontwo ..... zur Zeit leider nur über GitHub und npm zu installieren. Wir warten noch auf die Aufnahme in die ioBroker Adapterliste.

Gruß, Sven.

**Comment by skvarel** [comment]
@n3ucr0n 

Ja, das ist kein Problem. Setze ich um und mache die Tage ein Update. Allerdings kommen die Icons in unseren Icon Adapter 'vis-icontwo' und nicht in den 'vis-inventwo' Adapter

https://github.com/inventwo/ioBroker.vis-icontwo

Gruß, Sven.

**Comment by n3ucr0n** [comment]
Klasse, danke!

**Comment by skvarel** [comment]
Einverstanden?

![grafik](https://user-images.githubusercontent.com/1114419/84241990-80f34e00-ab00-11ea-9dea-4edf0e421f68.png)

**Comment by n3ucr0n** [comment]
Sehr cool! Danke! 
(Ich für meinen Teil werde mir die Icons noch drehen, aber das kann man ja sehr einfach selber machen).

Überhaupt möchte ich mien Lob für die ganzen Icons im vis-icontwo aussprechen. Habe ich gestern Abend installiert und mal etwas gestöbert, richtig klasse!

**Comment by skvarel** [comment]
Das Drehen kommt noch als Funktion in unsere Widgets. Dann lassen sich ALLE Icons nach Wunsch drehen ;)

**Comment by skvarel** [comment]
> 
> 
> Sehr cool! Danke!
> (Ich für meinen Teil werde mir die Icons noch drehen, aber das kann man ja sehr einfach selber machen).
> 
> Überhaupt möchte ich mien Lob für die ganzen Icons im vis-icontwo aussprechen. Habe ich gestern Abend installiert und mal etwas gestöbert, richtig klasse!
