### ISSUE TITLE
bitte alignment für überschriften einpflegen (json)

### ISSUE THREAD

**Issue by liv-in-sky** [inventwo/ioBroker.vis-inventwo#394]
bitte im json widget das aligment (links rechtsbündig) bei den überschriften der spalten einpflegen - siehe https://forum.iobroker.net/post/756504

ps: super widget - oft in gebrauch !!!

**Comment by liv-in-sky** [comment]
danke dir - habe erst jetzt zeit

frage: wenn ich einen spaltennamen eingebe, funktioniert es - wenn ich den standardd lasse und den namen aus dem json nehme, funktioniert es nicht

isst soweit ok für mich - muss ich halt einfach benennen - ist das so gewollt

**Comment by jkvarel** [comment]
Du meinst das Feld "Attribut in JSON"? Im Normalfall funktioniert es ohne da was einzutragen. Was mir bisher aufgefallen ist, dass man es bei ical machen muss. Weiß nicht warum die Reihenfolge manchmal durcheinander ist
