### ISSUE TITLE
switch schaltet nicht

### ISSUE THREAD

**Issue by SteffenPWH** [inventwo/ioBroker.vis-inventwo#40]
Das Schalten eines in homee eingebundenen Schalters funktioniert nicht.
Die Farbe des buttons wechselt auf die aktiv-Farbe, aber der Schaltvorgang erfolgt nicht.
Schalte ich die selbe Lampe mit einem anderen switch, dann ändert sich auch die Farbe des inventwo-switches.

Schalten mit dem "Standard-Switch" (bulb) aus vis funktioniert einwandfrei.

**Comment by jkvarel** [comment]
Hallo @SteffenPWH , 
wird der Datenpunkt nicht geändert? Kannst du das mal prüfen? Also gucken ob der Wert in den Datenpunkt geschrieben wird?
Welche Version des Adapters nutzt du?

**Comment by jkvarel** [comment]
Kannst du dir mal den Log angucken ob dort Fehler auftauchen? Das Problem kam schon mal vor und da lag es am Homee Adapter

**Comment by SteffenPWH** [comment]
> Hallo @SteffenPWH ,
> wird der Datenpunkt nicht geändert? Kannst du das mal prüfen? Also gucken ob der Wert in den Datenpunkt geschrieben wird?
- wenn ich per homee-App schalte, ändert sich der Datenpunkt fast sofort von 0 auf 1 und umgekehrt.
![image](https://user-images.githubusercontent.com/66113312/84407693-78d40500-ac0b-11ea-931e-3181736f9a80.png)


> Welche Version des Adapters nutzt du?

homee 0.3.1 
auf meinemSystem lässt sich nichts neueres installieren 
(nodejs.10.20.2, js-controller 2.2.9, npm 6.14.4.
inventwo 1.3.3.)

**Comment by SteffenPWH** [comment]
> Kannst du dir mal den Log angucken ob dort Fehler auftauchen? Das Problem kam schon mal vor und da lag es am Homee Adapter

ja, da ist was ... :)
![image](https://user-images.githubusercontent.com/66113312/84408365-51ca0300-ac0c-11ea-9593-063edc1d1de3.png)

**Comment by SteffenPWH** [comment]
> > Kannst du dir mal den Log angucken ob dort Fehler auftauchen? Das Problem kam schon mal vor und da lag es am Homee Adapter
> 
> ja, da ist was ... :)
> ![image](https://user-images.githubusercontent.com/66113312/84408365-51ca0300-ac0c-11ea-9593-063edc1d1de3.png)
> 
> hab einmal per widget an und aus geschaltet (also 2x drauf geklickt)

im widget lässt sich ja nur "boolean" oder "value" einstellen, keine Zahl oder Wert (0/1)
könnte es daran liegen? :)

**Comment by SteffenPWH** [comment]
im homee-adapter, einstellungen zu dem Datenpunkt des Schalters,
unter "RAW" findet sich folgendes:
![image](https://user-images.githubusercontent.com/66113312/84411208-83dc6480-ac0e-11ea-88c1-44516efe2db9.png)

**Comment by jkvarel** [comment]
@SteffenPWH , sollte mit der 1.3.8 (latest) behoben sein. Ich prüfe jetzt intern ob es sich um eine Zahl handelt und schreibe sie dann auch als Zahl in den Datenpunkt. Vorher wurde die Zahl als Text geschrieben
