### ISSUE TITLE
Slider Einstellungen

### ISSUE THREAD

**Issue by michad2** [inventwo/ioBroker.vis-inventwo#41]
Hallo,
Ich würde bei den Slidereinstellungen Schrittweiten um 0,1 und Einstellung der Zahlenwerte auch im Nachkommabereich benötigen.
Hintergrund : Ich habe bei meinem Trommelfilter eine Düsendrucküberwachung eingebaut, die ist momentan einstellbar zwischen 6.5 und 7.0 bar. Ich könnte natürlich den Wert mit 10 multiplizieren und später wieder teilen, das wäre aber unsauber. Einen anderen Slider möchte ich aber auch nicht nehmen, soll schon alles einheitlich sein.

Danke und Gruß
Micha

**Comment by skvarel** [comment]
@michad2 .. die 0.1er Schritte kommen mit dem nächsten Update.

Gruß, Sven.

**Comment by jkvarel** [comment]
@michad2, Slider Schritte können mit der 1.3.8 (latest) jetzt Dezimalzahlen sein. Zu beachten ist, dass ein Punkt und kein Komma verwendet werden muss :)
