### ISSUE TITLE
SimpleSlider->Min/Max-Werte passen nicht

### ISSUE THREAD

**Issue by Verblizz** [inventwo/ioBroker.vis-inventwo#410]
Hallo liebes Entwickler-Team,

mir ist eben aufgefallen, dass es ein Problem beim horizontalen Min/Max-Slider gibt:
Wenn der Min-Wert nicht "0" ist, dann verschiebt sich die Skalierung merkwürdigerweise. Beim Vertikalen ist das nicht so.
Ich habe mal einen Screenshot angefügt, es sind 2 Test-Slider, beide genau gleich konfiguriert...
Installiert ist Version 3.2.8
![grafik](https://user-images.githubusercontent.com/97833593/155582619-739853c0-bb63-45ee-8e93-ef9973994208.png)

**Comment by jkvarel** [comment]
Hallo @Verblizz 

Habe den Fehler gefunden. Bitte mit der nächsten Version einmal testen

**Comment by Verblizz** [comment]
Hallo @jkvarel,

habe eben die 3.3.1 über npm installiert, der Bug ist gefangen...;)
Vielen Dank!
