### ISSUE TITLE
Eingestellter Wert im RGB-Slider bleibt nicht konstant

### ISSUE THREAD

**Issue by uwe72** [inventwo/ioBroker.vis-inventwo#411]
Der mit dem Color-Slider eingestellte Wert wird zwar 1:1 an die Lampe übertragen, aber im Anschluss wird im Slider was komplett anderes dargestellt. Ich verwender das CIE Farbschema in Verbindung mit dem deCONZ-Adapter.

Für mich sieht dies nach einem Fehler aus.

https://user-images.githubusercontent.com/61848539/155819277-33754141-8a46-49f7-bb43-49b7bc3e28e3.mp4

**Comment by jkvarel** [comment]
Sollte mit v3.3.0 behoben sein. Außerdem bietet die Version einen Colorpicker, mit dem auch Sättigung und Helligkeit eingestellt werden kann

**Comment by uwe72** [comment]
Danke dir! Habe es schon mitbekommen über Facebook. 

Hatte es damals nur testweise ausprobiert. BIn aktuell noch bei Jarvis. Werde aber mittelfristig auf inventwo zurückkommen bzw. zu inventwo wechseln.

Sehr gute Arbeit!! VG
