### ISSUE TITLE
CSS für Scrollbalken

### ISSUE THREAD

**Issue by BernhardLinz** [inventwo/ioBroker.vis-inventwo#418]
Ich nutze das Widget "JSON Table". Dabei ist mir aufgefallen das CSS Anweisungen für die Scrollbar ignoriert werden.

Ich habe folgende CSS Klasse erstellt:
`
.myscrollbar::-webkit-scrollbar-track {
  background: rgba(51, 51, 51, 0.5);
}
.myscrollbar::-webkit-scrollbar-thumb {
  background: rgba(19, 179, 236, 0.5);
  border-radius: 5px;
  border: 1px solid #000000;
}
`
und dem Widget zugewiesen

Im VIS-Editor sehen dann die in diesem Fall blauen und breiteren Scrollbalken,
beim Aufruf des Projektes im Browser sind es jedoch wieder die normalen, grauen

Ich habe `overflow-x: visible` eingestellt

**Comment by jkvarel** [comment]
Stimmt doch nicht ganz. Beim Universal- und Multi-Widget setze ich die Klassen nicht. Beim Tabellen Widget schon. Ich gucke weiter und melde mich

**Comment by jkvarel** [comment]
Siehe https://stackoverflow.com/questions/61814935/webkit-scrollbar-thumb-not-working-in-chrome-81

Man muss vorher noch auf das gleiche Element ::-webkit-scrollbar stylen

So funktioniert es z.B. bei mir
.myscrollbar::-webkit-scrollbar {
    background:transparent;
} 
.myscrollbar::-webkit-scrollbar-track {
    background: rgba(51, 51, 51, 0.5); 
    
} 
.myscrollbar::-webkit-scrollbar-thumb {
    background: rgba(19, 179, 236, 0.5); 
    border-radius: 5px; 
    border: 1px solid #000000; 
    
}

**Comment by BernhardLinz** [comment]
Jupp, so geht es! Danke für die Lösung.
Da es bei anderen Dingen so funktioniert hatte bin ich nicht auf die Idee kommen danach zu suchen ob es an etwas anderen liegen kann
