### ISSUE TITLE
Wahr Falsch bei Multi und Universal

### ISSUE THREAD

**Issue by Ostseeskipper** [inventwo/ioBroker.vis-inventwo#425]
Hallo,
die Universal und Multis sind echt schon sehr vielseitig.
Wenn man diese jedoch als Navigationstabs einsetzen will funktioniert leider keine Prüfung.
Es gibt ja die Unterteilung falsch / wahr. Nur die Prüfung scheint nicht zu funktionieren.

![grafik](https://user-images.githubusercontent.com/101480124/158256252-ef29e9db-9c73-499d-b2c3-729bda042e50.png)

Würde gern den Rahmen je nach Zustand wahr/falsch farblich setzen.
Falls es kein Bug sein soll, dann bitte in Anfrage/Issue schieben.
Danke und viele Grüsse von der Küste

**Comment by jkvarel** [comment]
Das Feld Objeckt ID bei Navigation ist nicht zum Prüfen. Damit kannst du gleichzeitig einen Datenpunkt steuern, wenn du die View wechselst. 
Wenn du die View wechseln möchtest und gleichzeitig einen Datenpunkt abfragen, dann musst du das Multiwidget nehmen und unten bei den Zuständen "Prüfe auf" auf "Datenpunkt Wert" stellen. Dann kannst du navigieren und einen Datenpunkt abfragen 
![image](https://user-images.githubusercontent.com/35769746/158423616-1aa24d47-b0c8-4205-8deb-dfc316d47f1b.png)

**Comment by Ostseeskipper** [comment]
Hallo Jannis,
ohh besten Dank, werde ich gleich mal so ausprobieren.
Viele Grüsse von der Küste 
Andreas

    Am Dienstag, 15. März 2022, 17:18:35 MEZ hat Jannis ***@***.***> Folgendes geschrieben:  
 
 


Das Feld Objeckt ID bei Navigation ist nicht zum Prüfen. Damit kannst du gleichzeitig einen Datenpunkt steuern, wenn du die View wechselst.
Wenn du die View wechseln möchtest und gleichzeitig einen Datenpunkt abfragen, dann musst du das Multiwidget nehmen und unten bei den Zuständen "Prüfe auf" auf "Datenpunkt Wert" stellen. Dann kannst du navigieren und einen Datenpunkt abfragen


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ostseeskipper** [comment]
Hallo Jannis

Hmm und wo stelle ich die Rahmenfarbe je nach Prüfung ein? 
Das gibts da ja gar nicht.Ich mag die tollen schmalen Rahmen und der soll je nach Zustand eine andere Farbe bekommen so das ich weiss ob es sich lohn hinzuklicken.Dicke Farbe auf großflächige Icons mag ich nicht.

    Am Dienstag, 15. März 2022, 17:18:35 MEZ hat Jannis ***@***.***> Folgendes geschrieben:  
 
 


Das Feld Objeckt ID bei Navigation ist nicht zum Prüfen. Damit kannst du gleichzeitig einen Datenpunkt steuern, wenn du die View wechselst.
Wenn du die View wechseln möchtest und gleichzeitig einen Datenpunkt abfragen, dann musst du das Multiwidget nehmen und unten bei den Zuständen "Prüfe auf" auf "Datenpunkt Wert" stellen. Dann kannst du navigieren und einen Datenpunkt abfragen


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ostseeskipper** [comment]
OK, ich glaube das nun verstanden zu haben wo und wie ich das einstellen muss.
Finde die Anordnung der Einstellungsmöglichkeit im Universal Widget durchdachter
![grafik](https://user-images.githubusercontent.com/101480124/158891726-278c2432-53ed-478b-a4c4-a286ff79cc0e.png)
Nice to have. Danke

**Comment by jkvarel** [comment]
Beim Multi Widget sind die allgemeinen und für Falsch die Einstellungen. Alles was mit dem Wahr Zustand zu tun hat muss in den jeweiligen Zuständen eingestellt werden. Heißt sämtliche Farben können pro Zustand anders sein

**Comment by jkvarel** [comment]
Ich denke Problem ist behoben? Ansonsten gerne wieder öffnen oder neues Issue speziell zum neuen Problem aufmachen.
