### ISSUE TITLE
Farbe der Umrandung beim View in Popup wechselt nicht

### ISSUE THREAD

**Issue by fal-ke** [inventwo/ioBroker.vis-inventwo#426]
Ich verwende ein Multi-Widget vom Typ View in Popup um einen Dimmer zu schalten. Dabei wird die Umrandung des Widgets entsprechend dem Zustand des Dimmers farblich dargestellt.

Nun habe ich das Verhalten, dass beim Einschalten des Dimmers die Farbe sofort gewechselt wird, beim Ausschalten hingegen nicht. Gleichzeitig wechselt das Bild und die Beschriftung korrekt. Am Zustand des Dimmers kann es also nicht liegen.

Wird ein Refresh des Browsers durchgeführt, wechselt dann die Farbe der Umrandung.

Das Problem besteht nur bei View in Popup und nur bei der Umrandung. Sobald ich das Widget als Background benutze, funktioniert es korrekt. Auch funktioniert es korrekt, wenn ich statt der Umrandung die Hintergrundfarbe wechsle.

Die Adapter-Version ist die 3.3.1.

**Comment by jkvarel** [comment]
Fehler gefunden. Bitte mit der nächsten Version ausprobieren

**Comment by fal-ke** [comment]
Klappt, vielen Dank!
