### ISSUE TITLE
Switch schaltet fälschlicherweise hin und her

### ISSUE THREAD

**Issue by linchen4000** [inventwo/ioBroker.vis-inventwo#45]
Hi,

am PC per Mausklick klappt es gut mit dem hin und herschalten durch einen switch einer Variable (true/false).
Am Tablet (Android 7.1) jedoch wird bei einem Klick doppelt geschaltet. Die Variable steht auf true und wechselt durch einen Touchklick auf false und dann direkt wieder auf true nach bis auf wenige Millisekunden genau immer einer Sekunde.

Wie kann ich das Problem lösen?
Meine Idee wäre ein Script zu schalten, durch welches eine Veränderung eines Wertes durch den Switch immer nur möglich ist, sobald die letzte Änderung mehr als 1,5 Sekunden her war. Damit würde ich diese Doppelsprünge vermeiden. Evtl. habt ihr auch noch eine Idee, ob das am Adapter liegen könnte, oder tatsächlich an mir. Wird evtl der Touchklick als zwei Klicks interpretiert, weil er so "lange" ist? Hm.

Viele Grüße und danke für den Adapter :)

**Comment by jkvarel** [comment]
Hallo @linchen4000 , das Problem ist uns neu. Bekannt ist es mir nur bei den Buttons. Da wird bei machen Geräten der Wert 2x gepusht. Ich konnte das Problem aber noch nicht finden.
Wir nutzen den Switch bei am PC, Tablet mit Android (ich weiß gerade nicht welche Version, ist aber eine ältere als 7) und Smartphones (Android 10) und haben das Problem nicht.
Der Touchklick wird eigentlich nur als ein Klick interpertiert. Beim länger halten verhält sich das Skript nicht anders, als wenn du einmal schnell drauf tippst.

Welche Datenpunkte schaltest du damit? Ist das bei allen Datenpunkten so? Sind das deine eigenen oder von einem Adapter? Hast du Skripte laufen, die den Wert eventuell ändern könnten?

Viele Grüße und danke das du unseren Adapter nutzt ;)

**Comment by LapsusK** [comment]
Hallo jkvarel, zunächst mal danke für den Adapter, top Design und gute Funktionen im Widget für VIS!
Das Problem bei den Buttons kann ich bestätigen, bei den Switches allerdings nicht.
Mit den Buttons steuere ich das WebOS (Adapter lgtv V1.1.10) meines LG-Fernsehers. Bei Channel Up/Down schaltet er mir auch 2 Channels hoch bzw runter, unabhängig wie lange ich den Button betätige. Komischerweise beim ersten click auf den Button nicht. Alle weiteren clicks werden dann doppelt ausgeführt. Vielleicht hilft das ja etwas bei der Fehlersuche...
Viele Grüße Lapsus

**Comment by Flyor** [comment]
Ich kann das Problem bei den Switches zeitweise bestätigen - ich schalte mit einem Switch die Klimaanlage aus und ein (Datenpunkt des Adapters), welche jede Änderung akustisch bestätigt. In den meisten Fällen ist die Rückmeldung korrekt, es kommt jedoch auch vor dass die Rückmeldung doppelt kommt. Sozusagen Schaltvorgang von false auf true und dann noch ein true hinterher. Das Phänomen tritt aber nicht immer auf und im allgemeinen eher selten, wenn es aber gerade "akut" ist, dann bei jeder Schaltfolge...

**Comment by jkvarel** [comment]
Ich konnte das Problem reproduzieren und hab vermutlich den Fehler behoben.  Bei mir wird der Wert nun nicht mehr 2x gesetzt. 

Ich werde heute Abend ein Update in die latest schieben

**Comment by jkvarel** [comment]
v2.3.0 (latest) in online

Das Problem sollte ab dieser Version behoben sein. Wenn es doch wieder auftauchen sollte dann bitte bei uns melden. Danke :)
