### ISSUE TITLE
Color-Picker-Widget "verschwindet" bei Auswahl von CIE

### ISSUE THREAD

**Issue by markusk1407** [inventwo/ioBroker.vis-inventwo#455]
Hallo!
Wenn ich beim "großen" Color-Picker-Widget CIE auswähle, "verschwindet" das Widget, d.h. der Auswahlrahmen bleibt, aber der Farbkreis und aller Slider sind weg.

LG
Markus

**Comment by derTillus** [comment]
Der Colorpicker ist genau das, wonach ich gesucht habe. 
Leider habe ich das gleiche Problem. Installierte Version V3.3.3. Problem ist browserunabhängig Firefox, FullyKiosk und Edge. 

LG

**Comment by jkvarel** [comment]
Wenn kein Datenpunkt ausgewählt ist verschwindet das Widget. Es sollte sichtbar sein wenn ein Datenpunkt mit einem validen Wert ausgewählt ist. Könnt ihr das bestätigen? Falls nicht, könnt ihr mir bitte den Wert aus dem Datenpunkt schicken?

**Comment by jkvarel** [comment]
Sollte mit Update 3.3.4 behoben sein. Ansonsten bitte nochmal melden

**Comment by Michael12555** [comment]
Hallo, ich bin neu hier auf der Platform. Ich habe das gleiche Problem. Die Version ist 3.3.5.

<img width="1448" height="28" alt="Image" src="https://github.com/user-attachments/assets/3f30ef41-e3cb-43de-877e-275dbbb5cf6b" />

Habt ihr eine Idee woran das liegen könnte?

**Comment by HaraldGrhein** [comment]
Ich habe auch das gleiche Problem. Auch Version 3.3.5
Node.js v22.21.0
NPM 10.9.4
js-controller 7.1.0
