### ISSUE TITLE
JSON Table does not show updated values when Table Object ID is changed

### ISSUE THREAD

**Issue by Marty56** [inventwo/ioBroker.vis-inventwo#457]
An Update of the Table Object ID does not update the JSON Table in the visualisation.
(Unacceptable)) Workaround is to reload the browser page.

**Comment by jkvarel** [comment]
Hi, does the problem still exists? I tried it but its working.
Please let me know how do you update the value.

**Comment by jkvarel** [comment]
Is yes, please  reopen issue
