### ISSUE TITLE
Beschriftung und Bild für "Wahr" und "Falsch" sind vertauscht.

### ISSUE THREAD

**Issue by senger1985** [inventwo/ioBroker.vis-inventwo#46]
Beim dem Unversal-Switch werden die Beschriftungen und die Bilder, für "Wahr" und "Falsch" angezeigt. V2.1.0

**Comment by jkvarel** [comment]
Hallo @senger1985 

Vertauscht? Kannst du mir Bilder schicken? Ich konnte das bei mir nicht nachstellen

**Comment by senger1985** [comment]
![state](https://user-images.githubusercontent.com/35745035/92411040-8e8f9280-f146-11ea-8a4b-979f952185d6.PNG)
Wenn der WidgetTyp auf "State" eingestellt ist, werden die Werte vertauscht.
Dann wird z. B.: das Bild für "Wahr", bei dem Zustand "Falsch/false" angezeigt, bei der Beschriftung das selbe Verhalten.
Wenn allerdings der WidgetTyp auf "Switch" eingestellt ist, sind die Werte wieder richtig.

**Comment by jkvarel** [comment]
Der State prüft nicht auf ein Zustand. Der State ist ein Taster. Damit kannst du einem DP immer nur den gleichen Wert geben. Daher wird immer Bild und Beschriftung falsch angezeigt.
Wenn du die Rückmeldungsdauer erhöhst, dann bekommst du beim Klick eine kurze Rückmeldung (Bild und Beschriftung Wahr), damit du siehst, dass du gedrückt hast

**Comment by senger1985** [comment]
Dann habe ich das falsch interpretiert.
Danke für die Erklärung.

**Comment by jkvarel** [comment]
Kein Problem :)
