### ISSUE TITLE
Doppelauslösung Taster/state und "slider lässt sich nicht "sliden bei Windows Touch

### ISSUE THREAD

**Issue by Critit** [inventwo/ioBroker.vis-inventwo#461]
Hallo ich benutze eure widgets sehr gern, leider habe ich ein problem unter Windows Touchscreen

Wenn ich auf ein Widget drücke das auf "State" steht dann wird der Taster zweimal gedrückt. 
Wenn ich an meinem Android Handy bediene löst es nur einmal aus,
und wenn ich es mit Maus Bediene ebenfalls. 
ich hab das an meinem Windows Tablet in der Wand probiert und auch mit meinem Surface Pro 7, bei beiden das gleiche verhalten 

und das zweite Problem was ich bemerkt habe das ich ich den slider nicht mit dem Finger ziehen kann, also auf eine bestimmte stelle drücken geht dann beweget er sich aber den "Knopf" ziehen geht nicht, wie bei den Tastern geht das bei Android und mit Maus aber nicht auf meinem Wand Tablet und meinem Surface.

Der Slider von Material Widget lässt sich in Windows mit dem Finger "sliden"

Die Sachen wurden jeweils mit dem Edge Browser und dem Chrome Browser getestet, bei Firefox nicht aber kann ich auf Wunsch noch gerne Testen

Mit freundlichen Grüßen

Marcel (Critit)

Edit. Version ist die aktuelle 3.3.1

**Comment by jkvarel** [comment]
Sollte mit Update 3.3.4 behoben sein. Ansonsten bitte nochmal melden
