### ISSUE TITLE
Probleme mit den Schaltern

### ISSUE THREAD

**Issue by RBausOL** [inventwo/ioBroker.vis-inventwo#47]
Hallo

Ich habe ein Problem mit den Schaltern (Switch).
Ich benutze Homee und bekomme bei Lichtschaltern mit eurem Widget meine Lampen nicht aus.

homee.0 (4585) homee connection error: "value must be a number"

Ich habe den TYP auf "Wert" geändert und bei Wert falsch und Wert wahr 0 und 1 eingetragen aber er schaltet die Lampen nur an. An Homee der ähnlichem kann es nicht liegen da alle anderen Schalter im ioBroker und die Schalt-versuche im ioBroker über "Objekte" problemlos laufen.
Ich hoffe ihr könnt mir helfen, ich komme einfach nicht weiter.

Liebe Grüße

**Comment by jkvarel** [comment]
Hallo @RBausOL 

schade dass das Problem wieder auftaucht. Das gab es schon einmal und da lag es am Homee Adapter. Aber wenn es mit anderen Widgets funktioniert?

Ich guck mal ob ich den Beitrag finde und ob ich was im Code finde

**Comment by jkvarel** [comment]
Ich konnte den Beitrag dazu nicht finden und finde so auch keinen Fehler im Code. Die Werte werden, wenn es Zahlen sind, auch als Zahlen in  die Datenpunkte geschrieben.

Besteht das Problem immer noch?

**Comment by jkvarel** [comment]
Geschlossen aufgrund keiner Rückmeldung,

Besteht das Problem weiterhin? Wenn ja, dann gerne ein neues Issue aufmachen oder im ioBroker Forum melden :)
