### ISSUE TITLE
json Tabelle mit "Binding"

### ISSUE THREAD

**Issue by Farmer-cb** [inventwo/ioBroker.vis-inventwo#474]
Hallo
die json-Tabelle zeigt den Fehler "No or wrong data in datapoint" wenn in der Opject-ID ein binding eingesetzt wird.

**object-id: 0_userdata.0.Fingerprint.Protokoll.{0_userdata.0.Fingerprint.Protokoll.monat_jetzt}** funktioniert nicht,
**object id: 0_userdata.0.Fingerprint.Protokoll.2022.07** funktioniert.

da ich das eigentlich schon länger so nutze, hat es auch schon mal funktioniert

**Comment by jkvarel** [comment]
Sollte mit Update 3.3.4 behoben sein. Ansonsten bitte nochmal melden
