### ISSUE TITLE
ios 12 "View in Popup" not Display

### ISSUE THREAD

**Issue by rabbit6984** [inventwo/ioBroker.vis-inventwo#477]
**Describe the bug**  
On ipad with ios in safari or iobroker vis app the view in popup show empty grey backround and not the configured content of the view

On the Computer in MS Edge Chromium works it fine

**Versions:**  
 - Adapter version: 3.3.3
 - JS-Controller version: 4.0.23
 - Node version: 16.16.0
 - Operating system: raspberrypi iobroker client ipad ios 12

i don`t found a error in the iobroker logs

i hope i filled out anything correct

**Comment by jkvarel** [comment]
Does the problem still exists?
I checked it on an iPad with safari and the view in popup works as designed.
The reason why it's not working with the ioBroker app could be because the current version is not in the app.

**Comment by jkvarel** [comment]
Problem still exists? If so  just reopen the issue
