### ISSUE TITLE
Unsichtbarer Knopf nicht unsichtbar bei fullybrowser

### ISSUE THREAD

**Issue by cavernerg** [inventwo/ioBroker.vis-inventwo#489]
**Describe the bug**  
Ein unsichtbarer inventwo Universal Button wird in Fullybrowser dennoch angezeigt. 

**To Reproduce**  
0. add universal button
1. Go to "CSS Allgemein"
2. Click on opacity and set to 0 %
3. Open vis in firefox - button is invisible
4. Open vis in fullybrowser - button is visible

**Expected behavior**  
Der Button sollte in beiden Browsern unsichtbar sein 

**Screenshots & Logfiles**  
Je ein Screenshot aus firefox und fully

**Versions:**  
 - Adapter version: 3.3.1
 - JS-Controller version: 4.0.23
 - Node version: 16.17.0
 - Operating system: ubuntu 22.04 lxc

**Additional context**  

![grafik](https://user-images.githubusercontent.com/62744005/188707269-7ff0bc5e-e675-4247-a788-381970b6bb79.png)
![grafik](https://user-images.githubusercontent.com/62744005/188707288-0e997360-c8b5-425f-bc3a-3a07c1ec631a.png)

**Comment by jkvarel** [comment]
Bitte benutze diese Einstellung für die Transparenz
![image](https://github.com/inventwo/ioBroker.vis-inventwo/assets/35769746/46048e9a-97d1-45d6-9b3c-902fa654f66a)
