### ISSUE TITLE
Wert runden

### ISSUE THREAD

**Issue by seers84** [inventwo/ioBroker.vis-inventwo#504]
Hi,

gibt es eine Möglichkeit einen Zahlenwert zu runden?
Ich hab es mit binding und round versucht.
Bei beiden leider kein Erfolg.

Waschmaschine<br>{sourceanalytix.0.tuya__0__213076019c9c1f84e282__5.currentYear.consumed.01_currentDay;round(2)} kWh/d

Waschmaschine<br>{sourceanalytix.0.tuya__0__213076019c9c1f84e282__5.currentYear.consumed.01_currentDay;round} kWh/d

Ursprung:
![image](https://user-images.githubusercontent.com/87387550/195174780-a2202433-99ed-4cb7-8620-12e97f8b7dc5.png)
Ergebnis:
![image](https://user-images.githubusercontent.com/87387550/195174880-6208b50e-ca91-4ddb-88cc-edbb906e1720.png)

Mach ich was falsch? Bitte um Hilfe
Gruß
Reiner

**Comment by jkvarel** [comment]
Schaue dir am besten diese Seite an. Da findest zu viele Informationen zum Thema Bindings: https://www.machs-smart.de/iobroker-bindings-farben-berechnungen-abfragen/

Mit ;round(2) sollte es klappen.
