### ISSUE TITLE
Probleme beim Zugriff auf Vis über die Cloud

### ISSUE THREAD

**Issue by peterredl** [inventwo/ioBroker.vis-inventwo#516]
When accessing my vis remotely via the cloud adapter, I get the following errors.

cloud.0
216247 2022-11-02 09:07:10.843 Fehler Webseiten können nicht angefordert werden: Datei widgets/vis-inventwo/set/icons/socket.png nicht gefunden: {}

cloud.0
216247 2022-11-02 09:07:02.415 Fehler Unbekannter Befehl 1 empfangen: Name

In the LAN I can access my Vis without any problems.

**Comment by jkvarel** [comment]
The file widgets/vis-inventwo/set/icons/socket.png does not exists in the adapter. I don't know why you get the error. There are no icons in this adapter. We have a separate icon adapter: https://github.com/inventwo/ioBroker.vis-icontwo

**Comment by jkvarel** [comment]
If not already solved, please refere to the cloud adapter. I think I can't help you
