### ISSUE TITLE
Widget Image mit mehr als zwei Zuständen und Icons Möglich?

### ISSUE THREAD

**Issue by New-three** [inventwo/ioBroker.vis-inventwo#519]
Im Widget Image habe ich die Möglichkeit Zustände anhand zwei Icons darzustellen.
Das klappt auch wunderbar.

Nun habe ich ein Garagentor das mir 4 Zustände ausgibt. 
Gibt es eine Möglichkeit diese über das Image Widget darzustellen?
Im Grunde müsste die Anzahl der Bilder und Zustände verdoppelt werden.

**Comment by jkvarel** [comment]
Du könntest dafür das Multi-Widget nehmen. Dort kannst du den Hintergrund transparent machen und so viele Zustände definieren wie du möchtest.

**Comment by jkvarel** [comment]
Wie in meinem vorherigen Kommentar erwähnt, das Multi-Widget eignet sich dafür sehr gut. Ich denke ein neues Widget oder Anpassung am Image Widget ist nicht notwendig.
Falls etwas mit dem Multi Widget im Vergleich zum Image Widget nicht möglich ist gerne melden. Aber eigentlich müsste mit dem Multi sogar mehr möglich sein.
