### ISSUE TITLE
Temperatur-Picker-Widget

### ISSUE THREAD

**Issue by OlfrygtACAB** [inventwo/ioBroker.vis-inventwo#536]
moin moin zusammen,
ich weiss nicht ob es das schon irgendie gibt,
ist es möglich einen slider wie den Color-Picker-Widget darzustellen, nur nicht bunt sondern von kalt bis warmweiss

**Comment by jkvarel** [comment]
Du meinst sowas?
![image](https://github.com/inventwo/ioBroker.vis-inventwo/assets/35769746/57976215-aed6-4d66-993d-7d159ec5ee70)
Du kannst bei dem Color Picker einstellen welche "Kanäle" du verändern möchtest.
![image](https://github.com/inventwo/ioBroker.vis-inventwo/assets/35769746/b816ec09-01bf-4c04-9085-69e13eac3038)
