### ISSUE TITLE
"View in popup" not working when viewing HTML

### ISSUE THREAD

**Issue by Horgul123** [inventwo/ioBroker.vis-inventwo#563]
Widget Version 3.3.3., tested on Windows and  Android

I have an universal widget.
When it's displaying a camera stream via HTML iFrame a klick does not open the popup.
When I delete the HTML in "Beschriftung falsch" it works fine, insert the html again it's not working.
Text to display:
`<iframe style="transform-origin: 0px 0px 0px; transform: scale(0.7); width: 640px; height: 480px;" src="http://192.168.0.253:8089" name="iFrame" scrolling="no"></iframe>`

![2023-04-16_12-08-38](https://user-images.githubusercontent.com/45976162/232317197-9d1278e1-458c-4caa-a0a1-ff06d9dbbfcd.png)

**Comment by jkvarel** [comment]
It's not working because you interacting with the content of the iframe. Add the following style to the iframe: 
pointer-events: none;
