### ISSUE TITLE
Radiobutton - Bildfarbe true wird von false übernommen

### ISSUE THREAD

**Issue by bloop16** [inventwo/ioBroker.vis-inventwo#564]
Guten Tag,
Ich Suche nach einer Möglichkeit bei den Radiobuttons für die Bildfarbe true keine Änderung vorzunehmen. Allerdings übernimmt er mir immer die Farbe aus dem false Wert. 
Gibt es hier Abhilfe?

Herzlichen Dank!

**Comment by jkvarel** [comment]
Sollte mit Update 3.3.4 behoben sein. Ansonsten bitte nochmal melden
