### ISSUE TITLE
vis-inventwo Universal Switch um Popup-Windows anzusteuern: Funktioniert nicht in vis-2

### ISSUE THREAD

**Issue by MichaelSchaaf999** [inventwo/ioBroker.vis-inventwo#578]
**Describe the bug**  
Über Datenpunkte zum Öffnen/Schließen von PopUp-Views wird in vis-1 mit Universal Switch gesteuert, wann die PopUp-Views erscheinen und wieder verschwinden müssen.
In vis-2 funktioniert das nicht mehr: Es passiert gar nichts.

**To Reproduce**  
Aufruf eines Menüeintrags, der den Datenpunkt setzt: In vis-1 erscheint dann die im Universal-Switch verknüpfte View, in vis-2 erscheint gar nichts.

**Expected behavior**  
Funktion des Universal Switch wie in vis-1: PopUp-Views können getriggert werden.
Unsere iOBroker-Visualisierung arbeitet an vielen Stellen mit PopUp-Informationen (Steuerungshilfen bei der Eingabe, auch Fehlermeldungen usw) und benötigt die PopUp-Funktion dringend.

**Screenshots & Logfiles**  
n.a.

**Versions:**  
 - Adapter version: 3.3.3
 - JS-Controller version: 5.0.8  
 - Node version: 18.16.1 
 - Operating system: Debian 10 (?) in Proxmox VM

**Additional context**  
-

**Comment by MichaelSchaaf999** [comment]
any idea of a timeframe when this issue will be solved?

**Comment by MichaelSchaaf999** [comment]
any idea? Reminder.

**Comment by jkvarel** [comment]
Wann kann ich nicht sagen. Um viele Probleme zu beheben muss ein neuer Adapter entwickelt werden. Den Adapter Vis2 kompatible zu bekommen wird nicht klappen

**Comment by MichaelSchaaf999** [comment]
Gibt es denn einen Workaround mit bspw einem anderen Adapter, der dann dies Feature auch unterstützt, neu in VIS2? Frage auch an bspw @Apollon77

**Comment by MichaelSchaaf999** [comment]
> Gibt es denn einen Workaround mit bspw ein anderes Widget, das dann dies Feature auch unterstützt, neu in VIS2? Frage auch an bspw @Apollon77

any idea? Reminder.

**Comment by Apollon77** [comment]
Sorry, ich kann zu Vis nicht wirklich helfen

**Comment by vowill** [comment]
> > Gibt es denn einen Workaround mit bspw ein anderes Widget, das dann dies Feature auch unterstützt, neu in VIS2? Frage auch an bspw @Apollon77
> 
> any idea? Reminder.

Ich habe an anderer Stelle auch schon die Frage gestellt, ob es eine Art "Übersetzung" der Einträge in der Datei vis-views.json von vis-1 auf vis-2 geben könnte. Auf dieser Ebene dürfte ein händischer Eingriff bei verbleibenden Inkompatibilitäten vermutlich auch schneller und einfacher sein als im vis-2-Editor.
(Aufgrund der tollen Funktionen der inventwo-WIdgets habe ich diese in meiner vis-1 mehr als 900 mal verwendet. Da wird ein Umstieg auf vis-2 schwierig ...)

**Comment by MichaelSchaaf999** [comment]
> Sorry, ich kann zu Vis nicht wirklich helfen

Gut, trotzdem danke für den Hinweis, @Apollon77 Ingo. 
Inventwo-VIS2 ist ja jetzt im Test, das ist dann wieder Licht am Ende des Tunnels. ;-) 
Frage: Wenn man vor Monaten schon mal testweise auf VIS2 war mit seinen Projekten...  wie geht man gescheit vor, wenn man in VIS2 alles "auf Null" setzen will, also seine alten Migrationen dort alle wegwerfen will und neu aus VIS1 kommend in die VIS2 migrieren möchte? 
Gibt es da eine Anweisung irgendwo?

**Comment by MichaelSchaaf999** [comment]
> ...(Aufgrund der tollen Funktionen der inventwo-WIdgets habe ich diese in meiner vis-1 mehr als 900 mal verwendet. Da wird ein Umstieg auf vis-2 schwierig ...)

@vowill Richard: Gibt es da wohl irgendwo eine abrufbare Statistik in VIS(1), die zeigt, wieviele und welche Widgets man im Projekt verwendet hat? Quasi eine Cross-Reference...

**Comment by vowill** [comment]
> > ...(Aufgrund der tollen Funktionen der inventwo-WIdgets habe ich diese in meiner vis-1 mehr als 900 mal verwendet. Da wird ein Umstieg auf vis-2 schwierig ...)
> 
> @vowill Richard: Gibt es da wohl irgendwo eine abrufbare Statistik in VIS(1), die zeigt, wieviele und welche Widgets man im Projekt verwendet hat? Quasi eine Cross-Reference...
Wie an anderer Stelle schon geschrieben: Habe den Inhalt von vis-views.json aus dem Editor kopiert nach Excel und dort gefiltert nach Zeilen mit dem Inhalt "inventwo".

**Comment by MichaelSchaaf999** [comment]
> > Wie an anderer Stelle schon geschrieben: Habe den Inhalt von vis-views.json aus dem Editor kopiert nach Excel und dort gefiltert nach Zeilen mit dem Inhalt "inventwo".
Ah, danke, das hatte ich wohl "überlesen" nach dem Motto "von json hab ich eh keine Ahnung".
Ich denke mal: Das ist eine Parameterdatei. Wo findet man die wohl im System? Ich hab da leider keine Ahnung.

**Comment by vowill** [comment]
> > > vis-views.json ... > > > Ich denke mal: Das ist eine Parameterdatei. Wo findet man die wohl im System? Ich hab da leider keine Ahnung.
Leicht finden lässt sich diese Datei im Backup unter "iobroker_2024_04_yy-xx_xx_xx_backupiobroker\backup\files\vis.0" (nach dem Extrahieren der tar.gz-Datei). Dort hat jedes vis-Projekt einen eigenen Unterordner, in dem jeweils eine Datei "vis-views.json" liegt. Das Öffnen gelingt z. B. mit dem normalen Windows-Editor.

**Comment by MichaelSchaaf999** [comment]
>> Leicht finden lässt sich diese Datei im Backup unter "iobroker_2024_04_yy-xx_xx_xx_backupiobroker\backup\files\vis.0" (nach dem Extrahieren der tar.gz-Datei). Dort hat jedes vis-Projekt einen eigenen Unterordner, in dem jeweils eine Datei "vis-views.json" liegt. Das Öffnen gelingt z. B. mit dem normalen Windows-Editor.

Ah: Sehr cool und vielen vielen Dank.
Ich benutze den Backup-Adapter seit März nicht mehr, weil ich ihn nicht brauche und er nur Overhead ist.
Aber: Habe gefunden, dass man im VIS-edit ja unter Setup ein ganzes Projekt exportieren kann (was ich sonst schon lange nicht mehr genutzt habe). In der exportierten zip-Datei kann man dann auch suchen und zählen bis man schwindelig wird.
Ich selbst habe nach Zählung dann dort "nur" 652 vis-inventwo widgets: Aber auch das reicht ja schon, um bei der Migration zu VIS2 sehr sehr zurückhaltend zu sein.
Dir nochmal herzlichen Dank!

**Comment by jkvarel** [comment]
Der Adapter ist nicht mit VIS 2 kompatible und wird es nie sein. Ein neuer ist in Arbeit: https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo

**Comment by MichaelSchaaf999** [comment]
Danke sehr!
