### ISSUE TITLE
JSON Table Widget: Farbänderung der Werte via Schwellwert ist nur im Editor, nicht in Runtime sichtbar.

### ISSUE THREAD

**Issue by DokoBlock** [inventwo/ioBroker.vis-inventwo#580]
**Describe the bug**  
ich möchte in einer Tabelle Daten wiedergeben und die Daten aufgrund ihrer Inhalte farblich hervorheben.
Dazu bietet das Widget die Möglichkeit, wenn eine Spalte als "number" formatiert ist, einen Schwellwert-Formatierung zu hinterlegen, entweder direkt im Widget eingegeben oder aus einem Datenpunkt ausgelesen.
Die Darstellung im Editor sieht korrekt aus (Farben werden korrekt gewählt), bei der Darstellung dann später in der Runtime selbst (nicht mehr im Editor) sind die Farben nicht sichtbar.

**To Reproduce**  
1. create JSON with some numeric values
2. show JSON in JSON widget of vis-inventwo
3. set format of each table row to number
4. create a datapoint that contains a JSOn structure with the Schwellenwerte
5. colour of shown data should change according to Schwellwerte in editor
6. when showing the table in the runtime, to colour is not chosen but remains default.

**Expected behavior**  
the chosen colour Schwellwerte should also apply when data is shown in runtime

**Screenshots & Logfiles**  
Widget Property:
![Pic1](https://github.com/inventwo/ioBroker.vis-inventwo/assets/127679005/0d6d183d-bdc9-4f15-bebd-957b222aff7e)

Editor Ansicht:
![Pic2](https://github.com/inventwo/ioBroker.vis-inventwo/assets/127679005/97fbfe2d-5a4e-486b-84b3-920018511d4a)

Runtime Ansicht:
![Pci3](https://github.com/inventwo/ioBroker.vis-inventwo/assets/127679005/a836e02a-2cab-44aa-8f3e-c16cc9679871)

**Versions:**  
 - Adapter version: vis 1.4.16, vis-inventwo 3.3.3
 - JS-Controller version: 4.0.24
 - Node version: 18.17.0
 - Operating system: Linux Mint 20.3

**Additional context**

**Comment by jkvarel** [comment]
Sollte mit Update 3.3.4 behoben sein. Ansonsten bitte nochmal melden
