### ISSUE TITLE
VIS2 - Universal Widget - different evaluation of boolean

### ISSUE THREAD

**Issue by AndrewSteel** [inventwo/ioBroker.vis-inventwo#584]
**Describe the bug**  
Universal Widgets: The Object_ID's of type boolean are evaluated differently depending on the widget type.
For Switch and Background TRUE==TRUE for all other types TRUE==FALSE.

**To Reproduce**  
* Universal Widget
* Object-ID: of Type boolean
* Type: boolean
* Widget-Type: choose a Type
* Evaluation of boolean depends on Widget-Type

**Expected behavior**  
All Widget-Type should evaluate TRUE as TRUE and FALSE as FALSE

**Versions:**  
 - Adapter version: 3.3.3
 - vis-2-beta version: 2.1.5
 - JS-Controller version: 4.0.24
 - Node version: 16.9.1
 - Operating system: linux 6.1.21-v8+

**Comment by jkvarel** [comment]
Can you tell me which type does not behaves correctly?
The only type which should have the same behaviour is "background"

State: Has no true/false state. It's a  push button,
Navigation: State depends on view.
Increase or decrease value: Like state.
View in Popup. Just opens a Popup.
HTTP: Does not have an object id.

**Comment by jkvarel** [comment]
The adapter is not compatible for VIS 2 and won't be in the future. A new is being worked on: https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo
