### ISSUE TITLE
Nur lesend - Eigenschaft ?

### ISSUE THREAD

**Issue by mjfuchs71** [inventwo/ioBroker.vis-inventwo#60]
Hallo,
ich möchte gerne einen "Switch-Small" benutzen um die Zustände bestimmter "BOOLEANS" anzuzeigen.
Leider finde ich diese Eigenschaft nicht.
Wie kann ich einen Switch ähnlich wie bei BULB in "Allgemein" auf nur lesend stellen ?

Danke und Gruß 
Matthias

**Comment by jkvarel** [comment]
@mjfuchs71 , um Datenpunkte nur auszulesen gibt es die Background Widgets.

Aber der v2.0.0 gibt es das Universal und Multi Widget. Dort kann der Typ (Switch, State, Nav, Background) ausgewählt werden. Für dich wäre dann Background interessant

**Comment by mjfuchs71** [comment]
Werde ich gleich mal ansehen. Vielen Dank für Deine Antwort 😊

Von meinem iPhone gesendet

**Comment by jkvarel** [comment]
@mjfuchs71 , ich geh mal davon aus, dass alles geklappt hat. Wenn nicht dann einfach ein neues Issue aufmachen :)
