### ISSUE TITLE
Bindings funktionieren nicht richtig

### ISSUE THREAD

**Issue by jkvarel** [inventwo/ioBroker.vis-inventwo#601]
Bindings in Feldern wie z.B. Hintergrundfarbe werden zwar angewendet aber wenn sich der Wert ändert aktualisiert sich das Widget nicht.

**Comment by Duese123** [comment]
Ich habe dasselbe Problem. Das komische ist zb bei einem Symbol mit veränderter Farbe wird manchmal die Farbe überschrieben und das geladene Binding (Text) zeigt manchmal null beim aktualsieren

alles OK
![image](https://github.com/inventwo/ioBroker.vis-inventwo/assets/95966691/42b28dd5-ce23-4d44-b73c-9e17ccd6ca32)

manchmal kein binding Text 
![image](https://github.com/inventwo/ioBroker.vis-inventwo/assets/95966691/4f0d730f-b3d4-454d-8690-4978cde76bf8)

manchmal Hintergrundfarbe vom Symbol anders

**Comment by jkvarel** [comment]
Der Adapter ist nicht mit VIS 2 kompatible und wird es nie sein. Ein neuer ist in Arbeit: https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo
