### ISSUE TITLE
JSON Table undefined

### ISSUE THREAD

**Issue by sigi2345** [inventwo/ioBroker.vis-inventwo#603]
**!!! Before you start !!!!**  
Verify if there is not already an issue requesting the same vis 2 issue

**Describe wanted Enhancement !**  

JSON Table undefined

**Additional context**  

![Screenshot (316)](https://github.com/inventwo/ioBroker.vis-inventwo/assets/41079106/9aa53a8a-d378-46ec-bedb-755df43befa8)

**Comment by skvarel** [comment]
Der Adapter ist nicht VIS2 kompatibel und wird er auch nie werden. Eventuell wird es einen vis2-inventwo geben. Ob und wann er kommen wird, ist aber noch unklar.

**Comment by sigi2345** [comment]
> Der Adapter ist nicht VIS2 kompatibel und wird er auch nie werden. Eventuell wird es einen vis2-inventwo geben.

VIS2-Inventwo wäre Super!

**Comment by jkvarel** [comment]
Der Adapter ist nicht mit VIS 2 kompatible und wird es nie sein. Ein neuer ist in Arbeit: https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo
