### ISSUE TITLE
Simple Slider horizontal Schritte 

### ISSUE THREAD

**Issue by sigi2345** [inventwo/ioBroker.vis-inventwo#604]
**!!! Before you start !!!!**  
Verify if there is not already an issue requesting the same vis 2 issue

**Describe wanted Enhancement !**  
Simple Slider horizontal Schritte nur  0 oder 100
Edit:
Alle Slider betroffen!

**Additional context**  

![Animation_vis2_schritte](https://github.com/inventwo/ioBroker.vis-inventwo/assets/41079106/ea51cda0-c9aa-478b-a1d0-753b7188a358)

**Comment by JockelBln** [comment]
Die Farbe der Schritte lässt sich auch nicht ändern. Trotz Einstellung auf "weiß" sind sie bei dunklem Hintergrund nicht sichtbar.
Unter VIS-1 konnte man das an dieser Stelle ändern.
![image](https://github.com/inventwo/ioBroker.vis-inventwo/assets/56645688/791f4173-6492-4289-8d46-21f9754a896f)
![image](https://github.com/inventwo/ioBroker.vis-inventwo/assets/56645688/9a14077b-dfc3-4a44-bfa5-e37fd06dfe99)

**Comment by skvarel** [comment]
Der Adapter ist nicht VIS2 kompatibel und wird er auch nie werden. Eventuell wird es einen vis2-inventwo geben. Ob und wann er kommen wird, ist aber noch unklar.

**Comment by jkvarel** [comment]
Der Adapter ist nicht mit VIS 2 kompatible und wird es nie sein. Ein neuer ist in Arbeit: https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo
