### ISSUE TITLE
Palette Widgets doppelt?

### ISSUE THREAD

**Issue by sigi2345** [inventwo/ioBroker.vis-inventwo#609]
**Describe wanted Enhancement !**  

In der Palette werden einige Widgets anscheinend doppelt installiert.

**Additional context**  

![Screenshot (319)](https://github.com/inventwo/ioBroker.vis-inventwo/assets/41079106/5a32e301-7477-40d3-9120-0fcb1a8d3887)

**Comment by skvarel** [comment]
Der Adapter ist nicht VIS2 kompatibel und wird er auch nie werden. Eventuell wird es einen vis2-inventwo geben. Ob und wann er kommen wird, ist aber noch unklar.

**Comment by jkvarel** [comment]
Da sind keine Widgets doppelt. Die Widgets unten sind die alten aus der Version 1 des Adapters und haben teilweise die gleichen Namen wie die neuen. Werden mal bei einem Update rausfliegen.
![image](https://github.com/inventwo/ioBroker.vis-inventwo/assets/35769746/76eeb247-d110-448b-9c55-a51510259ea3)
