### ISSUE TITLE
Buttons auf "halber Höhe" nicht mehr verwendbar

### ISSUE THREAD

**Issue by Flyor** [inventwo/ioBroker.vis-inventwo#61]
Ich hab früher immer mit großer Freude die "halbhohen" Buttons verwendet. Meistens mit Text und Bild. Seit den letzten Updates, sterben diese wohl aus. Leider. 

Ich habe versucht die neue Schaltfläche per Hand auf die Höhe von 50px anzupassen, das klappt. Allerdings bekomm ich nun Bild und Text nicht mehr auf eine Ebene. Ich kann es zwar mit den Reglern verschieben, allerdings wird Bild UND Text gleichermaßen verschoben, egal ob ich den Regler für Text oder für Bild verwende. Im Bild noch die alten halbhohen Widgets, das neue (das aktiv bearbeitet wird) mit dem besagten Problem. Es ist entweder der Text oder das Bild nicht mehr innerhalb des Buttons. 

![inv](https://user-images.githubusercontent.com/64526892/95365116-f960f480-08d1-11eb-8259-7e2c84fd134f.jpg)

**Comment by jkvarel** [comment]
Hallo @Flyor 

Das kannst du mit den neuen Widgets ganz leicht umsetzen

![image](https://user-images.githubusercontent.com/35769746/95484364-ac902300-0990-11eb-9e4a-94ae97a3095d.png)
Oberes Widget:
![image](https://user-images.githubusercontent.com/35769746/95484422-bca80280-0990-11eb-9ec2-160d24ca4910.png)
Unteres Widget
![image](https://user-images.githubusercontent.com/35769746/95484464-caf61e80-0990-11eb-9cc0-9953f5d5ca28.png)

**Comment by Flyor** [comment]
@jkvarel Danke!! Ich hatte nahezu alle Felder ausprobiert, aber Stil hab ich anscheinend übersehen. Mit Stil horizontal funktioniert es bestens, so wie es damals mit den halbhohen standardmäßig war.
