### ISSUE TITLE
Slider funktionieren auf android touchscreens nicht

### ISSUE THREAD

**Issue by phipsi99** [inventwo/ioBroker.vis-inventwo#618]
Describe the bug
Ich habe einen Simple-Slider genutzt. Mit Maus funktioniert alles wie es soll. Am Smartphone (Mehrerer Browser und Samsung-Modelle getestet) kann man den Slider nicht ziehen. Nur klicken funktioniert.
Mit slidern aus anderen adaptern funktioniert es Problemlos, daher vermute ich ein bug in diesem Adapter und kein Problem des Browsers/Geräts.

To Reproduce

View mit Slider erstellen
View auf Android Gerät öffnen
Versuchen den Slider zu ziehen
Expected behavior
Sollte sich wie mit der Maus ziehen lassen

Versions:

Adapter version: v3.3.3
JS-Controller version: 5.0.12
Node version: v18.18.2
Operating system: docker

**Comment by mlapp** [comment]
Die Slider funktionieren bei mir sowohl auf dem Handy (Xiaomi) als auch einem Androidtablett absolut problemlos. 
Der Wert lässt sich sich sowohl durch antippen als auch ziehen ändern.

**Comment by phipsi99** [comment]
Ok, merkwürdig. Ich nutze auch den fullybrowser, dann kann man das ja schonmal ausschließen. 
Ich nutze vis 2.3.2, Problem ist nicht die Funktionalität an sich, sondern nur das sliden per touchscreen (in den slider klicken funktioniert, den slider ziehen nicht)

**Comment by jkvarel** [comment]
Die Widgets funktionieren nicht zu 100% mit Vis 2. Die einen mehr als die anderen. Daher kann es zu Problemen kommen.

**Comment by skvarel** [comment]
> Ok, merkwürdig. Ich nutze auch den fullybrowser, dann kann man das ja schonmal ausschließen. Ich nutze vis 2.3.2, Problem ist nicht die Funktionalität an sich, sondern nur das sliden per touchscreen (in den slider klicken funktioniert, den slider ziehen nicht)

Der Adapter ist nicht VIS2 kompatibel und wird er auch nie werden. Eventuell wird es einen vis2-inventwo geben. Ob und wann er kommen wird, ist aber noch unklar.
