### ISSUE TITLE
Anwendungsdauer und Verweildauer erklären

### ISSUE THREAD

**Issue by Aare07** [inventwo/ioBroker.vis-inventwo#62]
Ich habe bisher keine Anwendungsbeschreibung für die Felder im Multi State Verweildauer  / Anzeigedauer gefunden.
Ich versuche folgendes zu realisieren:
Wenn der Status eines Datenpunktes nur kurz true wird soll dies 10 Sekunden lang angezeigt werden, auch wenn der Datenpunkt schon wieder false ist.
(Sonnerie Knopf nur kurz gedrückt, in VIS Multistate soll 10 Sekunden lang das entsprechende Bild angezeigt werden)

Ausserdem sind diese Felder nicht pro Zustand separat sondern nur pro Widget global einstellbar?
Bewusst? Anwendungsfall wäre z.B. dass beim Eintreffen eines Alarmwertes dies eine Stunde lang angezeigt wird, restliche jedoch ohne Verzögerung angezeigt werden.

Oder verstehe ich Verweildauer / Anzeigedauer falsch?
Danke für die genialen Widgets

**Comment by jkvarel** [comment]
Hallo @Aare07 

Die Verweildauer ist beim Universal und Multi Widget nur für den State (wird bei den anderen auch automatisch ausgeblendet)
Der State setzt nur einen Wert in einen Datenpunkt. Damit man auch eine Rückmeldung beim klicken bekommt, kann man die Verweildauer erhöhen, damit der Button z.B. kurz in einer anderen Farbe aufleuchtet

**Comment by Aare07** [comment]
Danke !
Anregung: Dies in die Anleitung aufnehmen?
