### ISSUE TITLE
Multi-widget dosn´t open PopUp

### ISSUE THREAD

**Issue by bourton88** [inventwo/ioBroker.vis-inventwo#623]
Hallo,
bei mir funktioniert die Funktion "ViewInPopup" des Multi-Widgets in VIS2 nicht. Wenn ich mit dem Browser Inspektor schaue was passiert wenn ich auf das Widget klicke, steht dort eine Fehlermeldung "renderView not implemented: Popup Popup false"

Ich habe Vis1 und Vis2 auf die gleiche weise getestet. Vis1 funktioniert, Vis2 funktioniert nicht.

Ich habe auch unterschiedliche Browser (Chrome, Firefox, Fully) getestet, aber all emit dem gleichen negativem Ergebnis

**To Reproduce**  
1. Gehe zu Vis2 Editor
2. Erstelle "Multi"-Widget
3. Stelle Widget auf "ViewInPopup" um
4. Wähle View die erscheinen soll
5. Starte Runtime
6. See Error

**Screenshots & Logfiles**  
![grafik](https://github.com/inventwo/ioBroker.vis-inventwo/assets/64092936/ed5e8a2c-8944-4c36-9dd5-f4e5fccce60e)

**Versions:**  
 - Inventwo design widgets Adapter version: 3.3.3
 - Vis 2 Adapter version: 2.9.5
 - JS-Controller version: 5.0.17
 - Node version: v18.19.0
 - Operating system: docker

**Comment by tomtom791** [comment]
Hallo, ich habe das selbe Problem

**Comment by skvarel** [comment]
Der Adapter ist nicht VIS2 kompatibel und wird er auch nie werden. Eventuell wird es einen vis2-inventwo geben. Ob und wann er kommen wird, ist aber noch unklar.
