### ISSUE TITLE
Keine Bilddarstellung bei den Widgets

### ISSUE THREAD

**Issue by Sefina-DS** [inventwo/ioBroker.vis-inventwo#625]
Hi zusammen,

Beim VIS-2 sind alle Naviagtions- Widget ohne Bilder.
Ich hinterlege hochgeladene Bilder und es werden sie nicht angezeigt (immer nur ein Platzhalter)

MfG

**Comment by skvarel** [comment]
Der Adapter ist nicht VIS2 kompatibel und wird er auch nie werden. Eventuell wird es einen vis2-inventwo geben. Ob und wann er kommen wird, ist aber noch unklar.

**Comment by skvarel** [comment]
Der Adapter ist nicht VIS2 kompatibel und wird er auch nie werden. Eventuell wird es einen vis2-inventwo geben.

**Comment by jkvarel** [comment]
Der Adapter ist nicht mit VIS 2 kompatible und wird es nie sein. Ein neuer ist in Arbeit: https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo
