### ISSUE TITLE
Radio-button-list not useable

### ISSUE THREAD

**Issue by Rudi-Ment** [inventwo/ioBroker.vis-inventwo#675]
I take a radio-button-list from the right menue and pull it on my vis2-page.
Then i change the button-number to six and the six buttons are there - OK.

Now, when i make some changes in the values on the details of the single buttons, the hole list is not more displayed.
When i throw away the changes in the single buttons, the list  is displayed again.

I want to create a button-list for my shutters, with 0 %, 20 %, 40 % and so on.

**Comment by jkvarel** [comment]
This adapter is not compatible with VIS 2 and won't be in the future. A new for VIS 2 is being worked on: https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo
