### ISSUE TITLE
Colorpicker kein Farbauswahlfenster mehr bei Update von Version 1.2.0 auf 2.0.3

### ISSUE THREAD

**Issue by tomtom791** [inventwo/ioBroker.vis-inventwo#676]
Hallo, ich habe das Problem, das nach der Aktualisierung vom "color picker style Widgets" von Version 1.2.0 auf Version 2.0.3 kein Farbauswahlfenster mehr erscheint.

Admin   v6.13.16
NodeJS  v18.17.1
NPM 9.6.7

Wenn ich wieder zurück auf v1.2.0 gehe, dann funktioniert alles wie es soll.

Ich habe mal in einem Forum gelesen, das es schon irgendwo ein Ticket dafür gibt, habe es aber nicht gefunden.

Falls es ein Workaround für dieses Problem gibt, wäre ich für Hilfe dankbar.

**Comment by jkvarel** [comment]
Eine Version 2.0.3 gibt es nicht. Warum eigentlich nicht auf die neuste 3.3.4?

**Comment by tomtom791** [comment]
Vielleicht bin ich auch blind oder ich bring da was durcheinander.
![Screenshot_20240506_190033_Chrome](https://github.com/inventwo/ioBroker.vis-inventwo/assets/149101634/a3428570-5354-46d1-9847-7c7b75ebdb52)

**Comment by tomtom791** [comment]
Ich glaube das gehört hier nicht rein oder ? Sorry hab mich wohl vertan .

**Comment by jkvarel** [comment]
Von diesem Adapter? Der ist nicht VIS 2 kompatibel
![image](https://github.com/inventwo/ioBroker.vis-inventwo/assets/35769746/7be7a54c-297f-4c9e-a73b-4024a47e8215)

Ein neuer ist bereits in Arbeit
![image](https://github.com/inventwo/ioBroker.vis-inventwo/assets/35769746/d99bfbd6-cf81-4627-bbd0-e7ef57c4e141)

**Comment by tomtom791** [comment]
Hallo, ja bei der Version 0.1.5 funktioniert das Popup auch noch nicht bei mir.

![image](https://github.com/inventwo/ioBroker.vis-inventwo/assets/149101634/8e66a502-ff60-4f43-8a12-8410d6385591)

**Comment by tomtom791** [comment]
Also wenn ich in Ausführen gehe, und den Button drücke passiert nichts.

Installiert ist die Version 0.1.5.  Steht jedenfalls so im Admin.

![image](https://github.com/inventwo/ioBroker.vis-inventwo/assets/149101634/6993d96c-342d-40b5-85b1-7cdd755a90d2)

**Comment by jkvarel** [comment]
Das Widget auf dem Bild ist von dem Adapter für Vis 1. 

Vis 1:
![image](https://github.com/inventwo/ioBroker.vis-inventwo/assets/35769746/c7ddc901-636b-471f-91d3-7d63cd8ed4b4)
![image](https://github.com/inventwo/ioBroker.vis-inventwo/assets/35769746/48502015-6402-40c0-a2d4-3b39589e61e9)

Vis 2:
![image](https://github.com/inventwo/ioBroker.vis-inventwo/assets/35769746/8e4cf61e-6275-476a-843d-f5af0d65fde0)
![image](https://github.com/inventwo/ioBroker.vis-inventwo/assets/35769746/86a6139a-273f-488d-832d-285298fa584c)

**Comment by tomtom791** [comment]
Alles klar, hab es gefunden vielen Dank.
