### ISSUE TITLE
Iconfarbe nur als direkter HTML # Wert möglich, nicht wie Text als {Datenpunkt}

### ISSUE THREAD

**Issue by Aare07** [inventwo/ioBroker.vis-inventwo#68]
Seit dem Update auf Adapterversion 2.4.2 (und auch schon bei 2.4.1) kann man die Iconfarbe beim Status angeben.
Ich verwende Multi als Background und Teste auf drei Stati.
Bei der neuen "Farbe wahr" funktioniert nur der direkte Wert z.B. #ffffff  und nicht wie bei anderen Feldern via Datenpunkt so {vis-inventwo.0.CSS.Text}

Hatte früher die Möglichkeit "Invert" genutzt da weisses Bild und setze nun überall Textfarbe und möchte das gerne Global im Datenpunkt ändern können.

2. Darf ich noch eine Frage Stellen:
Gibt es die Möglichkeit beim Slider die Anpassung des Wertes zu verzögern, damit der Wert erst in den Datenpunkt geschrieben wird wenn der Slider "losgelassen" wird?
Also ich setze neu, aber solange ich hin und her "Slide" wird nicht dauernd der Wert aktualisiert.  
Wäre Cool.  Oder gibts dazu irgendwo ein Script das erst dern effektiven Datenpunkt schreibt wenn x Millisekunden nicht geändert? 

Danke für Eure tolle Arbeit!
Aare

**Comment by o0shojo0o** [comment]
Hi, habt ihr schon so ungefähr eine Zeitspanne wenn dieses Feature fertig werden könnt? :)

**Comment by jkvarel** [comment]
Leider kann ich dir noch nicht sagen, wann das Feature verfügbar sein wird. Es gibt noch eine Unschönheit mit dem einfärben. Das wird ein bisschen aufwendiger.

**Comment by jkvarel** [comment]
Farbe der Icons kann nun mit der Version 2.5.9 auch per Datenpunkt geschaltet werden.
