### ISSUE TITLE
Farbe invertieren funktioniert nicht

### ISSUE THREAD

**Issue by senger1985** [inventwo/ioBroker.vis-inventwo#69]
**Describe the bug**  
Die Bilder werden seit der V2.4.2 zwar im Editor, aber nicht in der Vis invertiert angezeigt.

**Versions:**  
 - Adapter version: 2.4.3

**Comment by skvarel** [comment]
@senger1985 , die Funktion "Invertieren" ist mit der v2.4.2 rausgeflogen, da die Icons nun beliebig gefärbt werden können.

**Comment by senger1985** [comment]
Danke, habe es wohl übersehen.
Durch die Doku habe ich es gefunden.
