### ISSUE TITLE
Icon Color variiert bei gleichen Farbwert 

### ISSUE THREAD

**Issue by o0shojo0o** [inventwo/ioBroker.vis-inventwo#76]
Hi, mit der aktuellen Version 2.5.5 habe ich bei den Icons Farbverfälschungen.

Hier ein Beispiel:
![image](https://user-images.githubusercontent.com/19333515/97810322-4aff6380-1c73-11eb-951d-3bd9be579365.png)

Und auch einmal die Einstellung: 
![image](https://user-images.githubusercontent.com/19333515/97810125-df68c680-1c71-11eb-95dd-db238c041694.png)

**Comment by jkvarel** [comment]
Hab ich mir schon gedacht, dass das noch zu Problemen führt. Das Problem ist, dass die Bilder nicht wirklich in der Farbe eingefärbt werden. Das klapp leider nicht, da es keine SVGs sind. Daher bediene ich mich einem Skript, welches HEX-Codes in CSS Filter umwandelt, um Bilder einzufärben. Bei speziellen Farbe kann es dadurch zu Verfälschungen kommen. Eine Möglichkeit aktuell ist, solange ENTER zu drücken, während man das Feld ausgewählt hat. Dann werden die Filter neu generiert.

Ich guck mal ob ich eine Lösung dafür finde. Ich glaube ich hab da eine Idee. Ich melde mich hier wenn ich das Problem gelöst habe

**Comment by jkvarel** [comment]
@o0shojo0o mit der Version 2.5.9 sollte das Problem behoben sein. Beim testen bei mir hatte ich keine Farbabweichungen mehr. Bitte gebe mir bescheid, ob es bei dir jetzt auch funktioniert :)

**Comment by o0shojo0o** [comment]
So, alles probiert....  läuft super!
