### ISSUE TITLE
Slider Widget / Invert Option und Aktion erst beim "Loslassen"

### ISSUE THREAD

**Issue by KoMa1978** [inventwo/ioBroker.vis-inventwo#81]
Hallo,

ich würde das Slider Widget gerne für Rollladen nutzen. Dafür wäre es hilfreich, eine Option "Invert" zu bekommen. Dies lässt sich aktuell darüber lösen, dass man bei Ausrichtung 180 eingibt, aber schöner wäre natürlich eine Checkbox.
Hintergrund ist der, dass der Slider zu 25% nach rechts bedeutet, dass die Rollladen zu 75% geschlossen sind, zu 75% nach rechts bedeutet zu 25% gechlossen.

Dann wäre es auch klasse, wenn der Befehl an das "Objekt" erst dann abgesendet wird, wenn man die Maus los lässt, oder evtl. mit einem konfigurierbaren Delay. Andernfalls springen die Rollladen sehr nervös hin und her ...

Besten Dank

**Comment by jkvarel** [comment]
Das die Slider den Wert erst senden, wenn man los lässt wird noch gemacht. Eine Checkbox zum invertieren ist kein Problem. Werde ich mit einbauen

**Comment by Flyor** [comment]
> Hallo,
> 
> ich würde das Slider Widget gerne für Rollladen nutzen. Dafür wäre es hilfreich, eine Option "Invert" zu bekommen. Dies lässt sich aktuell darüber lösen, dass man bei Ausrichtung 180 eingibt, aber schöner wäre natürlich eine Checkbox.
> Hintergrund ist der, dass der Slider zu 25% nach rechts bedeutet, dass die Rollladen zu 75% geschlossen sind, zu 75% nach rechts bedeutet zu 25% gechlossen.
> 
> Dann wäre es auch klasse, wenn der Befehl an das "Objekt" erst dann abgesendet wird, wenn man die Maus los lässt, oder evtl. mit einem konfigurierbaren Delay. Andernfalls springen die Rollladen sehr nervös hin und her ...
> 
> Besten Dank

Sicher dass der Adapter keinen Wert á la "invert level" als Datenpunkt hat? Bei meinen Rademachern ist das so. 
![1](https://user-images.githubusercontent.com/64526892/98054352-fe668480-1e3a-11eb-86ca-5ae672e19191.jpg)

**Comment by KoMa1978** [comment]
Jupp ganz sicher ...

Homematic hat nur den Wert "Level" und da bedeutet 100% = geöffnet/ganz oben und 0% = geschlossen/ganz unten.

**Comment by jkvarel** [comment]
Invertieren und Wert erst beim loslassen senden ist in der Version 2.6.0 (latest) möglich
