### ISSUE TITLE
Multi Widget Zustand-Einstellungen fehlen

### ISSUE THREAD

**Issue by Kespri** [inventwo/ioBroker.vis-inventwo#82]
Die Idee mit den multiplen Möglichkeiten von den Widgets gefällt mir sehr, daher dachte ich mir, ich werde eine weitere Visualisierung eröffnen und bin noch gespannt was kommt mit den weiteren Updates - Macht weiter so!
Nun zu meinem Problem:

![VIS](https://user-images.githubusercontent.com/51025431/98091604-eec05d80-1e85-11eb-8c4b-53e4fe33c72c.png)

Bei dem Multi-Widget fehlen Einstellungsmöglichkeiten bei den Zuständen [1-x]. Zur Zeit kann man nur die Objekt-ID und den Wert setzten. Wenn dann dieser Wert zutrifft, werden die Standardwerte überschrieben, welche auf die ich nicht zugreifen kann, aber wohl Hinterlegt sind (Hintergrund: Grün und Shadow: Dunkel) - siehe Bild.
Die Zustände sind so aber leider nicht brauchbar und hoffe die Einstellungsmöglichkeiten kommen zurück?

**Comment by jkvarel** [comment]
Hallo @Kespri , die Einstellungen sind nicht wirklich weg. Sie sind nur ausgeblendet. Klicke mal bitte auf den kleinen Button rechts neben Zustand[0], Zustand[1] usw. 
Dann sind die Einstellungen zu sehen.

**Comment by Kespri** [comment]
Oh, mein Fehler, das habe ich voll übersehen. Die Einstellungen tauchen auf, wenn man auf den Aufklapp-Button klickt! Danke für den Hinweis.

**Comment by jkvarel** [comment]
Super das es bei dir klappt :)
