### ISSUE TITLE
Universal - True/False funktioniert nicht richtig

### ISSUE THREAD

**Issue by Kespri** [inventwo/ioBroker.vis-inventwo#83]
Beim Universal Widget sind mehrere Bugs aufgetaucht

1.) Beim Widget Typ Navigation:
Wird die Farbe Aktiv beim Shadow beim Seitenwechsel nicht mit geändert, erst nach einem manuellen reload der Seite, hat der aktive Button die Farbe Aktiv übernommen, aber nicht beim Wechsel selber.

2.) Beim Widget Typ State:
Wenn man den State auf eine Lampe triggert bleibt der "Wert" wohl auf false, den die Farben Aktiv wird nicht übernommen.

-> Bei den Widget Typen Switch und Background funktioniert es, sind aber auch die einzigen Widget Typen, welche ein zusätzliches Feld "Typ" haben und zwischen boolean und value wählen können.

**Comment by jkvarel** [comment]
1) Ich hab den Fehler gefunden. Ist im nächsten Update behoben

2) Der Widget Typ "State" ist nicht dazu da den Status z.B. einer Lampe zu zeigen. Der State ist dazu da um immer wieder nur den gleichen Wert zu senden. Daher wechselt die Farbe nicht. Du kannst den für einen Moment aufblinken lassen, damit du weißt dass du geklickt hast, indem du den Wert "Rüchkmeldungsdauer" erhöhst.
