### ISSUE TITLE
Anzeigefehler auf älteren Geräten

### ISSUE THREAD

**Issue by scramer75** [inventwo/ioBroker.vis-inventwo#84]
Mal per copy and paste. muss ja nicht alles neu schreiben...

Hab die VIS neu gemacht, unter Nutzung der iventwo Widgets.
Nun habe ich das Problem, dass auf meinem iPad3 und auch auf dem alten GalaxyTab3 weder die Fensternavigation angezeigt wird, noch z.B. das coronavirus-stats. Andere Sachen (Werte, Berechnungen, Uhr, Wetter etc schon).
weder in der ioBroker App noch im Explorer
Auf meinem PC und auf dem iPad Air2 funzt es ohne Probleme.

Woran könnte es liegen? Gibt es Lösungen.
Hab Tante google auch schon bemüht aber bisher keine Lösung gefunden...

Auf dem 1.Bild (iPad Air2) sieht man, wie es aussehen sollte...
![123275467_3962817057079571_6984279034757735119_n](https://user-images.githubusercontent.com/59125562/98242905-6ddc9100-1f6d-11eb-9615-e80d2f94edf0.jpg)

Und so sieht es auf den älteren Geräten aus, es fehlen die wichtigen Fensterverknüpfungen. 
Nur in der App ioBroker.vis , im Safari Explorer läd er sich tot,  im Chrome läuft es einwandfrei (mit langen Ladezeiten).

Edit: im FullyBrowser fehlt ebenfalls die Hälfte auf dem GalaxyTab, analog zur App

Samsung Galaxy Tab 3 (Gt-P5200), Android 4.4.2
![123336392_3962817070412903_4824801603932478700_n](https://user-images.githubusercontent.com/59125562/98242987-92386d80-1f6d-11eb-99e0-e281c8b7c1a4.jpg)

iPad 3 Vers. 9.3.5
![123381341_3962817193746224_8977782361330167359_n](https://user-images.githubusercontent.com/59125562/98243432-3a4e3680-1f6e-11eb-95a6-fc60f0dde561.jpg)

Adapter sind alle aktuell (daran dürfte es aber eigentlich nicht liegen...

**Comment by jkvarel** [comment]
Leider fehlen hier die Angaben, nach denen ich auf Facebook gefragt habe...

Vermutlich sind die Geräte zu alt. Oder eher die Version der Betriebssysteme (Android 4.4.2 von 2013 und iOS 9.3.5 von 2016)
Unser Adapter ist dank einem Script, welches auch von anderen Adapter benutzt wird, immer auf dem aktuellen Stand, was Abhängigkeiten angeht, Daher kann es gut sein, dass die Widgets auf älteren Geräten nicht funktionieren.

Das gleiche gilt wohl auch für den coronavirus-stat Adapter (der nicht von uns ist).

**Comment by smet-o** [comment]
Ich habe das gleiche Problem auf dem iPad 3 (iOS 9.3.5). Wie vermutet funktioniert der coronavirus Adapter auch nicht. 

Eine Lösung ist demnach auch nicht in Sicht? Für weitere Infos und Test stehe ich gern zur Verfügung!

**Comment by jkvarel** [comment]
Da es keine Lösung dafür gibt schließe ich das Issue. Ich hoffe, dass ihr anderweitig das Problem lösen konntet. Das der Adapter und auch andere nicht auf älteren Geräten läuft tut uns leid aber da können wir nichts dran ändern.

Wenn ihr weitere Fragen und/oder Probleme habt, dann macht gerne ein neues Issue auf oder fragt auf Discord nach :)
