### ISSUE TITLE
Wert erhöhen oder senken Button

### ISSUE THREAD

**Issue by Kespri** [inventwo/ioBroker.vis-inventwo#87]
Könnt ihr noch ein Widget Typ  hinzufügen, mit welchem man ein Wert erhöhen oder senken kann?

Könnte man gut gebrauchen für z.B. Heizungen, um den Wert +1 oder -1 stufenweise zu ändern, je nach Wert wo man dann eingeben könnte?
Es gibt zwar schon ein Button im VIS, welcher das kann, aber der ist nicht so toll und müsste besonders angepasst werden oder über ein Background gelegt werden, was auch nicht so toll wäre, daher die Bitte nach einem nachreichen eines solchen Buttons.

Der Widget-Typ State würde sich dafür anbieten, oder in diesem Style, leider erkennt er den Wert +0.5 nicht und erhöht somit den Wert um 0.5 nicht - hoffe dies ist möglich.

Danke für eure tolle Arbeit - gefällt mir immer mehr, beim erstellen einer neuen VIS ;-)

**Comment by jkvarel** [comment]
@Kespri das würde sogar jetzt schon mit einem Binding klappen. Im Feld Wert einfach folgendes eintrage:
{wert:<Datenpunkt>; parseInt(wert)+1}
Z.B: {wert:0_userdata.0.Neues_Objekt; parseInt(wert)+1}
Wenn du um eine Kommazahl erhöhen möchtest, dann statt "parseInt" "parseFloat" nutzen

Aber es kommt noch ein extra Widget oder Widget Typ dazu ;)

**Comment by Kespri** [comment]
In der Tat, was es nicht alles für Möglichkeiten gibt bei ioBroker!

Was ich aber dadurch bemerkt habe, es fehlt die Funktion, das Absenden zu verzögern, wenn man mehrmals drückt, müsste es die Zahl kumulieren können und erst dann den Wert senden. Sonst muss man nach einem drücken erst mal warten, dass der Wert übermittelt wurde, bevor man ein zweites oder drittes Mal drückt.

**Comment by jkvarel** [comment]
Das lässt sich leider nicht ändern.

**Comment by jkvarel** [comment]
Bei Universal- und Multi-Widget kann jetzt beim Widget Typ "IncreaseDecreaseValue" ausgewählt werden. Damit lassen sich Werte erhöhen oder senken. Version 2.6.0 (latest)
