### ISSUE TITLE
Anzeigefehler in der iOBroker.vis App auf Android

### ISSUE THREAD

**Issue by ZikeDE** [inventwo/ioBroker.vis-inventwo#88]
*Screenshots & Logfiles**  
Desktop:
![20201111_034529](https://user-images.githubusercontent.com/74279387/98759245-fd040180-23d0-11eb-8559-b6104f14f6b9.jpg)
Galaxy Tab 4 10.1:
![20201111_034552](https://user-images.githubusercontent.com/74279387/98759248-ff665b80-23d0-11eb-9fc7-9e049d20ee72.jpg)

**Versions:**  
 - Adapter version: 1.3.8
 - JS-Controller version: 3.1.6
 - Node version: v12.19.0
 - Operating system: linux

**Additional context**  

Guten Tag,

Ich nutze das "Plugin" schon einige Zeit ohne Probleme im Browser, doch nun möchte ich die VIS gerne auf einem Android Tablet nutzen. Doch leider werden in der VIS App unter Android eure Widgets nicht angezeigt.

Getestet auf einem Samsung Galaxy Tab 4 10.1, einem Samsung Galaxy Note 9 und einem Galaxy Note 20 Ultra 5G. In Chrome läuft alles bestens. Woran könnte das Liegen? Ich zweifel schon an meiner Kompetenz.

MfG Jerry

**Comment by jkvarel** [comment]
Hallo @ZikeDE 
Die Widgets sind noch nicht richtig in der App drin. Das muss man erst noch beantragen. Da wir kurz vor der nächsten Stable Version sind (v2.x.x) lohnt es jetzt nicht für die 1.3.8 das zu beantragen.
Solange die Widgets nicht in der App sind kannst du auf alternativen zurückgreifen. Wir nutzen auf mobilen Geräten den 
Fully Kiosk Browser.

**Comment by ZikeDE** [comment]
Hallo @jkvarel jkvarel,

das hört sich doch gut an und Danke für die Lösung. Ist die Implementierung in die VIS App mit der neuen Stable Version geplant?

**Comment by jkvarel** [comment]
@ZikeDE ja das ist auf jeden Fall geplant. Ich kann dir aber kein Datum nennen

**Comment by jkvarel** [comment]
Zur Info: Aufnahme der neuen Widgets in die App habe ich nachgefragt. Wann das passiert kann ich aber nicht sagen

**Comment by GreatEMU** [comment]
Ich habe auch das Problem, dass die Inventwo-Widgets nicht auf meinem Android-Tablet angezeigt werden.
Habe ich das hier richtig verstanden, dass es (noch) gar nicht funktioniert?

**Comment by jkvarel** [comment]
Mit der Android App funktionieren die Widgets leider noch nicht. Die wurden leider noch nicht aufgenommen.

Mit welcher Version klappte es im alten Projekt nicht? Hattest du vorher ein Update gemacht?

**Comment by GreatEMU** [comment]
Meine Erstinstallation war (glaube ich) mit einer Version 5.2 (?).
Die Android-Integration ist nicht weiter tragisch, da ich nun mit dem WallPanel arbeite. Das funktioniert ganz prima.

Bevor ich mit dem neuen Projekt neu angefangen habe ich es mehrmals versucht. Aber auf bestehenden Views hat es einfach nichts angezteigt.

**Comment by GermanBluefox** [comment]
App 2.2.0 hat inwentwo 2.7.5 drin.

**Comment by udoamb** [comment]
Warum bekomme ich auf meinem s20fe keine vis app 2.2? Bei meinem galaxy gab womter ist habe ich gestern  geladen war sofort die Version 2.2.0 drauf

**Comment by jkvarel** [comment]
Ich habe die Version 2.2.0 auch noch nicht. Vielleicht kann @GermanBluefox was dazu sagen? Ist die Version nur für bestimmte Geräte freigeschaltet?

**Comment by jkvarel** [comment]
Ich hab heute mal in die App geguckt und bei mir werden die Widgets jetzt angezeigt. Die Widgets sind also in der App drin. Ich schließe das Issue daher. Sollten neue Fragen und/oder Probleme auftreten könnt ihr gerne ein neues Issue aufmachen

**Comment by udoamb** [comment]
Was hast du eingestellt damit er alles anzeigt?

Jannis <notifications@github.com> schrieb am Mi., 17. Feb. 2021, 18:44:

**Comment by jkvarel** [comment]
@udoamb nichts weiter. Mit der Version 2.2.0 werden die angezeigt
