### ISSUE TITLE
Multi Switch

### ISSUE THREAD

**Issue by McWoolf** [inventwo/ioBroker.vis-inventwo#89]
Sorry Leute!

Ich glaub ich bin für dieses Widget zu dämlich.
Ich habe alle Zustände eingetragen, einen datenpunkt angelegt in die er schreiben soll. 
Nur tut das Ding nicht was es soll, es ist zum Haare ausrauffen. Wie muss ich das Widget verstehen, damit es richtig funktioniert?
![1](https://user-images.githubusercontent.com/73942255/99181837-75e8bd80-2731-11eb-8eca-0b956ce960b5.PNG)
![2](https://user-images.githubusercontent.com/73942255/99181886-a6c8f280-2731-11eb-8a2e-02426e0463c1.PNG)
![3](https://user-images.githubusercontent.com/73942255/99181908-be07e000-2731-11eb-9822-82aefe795dfc.PNG)
![Datenpunkt](https://user-images.githubusercontent.com/73942255/99181934-edb6e800-2731-11eb-9f6a-2f6c64ee6302.PNG)

Hier ein paar Einstellungen, ich hoffe jemand kann mir helfen.
Danke schon mal im voraus.

**Comment by McWoolf** [comment]
Ja ich versuche ja eine Navigation zu erstellen, aber irgendwie stell ich mir die funktionsweise anders vor, als sie tatsächlich ist. Mir geht es um die Navigation. 
Ich verstehe es so:
Ich erstell in einer Start-View ein Multiswitch hinterlege dann alle weiteren View´s und lasse den Multiswitch auf jedem View anzeigen. So und jetzt stehe ich auf dem Schlauch, wie kann ich dann das gewünschte View anwählen??? oder warum komme ich auf ein View und bleib dann da hängen?
Wie gesagt ich verstehe diesen Multiswitch denk ich jetzt mal nur falsch.
Danke für eure Hilfe.

PS: Als Schalter hab ich das Universalwidget hergenommen.

**Comment by skvarel** [comment]
Hallo @McWoolf .. warum muss es ein Multi-Widget sein? Brauchst Du mehere Prüfungen?

Hier ein Beispiel für eine Navigation, die auf meheren Views (immer an der gelichen Stelle) angezeigt wird.

Das funktioniert natürlich auch mit dem Multi-Widget, die Konfiguration ist aber etwas aufwendiger.

![grafik](https://user-images.githubusercontent.com/1114419/99223447-cec55e00-27e4-11eb-9bc9-872ab0b5f039.png)

**Comment by skvarel** [comment]
Unsere Multi-Widgets (als Nav) schalten auch NUR EINE WIEV, können aber auf mehere prüfen.

Als Beispiel:
• Die Nav für das Erdgeschoss soll auf der 'Erdgeschoss View' UND auf der 'Garten View' als aktiv angezeigt werden. Dafür benötigt man dann das Multi-Widget. Es prüft dann, auf welcher View man sich befindet und zeigt bei jedem eingtragenen Zustand 'aktiv' an.

Es wird aber trotzdem nur die View geschaltet, die man oben eingibt!

In den meisten Fällen reicht das Unvisal-Widget.

**Comment by McWoolf** [comment]
Ok dann habe ich das komplett falsch verstanden.
Ich dachte ich habe einen "Schalter" der dann automatisch checkt auf welcher View man sich befindet und dann automatisch den wert umschreibt um auf eine andere View zu kommen..................... naja Knoten im Hirn.
@skvarel aber was macht das dann für einen Sinn mehrere View´s als aktiv zu setzen? Ich kann pro Gerät ja nur eine View aufrufen?!

**Comment by skvarel** [comment]
Hier nutze ich das Multi-Widget als Navigation.

Die Schaltfläche für inventwo soll aifd mehren Views als aktiv angezeigt werden.

Als Ziel wird unter 'allgemein' die View eingetragen. Nur diese wird geschaltet! Bei 'Zeige in Views' trage ich ein, wo das Widget überall zu sehen sein soll.

![grafik](https://user-images.githubusercontent.com/1114419/99224136-0a145c80-27e6-11eb-859d-4d895f46aa09.png)

Jetzt kommen die 'Zustände'

Hier legt man fest, auf welcher View das Widget aktiv angezeigt werden soll

![grafik](https://user-images.githubusercontent.com/1114419/99224350-75f6c500-27e6-11eb-83c3-f4dcd0c15388.png)

**Comment by skvarel** [comment]
@McWoolf 

Die werden NICHT geschaltet, sonder nur aktiv angezeigt.

Beisdpiel:

![grafik](https://user-images.githubusercontent.com/1114419/99224443-9fafec00-27e6-11eb-9512-f77026e748de.png)

![grafik](https://user-images.githubusercontent.com/1114419/99224472-a9d1ea80-27e6-11eb-8cd8-06020e5d8b6e.png)


Hier will ich mehrer Views unter dem Nav 'inventwo' angezeigt bekommen. Es sind verschiede Views, gehören aber zu inventwo

**Comment by skvarel** [comment]
Das dient dann nur zur Orientierung.

Zeites Beispiel, mein Keller.

Einmal die Übersicht und einmal der Zähler. Beides gehört zum 'Kellergeschoss'


![grafik](https://user-images.githubusercontent.com/1114419/99224582-e0a80080-27e6-11eb-84cc-67cd8c5258b7.png)

![grafik](https://user-images.githubusercontent.com/1114419/99224645-0208ec80-27e7-11eb-8af5-39b636e77eb6.png)

**Comment by McWoolf** [comment]
He Leute super i glaub i habs jetzt gecheckt!
Also ich muss dennoch für jede View eigene Buttons mit eigener Config anlegen, sie sehen nur gleich aus (und werden auf aktiv gesetzt) danke nochmals für eure Hilfe, somit macht das widget eigentlich ja nur Sinn, wenn man z.B. für ein Stockwerk mehrere View´s hat?!

**Comment by skvarel** [comment]
Ein Beispiel für das Multi-Widget als 'Background'

8 Zustände für die Mülltonnen. Es wird mit dem Widget nur geprüpft, nichts geschaltet.

Zwei Abfragen pro Mülltonne. Je Tonne wird geprüft ob sie heute oder morgen dran ist.

![grafik](https://user-images.githubusercontent.com/1114419/99224834-56ac6780-27e7-11eb-97f8-0e045e1b3b64.png)

Man muss sich nur verinnerlichen, das Multi-Widget prüft alle eingegeben Zustände, schaltet aber NUR den Datenpunkt, den man unter 'Allgemein' angibt.

**Comment by skvarel** [comment]
@McWoolf 

Genau. mehere Views pro Stockwerk. So passt die Beschreibung.

Du brauchst aber nur PRO Navigation zu einer View, ein Widget und kopierst es über die Funktion 'Zeige in Views' auf alle gewünschten Seiten.

![grafik](https://user-images.githubusercontent.com/1114419/99225191-f4079b80-27e7-11eb-922c-fac81ce71187.png)

Das sind 6 einzelne Widgets, die ich per 'Zeige in Views' auf alle 15 Views kopiere. So sind sie immer an der gleichen Stelle und ich muss sie nur auf einer View konfigurieren. Die Einstellungen gelten dann für ALLE Views.

**Comment by skvarel** [comment]
Vielleicht hilft unsere Wiki auch bei der Entscheidung, ob das Universal- oder das Multi-Widget das Richtige ist. Die Anleitung ist noch nicht ganz fertig, sollte aber schon etwas helfen.

https://github.com/inventwo/ioBroker.vis-inventwo/wiki/Widget-Erkl%C3%A4rungen-ab-Version-2.x.x

**Comment by jkvarel** [comment]
Ich denke die Frage wurde geklärt? Sollten neue Fragen aufkommen gerne ein neues Issue aufmachen oder bei Discord vorbeischauen
