### ISSUE TITLE
Kann das Kommando "setState" für vis-inventwo.0.CSS. nicht ausführen, weil nicht genügend Zugriffsrechte vorhanden sind.

### ISSUE THREAD

**Issue by ppb1308** [inventwo/ioBroker.vis-inventwo#92]
Hallo,

nach Update heute (auf 2.5.9) kommt beim Start der Visulaisierung der folgende Fehler:

Kann das Kommando "setState" für vis-inventwo.0.CSS. nicht ausführen, weil nicht genügend Zugriffsrechte vorhanden sind.

**Versions:**  
 - Adapter version: 2.5.9
 - JS-Controller version: 3.1.6
 - Node version: v12.18.3
 - Operating system: Ubuntu@ProxMox@NUC

Gruß,
Peter

**Comment by skvarel** [comment]
Wir arbeiten daran. Leider ist zu Zeit ein Downgrade auf 2.5.8 die einzige Lösung.

**Comment by ppb1308** [comment]
ok, nach Downgrade ist es weg.
Schön, dass Ihr es Euch anschaut.
Danke.

**Comment by jkvarel** [comment]
@ppb1308 bitte einmal mit der neuen Version (v2.5.10) versuchen

**Comment by ppb1308** [comment]
@jkvarel Die Version 2.5.10 ist bei mir leider noch nicht verfügbar, muss ich sicher in ioBroker aktualisieren, nur wie?

**Comment by ppb1308** [comment]
@jkvarel  Habs über das GitHub Icon installiert, ist nun 2.5.10 und Fehler ist nicht mehr aufgetreten nach Reload der Vis.

**Comment by michad2** [comment]
Moin,

mit der Version 2.5.10 werden gruppierte Widgets geschrottet 
![Schrott](https://user-images.githubusercontent.com/34954601/99357607-79548400-28ac-11eb-9a9c-dfd65b501d65.jpg)


![OK](https://user-images.githubusercontent.com/34954601/99357685-9be69d00-28ac-11eb-8dff-4e64c0af8422.jpg)

nach Rückschritt auf die 2.5.8 ist alles wieder ok, mehrfach getestet
Gruß Micha

**Comment by skvarel** [comment]
Da wird nichts geschrottet. Du kannst hier mal bitte alle Widgets einzeln durchklicken, dann sind sie wieder da.

![grafik](https://user-images.githubusercontent.com/1114419/99413382-007a1a00-28f6-11eb-9c4b-ce8f91b5aeec.png)


Das nächste mal, bitte bei einem neuen Fehler auch ein neues Issue erstellen.

Dieses Problem hat nichst mit dem Fehler in diesem Issue Titel zu tun

Gruß, Sven.
