### ISSUE TITLE
Nach Update 2.5.9: Fehlermeldung "kann das Kommando "setState" für vis-inventwo.0.CSS. nicht ausführen, weil nicht genügend Zugriffsrechte

### ISSUE THREAD

**Issue by Aare07** [inventwo/ioBroker.vis-inventwo#93]
Nach dem Update auf die neuste Version 2.5.9. erhalte ich beim Zugriff auf jedwelche View folgende Popup Fehlermeldung im Vis Runtime:
"Nicht genügend Zugriffsrechte: Kann das Kommando "setState" für vis-inventwo.0.CSS. nicht ausführen, weil nicht genügend Zugriffsrechte vorhanden sind."

Ich habe weder Benutzer noch Zugriffsrechte eingerichtet
ioBroker mit Node.js Version 12.19.0 
Alle Plugins aktuell (latest)
Restart der Adapter Web, Vis, Inventwo hat nicht geholfen

Loglevel bei Inventwo, Vis, Web auf Debug gestellt und bei Viewanzeige folgende Einträge. Ob die Zeile "Request authenticate" schon früher da war kann ich leider nicht sagen.
[Debug-Log-vis-Abfrage20201116.txt](https://github.com/inventwo/ioBroker.vis-inventwo/files/5545371/Debug-Log-vis-Abfrage20201116.txt)

**Comment by skvarel** [comment]
Wir arbeiten daran. Leider ist zu Zeitein Downgrade auf 2.5.8 die einzige Lösung.

**Comment by skvarel** [comment]
Bitte keine doppelten Issues bei gleichen Fehlern:

https://github.com/inventwo/ioBroker.vis-inventwo/issues/92

**Comment by Aare07** [comment]
Ja bitte dieses Issue schliessen, hatte vor dem Erfassen geprüft war aber einige Minuten zu langsam beim Schreiben... ;)
