### ISSUE TITLE
Buttons verschwunden nach Update auf 2.5.11

### ISSUE THREAD

**Issue by tigertim08** [inventwo/ioBroker.vis-inventwo#99]
Guten Morgen zusammen, 

ich habe gestern ein Update des Inventwo Designs auf 2.5.11 gemacht und dabei hat es mir die VIS zerschossen. Ich war dabei die Buttons auf die neuen umzustellen mit dem Update sind aber alle neuen verschwunden.... Hat dieses Phänomen noch jemand?

**Versions:**  
 - Adapter version: 2.5.11
 - JS-Controller version: 3.16
 - Node version: 2.18.2
 - Operating system: Debian

![2020-12-01_09-09-18](https://user-images.githubusercontent.com/24661102/100714986-d7a65a00-33b6-11eb-9f49-b30d7efa915a.png)

**Comment by beef76** [comment]
selbiges hab ich eben mit den Radio buttons gemeldet. ABER! Nach einem kompletten restart des ioBrokers alles wieder da, schon probiert?

**Comment by tigertim08** [comment]
Ja habe einen reboot gemacht allerdings ohne Veränderung

**Comment by tigertim08** [comment]
Danke an Sven! Jetzt werden alle wieder angezeigt. Mann muss die Widgets einmal aktivieren (danach wieder deaktivieren; mehrere auf einmal hat bei mir nicht funktioniert) damit es wieder angezeigt wird.
